// Generated by ts-to-zod
import * as z from "zod/mini";
import { AdyenPaymentMethodsConfigurationCardBillingAddressMode } from '../models/AdyenPaymentMethodsConfigurationCardBillingAddressMode';
export const adyenPaymentMethodsConfigurationCardBillingAddressModeSchema = z.enum(AdyenPaymentMethodsConfigurationCardBillingAddressMode);
