// Generated by ts-to-zod
import * as z from 'zod/mini';
import { adyenPaymentMethodsConfigurationGooglePayBillingAddressParametersSchema } from './AdyenPaymentMethodsConfigurationGooglePayBillingAddressParameters';
export const adyenPaymentMethodsConfigurationGooglePaySchema = z.object({
	billingAddressRequired: z.boolean(),
	billingAddressParameters: adyenPaymentMethodsConfigurationGooglePayBillingAddressParametersSchema,
});
