// Generated by ts-to-zod
import * as z from "zod/mini";
import { adyenGatewaySessionSchema } from './AdyenGatewaySession';
import { adyenPaymentMethodsConfigurationSchema } from './AdyenPaymentMethodsConfiguration';
export const adyenGatewaySchema = z.object({
    environment: z.optional(z.string()),
    clientKey: z.optional(z.string()),
    session: z.nullable(z.optional(adyenGatewaySessionSchema)),
    countryCode: z.optional(z.string()),
    paymentMethodsConfiguration: z.optional(adyenPaymentMethodsConfigurationSchema),
});
