// Generated by ts-to-zod
import * as z from "zod/mini";
export const adyenPaymentMethodsConfigurationPayPaySchema = z.object({
    blockPayPalCreditButton: z.boolean(),
    blockPayPalPayLaterButton: z.boolean(),
    blockPayPalVenmoButton: z.boolean(),
});
