// Generated by ts-to-zod
import * as z from 'zod/mini';
import { availableLanguagesItemSchema } from './AvailableLanguagesItem';
export const articleSchema = z.object({
	id: z.string(),
	bannerImageUrl: z.nullable(z.string()),
	coverImageUrl: z.nullable(z.string()),
	href: z.nullable(z.string()),
	keywords: z.array(z.string()),
	meta: z.record(z.string(), z.string()),
	shortDescription: z.nullable(z.string()),
	title: z.nullable(z.string()),
	videoUrl: z.nullable(z.string()),
	availableLanguages: z.nullable(availableLanguagesItemSchema),
});
