// Generated by ts-to-zod
import * as z from 'zod/mini';
import { resourceSchema } from './Resource';
import { sellerSchema } from './Seller';
import { seatSchema } from './Seat';
import { availabilityStatusSchema } from './AvailabilityStatus';
export const availabilityResourceSchema = z.object({
	resourceId: z.string(),
	resource: resourceSchema,
	driver: z.nullable(sellerSchema),
	guide: z.nullable(sellerSchema),
	availableSeats: z.array(seatSchema),
	selectedSeats: z.array(seatSchema),
	available: z.boolean(),
	status: availabilityStatusSchema,
	statusMessage: z.string(),
	statusCode: z.string(),
	vacancies: z.nullable(z.number()),
	capacity: z.nullable(z.number()),
	maxUnits: z.nullable(z.number()),
	totalCapacity: z.nullable(z.number()),
	limitCapacity: z.nullable(z.number()),
	limitPaxCount: z.number(),
	maxPaxCount: z.nullable(z.number()),
	noShows: z.number(),
	paxCount: z.number(),
	totalNoShows: z.number(),
	totalPaxCount: z.number(),
});
