// Generated by ts-to-zod
import * as z from "zod/mini";
import { pricingUnitSchema } from './PricingUnit';
import { pricingSchema } from './Pricing';
export const availabilityCalendarPricingSchema = z.object({
    unitPricingFrom: z.optional(z.array(pricingUnitSchema)),
    pricingFrom: z.optional(pricingSchema),
});
