// Generated by ts-to-zod
import * as z from "zod/mini";
import { packageAvailabilitySchema } from './PackageAvailability';
export const availabilityPackagesSchema = z.object({
    packageAvailabilities: z.optional(z.array(packageAvailabilitySchema)),
});
