// Generated by ts-to-zod
import * as z from "zod/mini";
import { extraPricingSchema } from './ExtraPricing';
export const availabilityExtrasSchema = z.object({
    extraPricing: z.optional(z.array(extraPricingSchema)),
});
