// Generated by ts-to-zod
import * as z from "zod/mini";
import { availabilityStatusSchema } from './AvailabilityStatus';
import { openingHoursSchema } from './OpeningHours';
import { sellerSchema } from './Seller';
import { pickupPointSchema } from './PickupPoint';
import { dropoffPointSchema } from './DropoffPoint';
import { pricingUnitSchema } from './PricingUnit';
import { pricingSchema } from './Pricing';
import { offerSchema } from './Offer';
import { tourGroupSchema } from './TourGroup';
import { fareSchema } from './Fare';
import { noticeSchema } from './Notice';
import { extraPricingSchema } from './ExtraPricing';
import { mappingSchema } from './Mapping';
import { packageAvailabilitySchema } from './PackageAvailability';
export const availabilitySchema = z.object({
    id: z.string(),
    localDateTimeStart: z.string(),
    localDateTimeEnd: z.string(),
    utcCutoffAt: z.string(),
    utcOnsaleAt: z.nullable(z.string()),
    allDay: z.boolean(),
    available: z.boolean(),
    status: availabilityStatusSchema,
    statusCode: z.string(),
    statusMessage: z.string(),
    vacancies: z.nullable(z.number()),
    capacity: z.nullable(z.number()),
    maxUnits: z.nullable(z.number()),
    openingHours: z.array(openingHoursSchema),
    driver: z.nullable(sellerSchema),
    guide: z.nullable(sellerSchema),
    internalName: z.optional(z.string()),
    tags: z.optional(z.array(z.string())),
    reference: z.nullable(z.string()),
    totalCapacity: z.nullable(z.number()),
    totalMaxWeight: z.nullable(z.optional(z.number())),
    paxWeight: z.optional(z.number()),
    maxWeight: z.nullable(z.optional(z.number())),
    weightUnit: z.nullable(z.optional(z.string())),
    availableWeight: z.nullable(z.optional(z.number())),
    limitCapacity: z.nullable(z.number()),
    limitPaxCount: z.number(),
    noShows: z.number(),
    totalNoShows: z.number(),
    totalPaxCount: z.number(),
    paxCount: z.number(),
    maxPaxCount: z.nullable(z.number()),
    pickupAvailable: z.optional(z.boolean()),
    pickupRequired: z.optional(z.boolean()),
    pickupPoints: z.optional(z.array(pickupPointSchema)),
    dropoffAvailable: z.optional(z.boolean()),
    dropoffRequired: z.optional(z.boolean()),
    dropoffPoints: z.optional(z.array(dropoffPointSchema)),
    unitPricing: z.optional(z.array(pricingUnitSchema)),
    pricing: z.optional(pricingSchema),
    offerCode: z.nullable(z.optional(z.string())),
    offerTitle: z.nullable(z.optional(z.string())),
    offers: z.optional(z.array(offerSchema)),
    offer: z.nullable(z.optional(offerSchema)),
    meetingPoint: z.nullable(z.optional(z.string())),
    meetingPointCoordinates: z.nullable(z.optional(z.string())),
    meetingPointDirections: z.nullable(z.optional(z.string())),
    meetingPointLatitude: z.nullable(z.optional(z.number())),
    meetingPointLongitude: z.nullable(z.optional(z.number())),
    meetingLocalDateTime: z.nullable(z.optional(z.string())),
    tourGroup: z.nullable(z.optional(tourGroupSchema)),
    fare: z.nullable(z.optional(fareSchema)),
    notices: z.optional(z.array(noticeSchema)),
    extraPricing: z.optional(z.array(extraPricingSchema)),
    hasResources: z.optional(z.boolean()),
    mappings: z.optional(z.array(mappingSchema)),
    packageAvailabilities: z.optional(z.array(packageAvailabilitySchema)),
});
