// Generated by ts-to-zod
import * as z from 'zod/mini';
import { extraPricingSchema } from './ExtraPricing';
export const availabilityCalendarExtrasSchema = z.object({
	extraPricingFrom: z.optional(z.array(extraPricingSchema)),
});
