// Generated by ts-to-zod
import * as z from "zod/mini";
import { uuidSchema } from './UUID';
export const availabilityCalendarBatchBodySchema = z.object({
    productId: z.optional(z.string()),
    productIds: z.optional(z.array(uuidSchema)),
    localDateStart: z.string(),
    localDateEnd: z.string(),
});
