// Generated by ts-to-zod
import * as z from "zod/mini";
import { offerSchema } from './Offer';
export const availabilityCalendarOffersSchema = z.object({
    offerCode: z.nullable(z.optional(z.string())),
    offerTitle: z.nullable(z.optional(z.string())),
    offers: z.optional(z.array(offerSchema)),
    offer: z.nullable(z.optional(offerSchema)),
});
