// Generated by ts-to-zod
import * as z from 'zod/mini';
import { availabilityUnitSchema } from './AvailabilityUnit';
export const availabilityCalendarBodySchema = z.object({
	productId: z.string(),
	optionId: z.string(),
	localDateStart: z.string(),
	localDateEnd: z.string(),
	units: z.optional(z.array(availabilityUnitSchema)),
	uuid: z.optional(z.string()),
	currency: z.nullable(z.optional(z.string())),
});
