// Generated by ts-to-zod
import * as z from 'zod/mini';
import { unitTypeSchema } from './UnitType';
export const availabilityUnitSchema = z.object({
	id: z.optional(z.string()),
	type: z.optional(unitTypeSchema),
	quantity: z.number(),
});
