// Generated by ts-to-zod
import * as z from "zod/mini";
import { pickupPointSchema } from './PickupPoint';
import { dropoffPointSchema } from './DropoffPoint';
export const availabilityPickupsSchema = z.object({
    pickupAvailable: z.optional(z.boolean()),
    pickupRequired: z.optional(z.boolean()),
    pickupPoints: z.optional(z.array(pickupPointSchema)),
    dropoffAvailable: z.optional(z.boolean()),
    dropoffRequired: z.optional(z.boolean()),
    dropoffPoints: z.optional(z.array(dropoffPointSchema)),
});
