// Generated by ts-to-zod
import * as z from "zod/mini";
import { tourGroupSchema } from './TourGroup';
import { fareSchema } from './Fare';
import { noticeSchema } from './Notice';
export const availabilityContentSchema = z.object({
    meetingPoint: z.nullable(z.optional(z.string())),
    meetingPointCoordinates: z.nullable(z.optional(z.string())),
    meetingPointDirections: z.nullable(z.optional(z.string())),
    meetingPointLatitude: z.nullable(z.optional(z.number())),
    meetingPointLongitude: z.nullable(z.optional(z.number())),
    meetingLocalDateTime: z.nullable(z.optional(z.string())),
    tourGroup: z.nullable(z.optional(tourGroupSchema)),
    fare: z.nullable(z.optional(fareSchema)),
    notices: z.optional(z.array(noticeSchema)),
});
