// Generated by ts-to-zod
import * as z from 'zod/mini';
import { availabilityUnitSchema } from './AvailabilityUnit';
export const availabilityCheckBodySchema = z.object({
	productId: z.string(),
	optionId: z.optional(z.string()),
	uuid: z.optional(z.string()),
	localTime: z.optional(z.string()),
	localDate: z.optional(z.string()),
	localDateStart: z.optional(z.string()),
	localDateEnd: z.optional(z.string()),
	availabilityIds: z.optional(z.array(z.string())),
	units: z.optional(z.array(availabilityUnitSchema)),
	currency: z.nullable(z.optional(z.string())),
});
