// Generated by ts-to-zod
import * as z from "zod/mini";
export const availabilityResourcesQueryParamsSchema = z.object({
    productId: z.string(),
    optionId: z.optional(z.string()),
    availabilityId: z.string(),
});
