// Generated by ts-to-zod
import * as z from "zod/mini";
import { pricingUnitSchema } from './PricingUnit';
import { pricingSchema } from './Pricing';
export const availabilityPricingSchema = z.object({
    unitPricing: z.optional(z.array(pricingUnitSchema)),
    pricing: z.optional(pricingSchema),
});
