// Generated by ts-to-zod
import * as z from "zod/mini";
import { availabilityStatusSchema } from './AvailabilityStatus';
import { openingHoursSchema } from './OpeningHours';
import { pricingUnitSchema } from './PricingUnit';
import { pricingSchema } from './Pricing';
import { offerSchema } from './Offer';
import { extraPricingSchema } from './ExtraPricing';
export const availabilityCalendarSchema = z.object({
    localDate: z.string(),
    localDateTimeStart: z.nullable(z.string()),
    localDateTimeEnd: z.nullable(z.string()),
    available: z.boolean(),
    status: availabilityStatusSchema,
    statusCode: z.string(),
    statusMessage: z.string(),
    vacancies: z.nullable(z.number()),
    capacity: z.nullable(z.number()),
    openingHours: z.array(openingHoursSchema),
    productId: z.optional(z.string()),
    optionId: z.optional(z.string()),
    limitCapacity: z.nullable(z.number()),
    totalCapacity: z.nullable(z.number()),
    totalMaxWeight: z.nullable(z.number()),
    totalPaxWeight: z.number(),
    paxWeight: z.number(),
    maxWeight: z.nullable(z.number()),
    weightUnit: z.nullable(z.string()),
    availableWeight: z.nullable(z.number()),
    limitPaxCount: z.number(),
    noShows: z.number(),
    totalNoShows: z.number(),
    totalPaxCount: z.number(),
    maxUnits: z.nullable(z.number()),
    maxPaxCount: z.nullable(z.number()),
    paxCount: z.number(),
    utcCutoffAt: z.string(),
    utcOnsaleAt: z.nullable(z.string()),
    availabilityLocalStartTimes: z.array(z.string()),
    unitPricingFrom: z.optional(z.array(pricingUnitSchema)),
    pricingFrom: z.optional(pricingSchema),
    offerCode: z.nullable(z.optional(z.string())),
    offerTitle: z.nullable(z.optional(z.string())),
    offers: z.optional(z.array(offerSchema)),
    offer: z.nullable(z.optional(offerSchema)),
    extraPricingFrom: z.optional(z.array(extraPricingSchema)),
});
