// Generated by ts-to-zod
import * as z from "zod/mini";
export const bookingCheckinSchema = z.object({
    checkedIn: z.optional(z.boolean()),
    checkinAvailable: z.optional(z.boolean()),
    checkinUrl: z.nullable(z.optional(z.string())),
});
