// Generated by ts-to-zod
import * as z from 'zod/mini';
import { bookingAdjustmentSchema } from './BookingAdjustment';
export const bookingAdjustmentsSchema = z.object({
	adjustments: z.optional(z.array(bookingAdjustmentSchema)),
});
