// Generated by ts-to-zod
import * as z from "zod/mini";
import { questionAnswerSchema } from './QuestionAnswer';
export const bookingQuestionsSchema = z.object({
    questionAnswers: z.optional(z.array(questionAnswerSchema)),
});
