// Generated by ts-to-zod
import * as z from "zod/mini";
import { includeSchema } from './Include';
import { bookingSchema } from './Booking';
export const bookingPackagesSchema = z.object({
    isPackage: z.optional(z.boolean()),
    packageIncludeId: z.nullable(z.optional(z.string())),
    packageInclude: z.nullable(z.optional(includeSchema)),
    packageBookings: z.optional(z.array(bookingSchema)),
    packageUnitItemUuid: z.optional(z.any()),
});
