// Generated by ts-to-zod
import * as z from "zod/mini";
import { resourceAllocationRequestSchema } from './ResourceAllocationRequest';
export const bookingResourcesBodySchema = z.object({
    resourceAllocations: z.optional(z.array(resourceAllocationRequestSchema)),
});
