// Generated by ts-to-zod
import * as z from "zod/mini";
import { giftPaymentSchema } from './GiftPayment';
export const bookingGiftsSchema = z.object({
    giftPayment: z.nullable(z.optional(giftPaymentSchema)),
});
