// Generated by ts-to-zod
import * as z from "zod/mini";
import { durationUnitSchema } from './DurationUnit';
import { noticeSchema } from './Notice';
export const bookingContentSchema = z.object({
    duration: z.optional(z.string()),
    durationAmount: z.optional(z.number()),
    durationUnit: z.optional(durationUnitSchema),
    meetingLocalDateTime: z.nullable(z.optional(z.string())),
    meetingPoint: z.nullable(z.optional(z.string())),
    meetingPointCoordinates: z.nullable(z.optional(z.string())),
    meetingPointDirections: z.nullable(z.optional(z.string())),
    meetingPointLatitude: z.nullable(z.optional(z.number())),
    meetingPointLongitude: z.nullable(z.optional(z.number())),
    notices: z.optional(z.array(noticeSchema)),
    termsAccepted: z.optional(z.boolean()),
});
