// Generated by ts-to-zod
import * as z from "zod/mini";
import { rentalDurationSchema } from './RentalDuration';
export const bookingRentalsSchema = z.object({
    isRental: z.optional(z.boolean()),
    rentalDurationId: z.nullable(z.optional(z.string())),
    rentalDuration: z.nullable(z.optional(rentalDurationSchema)),
});
