// Generated by ts-to-zod
import * as z from 'zod/mini';
export const bookingCartSchema = z.object({
	primary: z.optional(z.boolean()),
	orderId: z.optional(z.string()),
	orderReference: z.optional(z.string()),
});
