// Generated by ts-to-zod
import * as z from 'zod/mini';
import { type Booking } from '../models/Booking';
import { bookingStatusSchema } from './BookingStatus';
import { productSchema } from './Product';
import { optionSchema } from './Option';
import { cancellationSchema } from './Cancellation';
import { availabilitySchema } from './Availability';
import { customerContactSchema } from './CustomerContact';
import { deliveryMethodSchema } from './DeliveryMethod';
import { ticketSchema } from './Ticket';
import { unitItemSchema } from './UnitItem';
import { pricingSchema } from './Pricing';
import { settlementMethodSchema } from './SettlementMethod';
import { agentSchema } from './Agent';
import { resellerSchema } from './Reseller';
import { contactFieldSchema } from './ContactField';
import { bookingRejectionSchema } from './BookingRejection';
import { userSchema } from './User';
import { sellerSchema } from './Seller';
import { labelSchema } from './Label';
import { pickupPointSchema } from './PickupPoint';
import { durationUnitSchema } from './DurationUnit';
import { noticeSchema } from './Notice';
import { offerComparisonSchema } from './OfferComparison';
import { offerSchema } from './Offer';
import { questionAnswerSchema } from './QuestionAnswer';
import { resourceAllocationSchema } from './ResourceAllocation';
import { giftPaymentSchema } from './GiftPayment';
import { extraItemSchema } from './ExtraItem';
import { extraPricingSchema } from './ExtraPricing';
import { includeSchema } from './Include';
import { bookingAdjustmentSchema } from './BookingAdjustment';
import { identitySchema } from './Identity';
import { membershipBenefitSchema } from './MembershipBenefit';
import { membershipSchema } from './Membership';
import { rentalDurationSchema } from './RentalDuration';
import { cardPaymentGatewaySchema } from './CardPaymentGateway';
import { mappingSchema } from './Mapping';
export const bookingSchema: z.ZodMiniType<Booking> = z.lazy(() =>
	z.object({
		id: z.string(),
		uuid: z.string(),
		testMode: z.boolean(),
		resellerReference: z.nullable(z.string()),
		supplierReference: z.nullable(z.string()),
		status: bookingStatusSchema,
		internalStatus: z.string(),
		utcCreatedAt: z.string(),
		utcUpdatedAt: z.string(),
		utcExpiresAt: z.nullable(z.string()),
		utcRedeemedAt: z.nullable(z.string()),
		utcConfirmedAt: z.nullable(z.string()),
		productId: z.string(),
		product: z.optional(productSchema),
		optionId: z.string(),
		option: z.nullable(optionSchema),
		cancellable: z.boolean(),
		cancellation: z.nullable(cancellationSchema),
		freesale: z.boolean(),
		availabilityId: z.nullable(z.string()),
		availability: z.nullable(availabilitySchema),
		contact: z.optional(customerContactSchema),
		notes: z.nullable(z.string()),
		deliveryMethods: z.array(deliveryMethodSchema),
		voucher: z.nullable(ticketSchema),
		unitItems: z.array(unitItemSchema),
		pricing: z.optional(pricingSchema),
		rebookingUuid: z.nullable(z.string()),
		originalRebookingUuid: z.nullable(z.string()),
		alias: z.nullable(z.string()),
		settlementMethod: settlementMethodSchema,
		settlementMethods: z.array(settlementMethodSchema),
		quote: z.boolean(),
		confirmable: z.boolean(),
		agent: z.nullable(agentSchema),
		reseller: z.nullable(resellerSchema),
		requiredContactFields: z.array(contactFieldSchema),
		visibleContactFields: z.array(contactFieldSchema),
		rejection: z.nullable(bookingRejectionSchema),
		utcNoshowedAt: z.nullable(z.string()),
		utcRebookedAt: z.nullable(z.string()),
		tags: z.optional(z.array(z.string())),
		user: z.nullable(userSchema),
		seller: z.nullable(sellerSchema),
		localDateTimeStart: z.string(),
		localDateTimeEnd: z.string(),
		emailReceipt: z.boolean(),
		orderNotes: z.nullable(z.string()),
		label: z.nullable(labelSchema),
		metadata: z.record(z.string(), z.any()),
		updatable: z.boolean(),
		availabilityLocalDateStart: z.nullable(z.string()),
		availabilityLocalDateEnd: z.nullable(z.string()),
		guide: z.nullable(sellerSchema),
		driver: z.nullable(sellerSchema),
		active: z.boolean(),
		pickupRequested: z.optional(z.boolean()),
		pickupHotel: z.nullable(z.optional(z.string())),
		pickupRoom: z.nullable(z.optional(z.string())),
		pickupNotes: z.nullable(z.optional(z.string())),
		pickupPoint: z.nullable(z.optional(pickupPointSchema)),
		pickupPointId: z.nullable(z.optional(z.string())),
		pickupHotelRoom: z.nullable(z.optional(z.string())),
		pickupDispatch: z.nullable(z.optional(z.string())),
		dropoffDispatch: z.nullable(z.optional(z.string())),
		duration: z.optional(z.string()),
		durationAmount: z.optional(z.number()),
		durationUnit: z.optional(durationUnitSchema),
		meetingLocalDateTime: z.nullable(z.optional(z.string())),
		meetingPoint: z.nullable(z.optional(z.string())),
		meetingPointCoordinates: z.nullable(z.optional(z.string())),
		meetingPointDirections: z.nullable(z.optional(z.string())),
		meetingPointLatitude: z.nullable(z.optional(z.number())),
		meetingPointLongitude: z.nullable(z.optional(z.number())),
		notices: z.optional(z.array(noticeSchema)),
		termsAccepted: z.optional(z.boolean()),
		primary: z.optional(z.boolean()),
		orderId: z.optional(z.string()),
		orderReference: z.optional(z.string()),
		offerCode: z.nullable(z.optional(z.string())),
		offerTitle: z.nullable(z.optional(z.string())),
		offerComparisons: z.optional(z.array(offerComparisonSchema)),
		offerIsCombination: z.optional(z.boolean()),
		offers: z.optional(z.array(offerSchema)),
		offer: z.nullable(z.optional(offerSchema)),
		questionAnswers: z.optional(z.array(questionAnswerSchema)),
		resourceAllocations: z.optional(z.array(resourceAllocationSchema)),
		giftPayment: z.nullable(z.optional(giftPaymentSchema)),
		extraItems: z.optional(z.array(extraItemSchema)),
		extraPricing: z.optional(z.array(extraPricingSchema)),
		isPackage: z.optional(z.boolean()),
		packageIncludeId: z.nullable(z.optional(z.string())),
		packageInclude: z.nullable(z.optional(includeSchema)),
		packageBookings: z.optional(z.array(bookingSchema)),
		packageUnitItemUuid: z.optional(z.any()),
		adjustments: z.optional(z.array(bookingAdjustmentSchema)),
		identity: z.optional(identitySchema),
		identityId: z.optional(z.string()),
		checkedIn: z.optional(z.boolean()),
		checkinAvailable: z.optional(z.boolean()),
		checkinUrl: z.nullable(z.optional(z.string())),
		membershipBenefit: z.nullable(z.optional(membershipBenefitSchema)),
		membership: z.nullable(z.optional(membershipSchema)),
		isMembership: z.optional(z.boolean()),
		appendMembershipValidity: z.optional(z.boolean()),
		membershipAutoRenew: z.optional(z.boolean()),
		isRental: z.optional(z.boolean()),
		rentalDurationId: z.nullable(z.optional(z.string())),
		rentalDuration: z.nullable(z.optional(rentalDurationSchema)),
		cardPayment: z.nullable(z.optional(cardPaymentGatewaySchema)),
		returnUrl: z.nullable(z.optional(z.string())),
		mappings: z.optional(z.array(mappingSchema)),
	}),
);
