// Generated by ts-to-zod
import * as z from "zod/mini";
export const bookingCancellationBodySchema = z.object({
    reason: z.optional(z.string()),
    force: z.optional(z.boolean()),
    emailReceipt: z.optional(z.boolean()),
});
