// Generated by ts-to-zod
import * as z from "zod/mini";
import { mappingSchema } from './Mapping';
export const bookingMappingsSchema = z.object({
    mappings: z.optional(z.array(mappingSchema)),
});
