// Generated by ts-to-zod
import * as z from 'zod/mini';
import { adjustmentPerSchema } from './AdjustmentPer';
import { adjustmentDiscountSchema } from './AdjustmentDiscount';
import { type BookingAdjustment } from '../models/BookingAdjustment';
export const bookingAdjustmentSchema: z.ZodMiniType<BookingAdjustment> = z.object({
	per: adjustmentPerSchema,
	amount: z.any(),
	notes: z.nullable(z.string()),
	netDiscount: adjustmentDiscountSchema,
}) as z.ZodMiniType<BookingAdjustment>;
