// Generated by ts-to-zod
import * as z from "zod/mini";
import { unitItemIdentifierSchema } from './UnitItemIdentifier';
import { bookingContactSchema } from './BookingContact';
import { settlementMethodSchema } from './SettlementMethod';
import { resourceAllocationRequestSchema } from './ResourceAllocationRequest';
export const bookingUpdateBodySchema = z.object({
    resellerReference: z.optional(z.string()),
    productId: z.optional(z.string()),
    optionId: z.optional(z.string()),
    availabilityId: z.optional(z.string()),
    expirationMinutes: z.optional(z.number()),
    notes: z.optional(z.string()),
    emailReceipt: z.optional(z.boolean()),
    unitItems: z.optional(z.array(unitItemIdentifierSchema)),
    contact: z.optional(bookingContactSchema),
    alias: z.optional(z.string()),
    settlementMethod: z.optional(settlementMethodSchema),
    quote: z.optional(z.boolean()),
    freesale: z.optional(z.boolean()),
    redeemed: z.optional(z.boolean()),
    uuid: z.optional(z.string()),
    tags: z.optional(z.array(z.string())),
    meta: z.optional(z.record(z.string(), z.string())),
    pickupRequested: z.optional(z.boolean()),
    pickupPointId: z.optional(z.string()),
    pickupHotel: z.optional(z.string()),
    pickupHotelRoom: z.optional(z.string()),
    termsAccepted: z.optional(z.boolean()),
    offerCode: z.optional(z.string()),
    resourceAllocations: z.optional(z.array(resourceAllocationRequestSchema)),
});
