// Generated by ts-to-zod
import * as z from "zod/mini";
import { extraItemSchema } from './ExtraItem';
import { extraPricingSchema } from './ExtraPricing';
export const bookingExtrasSchema = z.object({
    extraItems: z.optional(z.array(extraItemSchema)),
    extraPricing: z.optional(z.array(extraPricingSchema)),
});
