// Generated by ts-to-zod
import * as z from 'zod/mini';
import { resourceAllocationSchema } from './ResourceAllocation';
export const bookingResourcesSchema = z.object({
	resourceAllocations: z.optional(z.array(resourceAllocationSchema)),
});
