// Generated by ts-to-zod
import * as z from 'zod/mini';
import { membershipBenefitSchema } from './MembershipBenefit';
import { membershipSchema } from './Membership';
export const bookingMembershipsSchema = z.object({
	membershipBenefit: z.nullable(z.optional(membershipBenefitSchema)),
	membership: z.nullable(z.optional(membershipSchema)),
	isMembership: z.optional(z.boolean()),
	appendMembershipValidity: z.optional(z.boolean()),
	membershipAutoRenew: z.optional(z.boolean()),
});
