// Generated by ts-to-zod
import * as z from 'zod/mini';
import { pickupPointSchema } from './PickupPoint';
export const bookingPickupsSchema = z.object({
	pickupRequested: z.optional(z.boolean()),
	pickupHotel: z.nullable(z.optional(z.string())),
	pickupRoom: z.nullable(z.optional(z.string())),
	pickupNotes: z.nullable(z.optional(z.string())),
	pickupPoint: z.nullable(z.optional(pickupPointSchema)),
	pickupPointId: z.nullable(z.optional(z.string())),
	pickupHotelRoom: z.nullable(z.optional(z.string())),
	pickupDispatch: z.nullable(z.optional(z.string())),
	dropoffDispatch: z.nullable(z.optional(z.string())),
});
