// Generated by ts-to-zod
import * as z from "zod/mini";
export const bookingPickupBodySchema = z.object({
    pickupRequested: z.optional(z.boolean()),
    pickupPointId: z.optional(z.string()),
    pickupHotel: z.optional(z.string()),
    pickupHotelRoom: z.optional(z.string()),
});
