// Generated by ts-to-zod
import * as z from 'zod/mini';
import { unitItemIdentifierSchema } from './UnitItemIdentifier';
import { bookingContactSchema } from './BookingContact';
export const bookingConfirmationBodySchema = z.object({
	emailReceipt: z.optional(z.boolean()),
	resellerReference: z.optional(z.string()),
	unitItems: z.optional(z.array(unitItemIdentifierSchema)),
	contact: bookingContactSchema,
	notes: z.optional(z.string()),
	metadata: z.optional(z.record(z.string(), z.string())),
	pickupRequested: z.optional(z.boolean()),
	pickupPointId: z.optional(z.string()),
	pickupHotel: z.optional(z.string()),
	pickupHotelRoom: z.optional(z.string()),
});
