// Generated by ts-to-zod
import * as z from 'zod/mini';
export const brandVentrataCheckoutContentSchema = z.object({
	headerBackgroundColor: z.optional(z.string()),
	footerBackgroundColor: z.optional(z.string()),
});
