// Generated by ts-to-zod
import * as z from "zod/mini";
import { brandContactSchema } from './BrandContact';
import { fontSchema } from './Font';
export const brandSchema = z.object({
    id: z.nullable(z.string()),
    name: z.nullable(z.string()),
    contact: brandContactSchema,
    color: z.nullable(z.string()),
    secondaryColor: z.nullable(z.string()),
    backgroundColor: z.nullable(z.string()),
    accentFont: z.nullable(fontSchema),
    bodyFont: z.nullable(fontSchema),
    headerFont: z.nullable(fontSchema),
    checkoutLogoUrl: z.nullable(z.string()),
    logoUrl: z.nullable(z.string()),
    logoWhiteUrl: z.nullable(z.string()),
    faviconUrl: z.nullable(z.string()),
    headerBackgroundColor: z.optional(z.string()),
    footerBackgroundColor: z.optional(z.string()),
});
