// Generated by ts-to-zod
import * as z from 'zod/mini';
export const brandContactSchema = z.object({
	name: z.nullable(z.string()),
	email: z.nullable(z.string()),
	telephone: z.nullable(z.string()),
	address: z.nullable(z.string()),
	website: z.nullable(z.string()),
});
