// Generated by ts-to-zod
import * as z from 'zod/mini';
import { refundSchema } from './Refund';
export const cancellationSchema = z.object({
	refund: refundSchema,
	reason: z.nullable(z.string()),
	notes: z.nullable(z.string()),
	utcCancelledAt: z.string(),
});
