// Generated by ts-to-zod
import * as z from "zod/mini";
import { capabilityIdSchema } from './CapabilityId';
import { octo_CapabilityIdSchema } from './Octo_CapabilityId';
export const capabilitySchema = z.object({
    id: capabilityIdSchema,
    revision: z.number(),
    required: z.boolean(),
    dependencies: z.array(octo_CapabilityIdSchema),
    docs: z.nullable(z.string()),
});
