// Generated by ts-to-zod
import * as z from "zod/mini";
import { externalGatewayRequestSchema } from './ExternalGatewayRequest';
import { paypalGatewayRequestSchema } from './PaypalGatewayRequest';
export const cardPaymentSchema = z.object({
    amount: z.nullable(z.number()),
    cancel: z.nullable(z.optional(z.boolean())),
    cardId: z.nullable(z.string()),
    currency: z.nullable(z.string()),
    external: z.nullable(externalGatewayRequestSchema),
    gateway: z.nullable(z.string()),
    notes: z.nullable(z.optional(z.string())),
    paypal: z.nullable(paypalGatewayRequestSchema),
});
