// Generated by ts-to-zod
import * as z from "zod/mini";
import { cardSchema } from './Card';
import { adyenGatewaySchema } from './AdyenGateway';
import { vivawalletGatewaySchema } from './VivawalletGateway';
import { stripeGatewaySchema } from './StripeGateway';
import { bridgepayGatewaySchema } from './BridgepayGateway';
import { realaxGatewaySchema } from './RealaxGateway';
import { paypalGatewaySchema } from './PaypalGateway';
import { externalGatewaySchema } from './ExternalGateway';
import { paytrGatewaySchema } from './PaytrGateway';
import { spreedlyGatewaySchema } from './SpreedlyGateway';
import { peachGatewaySchema } from './PeachGateway';
export const cardPaymentGatewaySchema = z.object({
    id: z.string(),
    gateway: z.string(),
    source: z.string(),
    paid: z.number(),
    totalPaid: z.number(),
    paidSurcharge: z.number(),
    balance: z.number(),
    surcharge: z.number(),
    totalRefunded: z.number(),
    outstandingBalance: z.number(),
    currency: z.string(),
    currencyPrecision: z.number(),
    reusableCards: z.array(cardSchema),
    adyen: z.optional(adyenGatewaySchema),
    vivawallet: z.optional(vivawalletGatewaySchema),
    stripe: z.optional(stripeGatewaySchema),
    bridgepay: z.optional(bridgepayGatewaySchema),
    realax: z.optional(realaxGatewaySchema),
    paypal: z.optional(paypalGatewaySchema),
    external: z.optional(externalGatewaySchema),
    paytr: z.optional(paytrGatewaySchema),
    spreedly: z.optional(spreedlyGatewaySchema),
    peach: z.optional(peachGatewaySchema),
});
