// Generated by ts-to-zod
import * as z from "zod/mini";
import { availableLanguagesItemSchema } from './AvailableLanguagesItem';
export const categorySchema = z.object({
    id: z.string(),
    default: z.boolean(),
    name: z.nullable(z.string()),
    title: z.nullable(z.string()),
    tags: z.array(z.string()),
    shortDescription: z.nullable(z.string()),
    coverImageUrl: z.nullable(z.string()),
    bannerImageUrl: z.nullable(z.string()),
    productIds: z.optional(z.array(z.string())),
    href: z.nullable(z.optional(z.string())),
    availableLanguages: z.nullable(z.optional(availableLanguagesItemSchema)),
    meta: z.optional(z.record(z.string(), z.string())),
});
