// Generated by ts-to-zod
import * as z from 'zod/mini';
import { availableLanguagesSchema } from './AvailableLanguages';
export const categoryVentrataCheckoutContentSchema = z.object({
	href: z.nullable(z.optional(z.string())),
	availableLanguages: z.nullable(z.optional(availableLanguagesSchema)),
	meta: z.optional(z.record(z.string(), z.string())),
});
