// Generated by ts-to-zod
import * as z from 'zod/mini';
import { CheckoutSitemapEntryRel } from '../models/CheckoutSitemapEntryRel';
export const checkoutSitemapEntryRelSchema = z.enum(CheckoutSitemapEntryRel);
