// Generated by ts-to-zod
import * as z from "zod/mini";
import { bookingSchema } from './Booking';
export const checkinLookupSchema = z.object({
    message: z.nullable(z.string()),
    verified: z.boolean(),
    bookings: z.array(bookingSchema),
});
