// Generated by ts-to-zod
import * as z from 'zod/mini';
import { checkoutSitemapEntryRelSchema } from './CheckoutSitemapEntryRel';
export const checkoutSitemapEntrySchema = z.object({
	id: z.nullable(z.string()),
	description: z.nullable(z.string()),
	destinationId: z.optional(z.string()),
	keywords: z.array(z.string()),
	language: z.string(),
	name: z.nullable(z.string()),
	rel: checkoutSitemapEntryRelSchema,
	title: z.nullable(z.string()),
});
