// Generated by ts-to-zod
import * as z from 'zod/mini';
import { giftExpiryUnitSchema } from './GiftExpiryUnit';
import { giftsRestrictionsSchema } from './GiftsRestrictions';
import { checkoutConfigPricingDisplaySchema } from './CheckoutConfigPricingDisplay';
import { resellerSchema } from './Reseller';
import { envSchema } from './Env';
import { destinationSchema } from './Destination';
import { checkoutDomainSchema } from './CheckoutDomain';
import { checkoutSitemapEntrySchema } from './CheckoutSitemapEntry';
import { destinationContactSchema } from './DestinationContact';
import { brandSchema } from './Brand';
import { categorySchema } from './Category';
import { noticeSchema } from './Notice';
import { availableLanguagesSchema } from './AvailableLanguages';
import { pageSchema } from './Page';
import { articleSchema } from './Article';
import { navSchema } from './Nav';
import { claimSchema } from './Claim';
export const checkoutConfigSchema = z.object({
	allowedCheckinMethods: z.array(z.string()),
	conversionHtml: z.nullable(z.string()),
	defaultMarketingAllowed: z.boolean(),
	giftsAllowed: z.boolean(),
	giftsDuration: z.string(),
	giftsDurationAmount: z.number(),
	giftsDurationUnit: giftExpiryUnitSchema,
	giftsRestrictions: giftsRestrictionsSchema,
	googleAnalyticsMeasurementId: z.nullable(z.string()),
	googleMapsApiKey: z.string(),
	googleUniversalAnalyticsId: z.nullable(z.string()),
	includeTax: z.boolean(),
	loqateApiKey: z.nullable(z.string()),
	memberSignupUrl: z.nullable(z.string()),
	membersAllowed: z.boolean(),
	noindex: z.boolean(),
	pricingDisplay: checkoutConfigPricingDisplaySchema,
	quotesAllowed: z.boolean(),
	recaptchaEnterpriseSiteKey: z.nullable(z.string()),
	segmentKey: z.nullable(z.string()),
	theme: z.string(),
	waitlistsAllowed: z.boolean(),
	widgetCss: z.nullable(z.string()),
	marketingConsent: z.nullable(z.string()),
	reseller: z.nullable(resellerSchema),
	env: envSchema,
	bodyHtml: z.nullable(z.string()),
	destinations: z.optional(z.array(destinationSchema)),
	domains: z.optional(z.array(checkoutDomainSchema)),
	footerHtml: z.nullable(z.string()),
	headHtml: z.nullable(z.string()),
	legacyWidgetToken: z.nullable(z.optional(z.string())),
	redirects: z.optional(z.record(z.string(), z.string())),
	showFooter: z.optional(z.boolean()),
	showHeader: z.optional(z.boolean()),
	sitemap: z.optional(z.record(z.string(), checkoutSitemapEntrySchema)),
	id: z.string(),
	default: z.boolean(),
	name: z.nullable(z.string()),
	title: z.nullable(z.string()),
	shortDescription: z.nullable(z.string()),
	featured: z.boolean(),
	country: z.nullable(z.string()),
	contact: destinationContactSchema,
	brand: brandSchema,
	latitude: z.nullable(z.number()),
	longitude: z.nullable(z.number()),
	googlePlaceId: z.nullable(z.string()),
	bannerImageUrl: z.nullable(z.string()),
	coverImageUrl: z.nullable(z.string()),
	videoUrl: z.nullable(z.string()),
	facebookUrl: z.nullable(z.string()),
	googleUrl: z.nullable(z.string()),
	tripadvisorUrl: z.nullable(z.string()),
	twitterUrl: z.nullable(z.string()),
	youtubeUrl: z.nullable(z.string()),
	instagramUrl: z.nullable(z.string()),
	categories: z.optional(z.array(categorySchema)),
	tags: z.array(z.string()),
	address: z.nullable(z.string()),
	notices: z.array(noticeSchema),
	defaultCurrency: z.optional(z.string()),
	availableCurrencies: z.optional(z.array(z.string())),
	href: z.nullable(z.optional(z.string())),
	availableLanguages: z.nullable(z.optional(availableLanguagesSchema)),
	meta: z.optional(z.record(z.string(), z.string())),
	pages: z.optional(z.array(pageSchema)),
	articles: z.optional(z.array(articleSchema)),
	navs: z.optional(z.array(navSchema)),
	claims: z.optional(z.array(claimSchema)),
	featuredCategories: z.optional(z.array(categorySchema)),
});
