// Generated by ts-to-zod
import * as z from 'zod/mini';
export const checkinLookupBodySchema = z.object({
	page: z.optional(z.number()),
	email: z.optional(z.string()),
	mobile: z.optional(z.string()),
	country: z.optional(z.string()),
	reference: z.optional(z.string()),
	verification: z.optional(z.string()),
});
