// Generated by ts-to-zod
import * as z from 'zod/mini';
export const claimSchema = z.object({
	id: z.string(),
	href: z.nullable(z.string()),
	icon: z.nullable(z.string()),
	shortDescription: z.nullable(z.string()),
	title: z.nullable(z.string()),
});
