// Generated by ts-to-zod
import * as z from 'zod/mini';
import { bookingContactSchema } from './BookingContact';
export const confirmOrderBodySchema = z.object({
	expirationMinutes: z.optional(z.number()),
	emailReceipt: z.optional(z.boolean()),
	contact: z.optional(bookingContactSchema),
	currency: z.optional(z.string()),
});
