// Generated by ts-to-zod
import * as z from "zod/mini";
import { cardPaymentSchema } from './CardPayment';
export const createOrderCardPaymentsBodySchema = z.object({
    cardPayment: z.optional(cardPaymentSchema),
    returnUrl: z.nullable(z.optional(z.string())),
    gatewayId: z.optional(z.string()),
});
