// Generated by ts-to-zod
import * as z from "zod/mini";
import { createGiftBodySchema } from './CreateGiftBody';
export const createOrderGiftsBodySchema = z.object({
    gifts: z.optional(z.array(createGiftBodySchema)),
});
