// Generated by ts-to-zod
import * as z from 'zod/mini';
import { webhookEventSchema } from './WebhookEvent';
import { capabilityIdSchema } from './CapabilityId';
export const createWebhookBodySchema = z.object({
	url: z.string(),
	function: z.nullable(z.optional(z.string())),
	event: webhookEventSchema,
	useContactLanguage: z.optional(z.boolean()),
	headers: z.optional(z.record(z.string(), z.string())),
	capabilities: z.optional(z.array(capabilityIdSchema)),
});
