// Generated by ts-to-zod
import * as z from "zod/mini";
import { bookingReservationBodySchema } from './BookingReservationBody';
import { bookingContactSchema } from './BookingContact';
import { settlementMethodSchema } from './SettlementMethod';
import { cardPaymentSchema } from './CardPayment';
import { createGiftBodySchema } from './CreateGiftBody';
export const createOrderBodySchema = z.object({
    bookings: z.optional(z.array(bookingReservationBodySchema)),
    contact: z.optional(bookingContactSchema),
    emailReceipt: z.optional(z.boolean()),
    expirationMinutes: z.optional(z.number()),
    quote: z.optional(z.boolean()),
    settlementMethod: z.optional(settlementMethodSchema),
    notes: z.nullable(z.optional(z.string())),
    currency: z.optional(z.string()),
    cardPayment: z.optional(cardPaymentSchema),
    returnUrl: z.nullable(z.optional(z.string())),
    gatewayId: z.optional(z.string()),
    gifts: z.optional(z.array(createGiftBodySchema)),
    identityId: z.optional(z.string()),
});
