// Generated by ts-to-zod
import * as z from "zod/mini";
import { defaultableIDSchema } from './DefaultableID';
import { bookingContactSchema } from './BookingContact';
import { waitlistUnitItemIdentifierSchema } from './WaitlistUnitItemIdentifier';
export const createWaitlistRequestSchema = z.object({
    productId: z.string(),
    optionId: defaultableIDSchema,
    returnUrl: z.optional(z.string()),
    localDate: z.string(),
    contact: bookingContactSchema,
    units: z.array(waitlistUnitItemIdentifierSchema),
});
