// Generated by ts-to-zod
import * as z from "zod/mini";
import { customerContactSchema } from './CustomerContact';
import { giftPaymentSchema } from './GiftPayment';
import { settlementMethodSchema } from './SettlementMethod';
export const createGiftBodySchema = z.object({
    alias: z.optional(z.string()),
    amount: z.number(),
    contact: z.optional(customerContactSchema),
    currency: z.optional(z.string()),
    emailReceipt: z.boolean(),
    expirationMinutes: z.optional(z.number()),
    giftPayment: z.optional(giftPaymentSchema),
    identityId: z.optional(z.string()),
    message: z.optional(z.string()),
    notes: z.optional(z.string()),
    offerCode: z.optional(z.string()),
    resellerReference: z.optional(z.string()),
    settlementMethod: z.optional(settlementMethodSchema),
});
