// Generated by ts-to-zod
import * as z from 'zod/mini';
import { availableLanguagesSchema } from './AvailableLanguages';
import { pageSchema } from './Page';
import { articleSchema } from './Article';
import { navSchema } from './Nav';
import { claimSchema } from './Claim';
import { categorySchema } from './Category';
export const destinationVentrataCheckoutContentSchema = z.object({
	href: z.nullable(z.optional(z.string())),
	availableLanguages: z.nullable(z.optional(availableLanguagesSchema)),
	meta: z.optional(z.record(z.string(), z.string())),
	pages: z.optional(z.array(pageSchema)),
	articles: z.optional(z.array(articleSchema)),
	navs: z.optional(z.array(navSchema)),
	claims: z.optional(z.array(claimSchema)),
	featuredCategories: z.optional(z.array(categorySchema)),
});
