// Generated by ts-to-zod
import * as z from "zod/mini";
export const destinationPricingSchema = z.object({
    defaultCurrency: z.optional(z.string()),
    availableCurrencies: z.optional(z.array(z.string())),
});
