// Generated by ts-to-zod
import * as z from 'zod/mini';
import { destinationContactSchema } from './DestinationContact';
import { brandSchema } from './Brand';
import { categorySchema } from './Category';
import { noticeSchema } from './Notice';
import { availableLanguagesItemSchema } from './AvailableLanguagesItem';
import { pageSchema } from './Page';
import { articleSchema } from './Article';
import { navSchema } from './Nav';
import { claimSchema } from './Claim';
export const destinationSchema = z.object({
	id: z.string(),
	default: z.boolean(),
	name: z.nullable(z.string()),
	title: z.nullable(z.string()),
	shortDescription: z.nullable(z.string()),
	featured: z.boolean(),
	country: z.nullable(z.string()),
	contact: destinationContactSchema,
	brand: brandSchema,
	latitude: z.nullable(z.number()),
	longitude: z.nullable(z.number()),
	googlePlaceId: z.nullable(z.string()),
	bannerImageUrl: z.nullable(z.string()),
	coverImageUrl: z.nullable(z.string()),
	videoUrl: z.nullable(z.string()),
	facebookUrl: z.nullable(z.string()),
	googleUrl: z.nullable(z.string()),
	tripadvisorUrl: z.nullable(z.string()),
	twitterUrl: z.nullable(z.string()),
	youtubeUrl: z.nullable(z.string()),
	instagramUrl: z.nullable(z.string()),
	categories: z.optional(z.array(categorySchema)),
	tags: z.array(z.string()),
	address: z.nullable(z.string()),
	notices: z.array(noticeSchema),
	defaultCurrency: z.optional(z.string()),
	availableCurrencies: z.optional(z.array(z.string())),
	href: z.nullable(z.optional(z.string())),
	availableLanguages: z.nullable(z.optional(availableLanguagesItemSchema)),
	meta: z.optional(z.record(z.string(), z.string())),
	pages: z.optional(z.array(pageSchema)),
	articles: z.optional(z.array(articleSchema)),
	navs: z.optional(z.array(navSchema)),
	claims: z.optional(z.array(claimSchema)),
	featuredCategories: z.optional(z.array(categorySchema)),
});
