// Generated by ts-to-zod
import * as z from 'zod/mini';
export const dropoffPointSchema = z.object({
	id: z.string(),
	name: z.nullable(z.string()),
	directions: z.nullable(z.string()),
	address: z.nullable(z.string()),
	latitude: z.nullable(z.number()),
	longitude: z.nullable(z.number()),
	localDateTime: z.nullable(z.string()),
	localDateTimeTo: z.nullable(z.string()),
	googlePlaceId: z.nullable(z.string()),
	street: z.nullable(z.string()),
	postalCode: z.nullable(z.string()),
	locality: z.nullable(z.string()),
	region: z.nullable(z.string()),
	state: z.nullable(z.string()),
	country: z.nullable(z.string()),
});
