// Generated by ts-to-zod
import * as z from "zod/mini";
import { taxSchema } from './Tax';
export const extraPricingSchema = z.object({
    extraId: z.string(),
    original: z.number(),
    retail: z.number(),
    net: z.nullable(z.number()),
    currency: z.string(),
    currencyPrecision: z.number(),
    includedTaxes: z.array(taxSchema),
});
