// Generated by ts-to-zod
import * as z from "zod/mini";
import { extraRestrictionsSchema } from './ExtraRestrictions';
import { customRetailOptionSchema } from './CustomRetailOption';
import { pricingSchema } from './Pricing';
export const extraSchema = z.object({
    id: z.string(),
    internalName: z.string(),
    reference: z.nullable(z.string()),
    restrictions: extraRestrictionsSchema,
    tags: z.array(z.string()),
    customRetail: z.boolean(),
    customRetailOptions: z.array(customRetailOptionSchema),
    pricingFrom: z.optional(z.array(pricingSchema)),
    pricing: z.optional(z.array(pricingSchema)),
    title: z.nullable(z.optional(z.string())),
});
