// Generated by ts-to-zod
import * as z from 'zod/mini';
import { extraSchema } from './Extra';
import { pricingSchema } from './Pricing';
export const extraItemSchema = z.object({
	id: z.string(),
	extraId: z.string(),
	extra: extraSchema,
	pricing: pricingSchema,
});
