// Generated by ts-to-zod
import * as z from 'zod/mini';
import { unitTypeSchema } from './UnitType';
export const extraRestrictionsSchema = z.object({
	default: z.boolean(),
	required: z.boolean(),
	minAge: z.number(),
	maxAge: z.number(),
	idRequired: z.boolean(),
	minQuantity: z.nullable(z.number()),
	maxQuantity: z.nullable(z.number()),
	minCustomRetail: z.number(),
	maxCustomRetail: z.nullable(z.number()),
	paxCount: z.number(),
	accompaniedBy: z.array(unitTypeSchema),
	accompaniedByRatio: z.nullable(z.number()),
	accompaniedByRatioDenominator: z.number(),
	notAccompaniedBy: z.array(unitTypeSchema),
});
