// Generated by ts-to-zod
import * as z from 'zod/mini';
import { type FareGroup } from '../models/FareGroup';
export const fareGroupSchema: z.ZodMiniType<FareGroup> = z.object({
	id: z.string(),
	internalName: z.string(),
	title: z.string(),
	shortDescription: z.any(),
}) as z.ZodMiniType<FareGroup>;
