// Generated by ts-to-zod
import * as z from 'zod/mini';
import { fareGroupSchema } from './FareGroup';
import { type Fare } from '../models/Fare';
export const fareSchema: z.ZodMiniType<Fare> = z.object({
	id: z.string(),
	internalName: z.string(),
	title: z.string(),
	shortDescription: z.any(),
	fareGroup: z.nullable(fareGroupSchema),
}) as z.ZodMiniType<Fare>;
