// Generated by ts-to-zod
import * as z from 'zod/mini';
export const fontSchema = z.object({
	id: z.string(),
	name: z.nullable(z.string()),
	normalTtfUrl: z.nullable(z.string()),
	italicTtfUrl: z.nullable(z.string()),
	boldTtfUrl: z.nullable(z.string()),
	boldItalicTtfUrl: z.nullable(z.string()),
});
