// Generated by ts-to-zod
import * as z from 'zod/mini';
export const getBookingsQueryParamsSchema = z.object({
	resellerReference: z.optional(z.string()),
	supplierReference: z.optional(z.string()),
	localDate: z.optional(z.string()),
	localDateStart: z.optional(z.string()),
	localDateEnd: z.optional(z.string()),
	productId: z.optional(z.string()),
	optionId: z.optional(z.string()),
});
