// Generated by ts-to-zod
import * as z from "zod/mini";
import { resellerStatusSchema } from './ResellerStatus';
export const getMappingsRequestSchema = z.object({
    productId: z.optional(z.string()),
    optionId: z.optional(z.string()),
    resellerReference: z.optional(z.string()),
    resellerStatus: z.optional(resellerStatusSchema),
});
