// Generated by ts-to-zod
import * as z from "zod/mini";
import { octo_GetProductsRequestSchema } from './Octo_GetProductsRequest';
export const getProductsRequestSchema = z.intersection(octo_GetProductsRequestSchema, z.object({
    categoryId: z.optional(z.string()),
    destinationId: z.optional(z.string()),
    featured: z.optional(z.boolean()),
    productIds: z.optional(z.array(z.string())),
}));
