// Generated by ts-to-zod
import * as z from "zod/mini";
import { connectionSchema } from './Connection';
export const getYourGuideConnectionSchema = z.intersection(connectionSchema, z.object({
    gygConnectId: z.string(),
    gygLoginEmail: z.string(),
    gygLoginPassword: z.string(),
    gygLoginOTPSecret: z.optional(z.string()),
    gygSupplierId: z.optional(z.string()),
    gygSupplierName: z.optional(z.string()),
    gygActivated: z.boolean(),
}));
