// Generated by ts-to-zod
import * as z from 'zod/mini';
export const getYourGuideActivateBodySchema = z.object({
	gygLoginOTPSecret: z.string(),
	gygSupplierId: z.string(),
	gygSupplierName: z.string(),
});
