// Generated by ts-to-zod
import * as z from 'zod/mini';
import { agentSchema } from './Agent';
import { cancellationSchema } from './Cancellation';
import { customerContactSchema } from './CustomerContact';
import { deliveryMethodSchema } from './DeliveryMethod';
import { giftPaymentSchema } from './GiftPayment';
import { pricingSchema } from './Pricing';
import { contactFieldSchema } from './ContactField';
import { resellerSchema } from './Reseller';
import { sellerSchema } from './Seller';
import { settlementMethodSchema } from './SettlementMethod';
import { bookingStatusSchema } from './BookingStatus';
import { userSchema } from './User';
import { giftVoucherSchema } from './GiftVoucher';
import { identitySchema } from './Identity';
import { cardPaymentGatewaySchema } from './CardPaymentGateway';
import { offerComparisonSchema } from './OfferComparison';
import { offerSchema } from './Offer';
export const giftSchema = z.object({
	agent: z.nullable(agentSchema),
	alias: z.nullable(z.string()),
	active: z.boolean(),
	amount: z.number(),
	cancellable: z.boolean(),
	updatable: z.boolean(),
	cancellation: z.nullable(cancellationSchema),
	confirmable: z.boolean(),
	contact: z.nullable(customerContactSchema),
	currency: z.string(),
	deliveryMethods: z.array(deliveryMethodSchema),
	giftPayment: z.nullable(giftPaymentSchema),
	id: z.string(),
	message: z.nullable(z.string()),
	notes: z.nullable(z.string()),
	pricing: z.optional(pricingSchema),
	recipient: z.nullable(customerContactSchema),
	requiredContactFields: z.array(contactFieldSchema),
	reseller: z.nullable(resellerSchema),
	resellerReference: z.nullable(z.string()),
	seller: z.nullable(sellerSchema),
	settlementMethod: settlementMethodSchema,
	settlementMethods: z.array(settlementMethodSchema),
	status: bookingStatusSchema,
	internalStatus: z.string(),
	supplierReference: z.string(),
	testMode: z.nullable(z.boolean()),
	user: z.nullable(userSchema),
	utcCreatedAt: z.string(),
	utcUpdatedAt: z.string(),
	utcExpiresAt: z.nullable(z.string()),
	utcRedeemedAt: z.nullable(z.string()),
	utcConfirmedAt: z.nullable(z.string()),
	uuid: z.string(),
	visibleContactFields: z.array(contactFieldSchema),
	voucher: giftVoucherSchema,
	identity: z.optional(identitySchema),
	identityId: z.optional(z.string()),
	cardPayment: z.nullable(z.optional(cardPaymentGatewaySchema)),
	returnUrl: z.nullable(z.optional(z.string())),
	primary: z.optional(z.boolean()),
	orderId: z.optional(z.string()),
	orderReference: z.optional(z.string()),
	offerCode: z.nullable(z.optional(z.string())),
	offerTitle: z.nullable(z.optional(z.string())),
	offerComparisons: z.optional(z.array(offerComparisonSchema)),
	offerIsCombination: z.optional(z.boolean()),
	offers: z.optional(z.array(offerSchema)),
	offer: z.nullable(z.optional(offerSchema)),
});
