// Generated by ts-to-zod
import * as z from 'zod/mini';
export const giftsRestrictionItemSchema = z.object({
	amount: z.nullable(z.number()),
	currency: z.string(),
	currencyPrecision: z.number(),
});
