// Generated by ts-to-zod
import * as z from 'zod/mini';
import { redemptionMethodSchema } from './RedemptionMethod';
import { deliveryOptionSchema } from './DeliveryOption';
export const giftVoucherSchema = z.object({
	redemptionMethod: redemptionMethodSchema,
	utcRedeemedAt: z.nullable(z.string()),
	deliveryOptions: z.array(deliveryOptionSchema),
});
