// Generated by ts-to-zod
import * as z from 'zod/mini';
import { giftsRestrictionItemSchema } from './GiftsRestrictionItem';
export const giftsRestrictionsSchema = z.object({
	maxAmounts: z.array(giftsRestrictionItemSchema),
	minAmounts: z.array(giftsRestrictionItemSchema),
});
