// Generated by ts-to-zod
import * as z from "zod/mini";
import { offerComparisonSchema } from './OfferComparison';
import { offerSchema } from './Offer';
export const giftOffersSchema = z.object({
    offerCode: z.nullable(z.optional(z.string())),
    offerTitle: z.nullable(z.optional(z.string())),
    offerComparisons: z.optional(z.array(offerComparisonSchema)),
    offerIsCombination: z.optional(z.boolean()),
    offers: z.optional(z.array(offerSchema)),
    offer: z.nullable(z.optional(offerSchema)),
});
