// Generated by ts-to-zod
import * as z from "zod/mini";
import { identitySchema } from './Identity';
export const giftIdentitiesSchema = z.object({
    identity: z.optional(identitySchema),
    identityId: z.optional(z.string()),
});
