// Generated by ts-to-zod
import * as z from 'zod/mini';
import { googleOperatorSchema } from './GoogleOperator';
import { googleRatingSchema } from './GoogleRating';
import { googleUrlSchema } from './GoogleUrl';
import { googleOptionCategorySchema } from './GoogleOptionCategory';
import { googleRelatedLocationSchema } from './GoogleRelatedLocation';
import { googleLocalizedNameSchema } from './GoogleLocalizedName';
export const googleOptionsSchema = z.object({
	operator: z.nullable(googleOperatorSchema),
	rating: z.nullable(googleRatingSchema),
	landing_page: googleUrlSchema,
	inventory_types: z.array(z.string()),
	landing_page_list_view: z.nullable(googleUrlSchema),
	option_categories: z.array(googleOptionCategorySchema),
	related_locations: z.array(googleRelatedLocationSchema),
	brand_name: googleLocalizedNameSchema,
});
