// Generated by ts-to-zod
import * as z from "zod/mini";
import { googleNullableLocalizedTextSchema } from './GoogleNullableLocalizedText';
export const googleNullableLocalizedNameSchema = z.object({
    localized_texts: z.array(googleNullableLocalizedTextSchema),
});
