// Generated by ts-to-zod
import * as z from "zod/mini";
import { googleLocalizedTextSchema } from './GoogleLocalizedText';
export const googleLocalizedNameSchema = z.object({
    localized_texts: z.array(googleLocalizedTextSchema),
});
