// Generated by ts-to-zod
import * as z from "zod/mini";
export const googleRelatedLocationSchema = z.object({
    location: z.object({
        location: z.object({
            place_id: z.string(),
        }),
    }),
    relation_type: z.string(),
});
