// Generated by ts-to-zod
import * as z from "zod/mini";
import { productSchema } from './Product';
import { defaultableIDSchema } from './DefaultableID';
import { optionSchema } from './Option';
import { type Include } from '../models/Include';
export const includeSchema: z.ZodMiniType<Include> = z.lazy(() => z.object({
    id: z.string(),
    required: z.boolean(),
    limit: z.number(),
    validityDays: z.nullable(z.number()),
    availabilityRequired: z.boolean(),
    productId: z.string(),
    product: z.nullable(productSchema),
    optionId: defaultableIDSchema,
    option: z.nullable(optionSchema),
}));
