// Generated by ts-to-zod
import * as z from "zod/mini";
import { itineraryItemTypeSchema } from './ItineraryItemType';
import { durationUnitSchema } from './DurationUnit';
export const itineraryItemSchema = z.object({
    name: z.string(),
    type: itineraryItemTypeSchema,
    description: z.nullable(z.string()),
    address: z.nullable(z.string()),
    googlePlaceId: z.nullable(z.string()),
    latitude: z.nullable(z.number()),
    longitude: z.nullable(z.number()),
    travelTime: z.nullable(z.string()),
    travelTimeAmount: z.nullable(z.number()),
    travelTimeUnit: z.nullable(durationUnitSchema),
    duration: z.nullable(z.string()),
    durationAmount: z.number(),
    durationUnit: durationUnitSchema,
});
