// Generated by ts-to-zod
import * as z from "zod/mini";
export const linkSchema = z.object({
    id: z.string(),
    href: z.nullable(z.string()),
    shortDescription: z.nullable(z.string()),
    title: z.nullable(z.string()),
});
