// Generated by ts-to-zod
import * as z from 'zod/mini';
export const listGiftsQueryParamsSchema = z.object({
	resellerReference: z.optional(z.string()),
	supplierReference: z.optional(z.string()),
	utcCreatedAtStart: z.optional(z.string()),
	utcCreatedAtEnd: z.optional(z.string()),
	utcUpdatedAtStart: z.optional(z.string()),
	utcUpdatedAtEnd: z.optional(z.string()),
	contactEmailAddress: z.optional(z.string()),
});
