// Generated by ts-to-zod
import * as z from 'zod/mini';
export const listOrdersQueryParamsSchema = z.object({
	contactEmailAddress: z.optional(z.string()),
	contactLastName: z.optional(z.string()),
	contactPhoneNumber: z.optional(z.string()),
	supplierReference: z.optional(z.string()),
	utcCreatedAtEnd: z.optional(z.string()),
	utcCreatedAtStart: z.optional(z.string()),
	utcUpdatedAtEnd: z.optional(z.string()),
	utcUpdatedAtStart: z.optional(z.string()),
});
