// Generated by ts-to-zod
import * as z from 'zod/mini';
import { resellerStatusSchema } from './ResellerStatus';
export const mappingSchema = z.object({
	resellerReference: z.string(),
	resellerStatus: resellerStatusSchema,
	title: z.string(),
	url: z.string(),
	webhookUrl: z.nullable(z.string()),
	optionRequired: z.boolean(),
	unitRequired: z.boolean(),
	productId: z.nullable(z.string()),
	optionId: z.nullable(z.string()),
	unitId: z.nullable(z.string()),
	connected: z.boolean(),
});
