// Generated by ts-to-zod
import * as z from "zod/mini";
import { resellerStatusSchema } from './ResellerStatus';
export const mappingToUpdateSchema = z.object({
    resellerReference: z.string(),
    resellerStatus: resellerStatusSchema,
    title: z.string(),
    url: z.string(),
    webhookUrl: z.nullable(z.string()),
    optionRequired: z.boolean(),
    unitRequired: z.boolean(),
});
