// Generated by ts-to-zod
import * as z from "zod/mini";
import { customerContactSchema } from './CustomerContact';
export const membershipSchema = z.object({
    id: z.string(),
    title: z.string(),
    contact: customerContactSchema,
    reference: z.string(),
    resellerReference: z.nullable(z.string()),
    supplierReference: z.string(),
    availabilityLocalDateStart: z.nullable(z.string()),
    availabilityLocalDateEnd: z.nullable(z.string()),
});
