// Generated by ts-to-zod
import * as z from "zod/mini";
import { membershipSchema } from './Membership';
export const membershipLookupSchema = z.object({
    memberships: z.array(membershipSchema),
    message: z.nullable(z.string()),
    verified: z.boolean(),
});
