// Generated by ts-to-zod
import * as z from "zod/mini";
export const membershipLookupBodySchema = z.object({
    country: z.nullable(z.optional(z.string())),
    email: z.nullable(z.optional(z.string())),
    mobile: z.nullable(z.optional(z.string())),
    reference: z.nullable(z.optional(z.string())),
    verification: z.nullable(z.optional(z.string())),
});
