// Generated by ts-to-zod
import * as z from 'zod/mini';
export const navSchema = z.object({
	id: z.string(),
	title: z.nullable(z.string()),
	parentTitle: z.nullable(z.string()),
	inFooter: z.nullable(z.boolean()),
	inHeader: z.nullable(z.boolean()),
	href: z.nullable(z.string()),
});
