// Generated by ts-to-zod
import * as z from 'zod/mini';
export const noticeSchema = z.object({
	id: z.string(),
	title: z.nullable(z.string()),
	shortDescription: z.string(),
	coverImageUrl: z.nullable(z.string()),
});
