// Generated by ts-to-zod
import * as z from 'zod/mini';
import { octo_BaseErrorSchema } from './Octo_BaseError';
export const octo_ErrorInvalidUnitIDSchema = z.intersection(
	octo_BaseErrorSchema,
	z.object({
		unitId: z.string(),
	}),
);
