// Generated by ts-to-zod
import * as z from 'zod/mini';
import { pricingSchema } from './Pricing';
import { productSchema } from './Product';
import { unitSchema } from './Unit';
export const offerComparisonSchema = z.object({
	productId: z.string(),
	optionId: z.string(),
	pricing: pricingSchema,
	product: productSchema,
	shortDescription: z.optional(z.string()),
	units: z.array(unitSchema),
});
