// Generated by ts-to-zod
import * as z from "zod/mini";
export const offerRestrictionsSchema = z.object({
    minUnits: z.nullable(z.number()),
    maxUnits: z.nullable(z.number()),
    minTotal: z.nullable(z.number()),
    maxTotal: z.nullable(z.number()),
    unitIds: z.array(z.string()),
});
