// Generated by ts-to-zod
import * as z from "zod/mini";
import { membershipBenefitSchema } from './MembershipBenefit';
export const offerMembershipsSchema = z.object({
    membershipBenefit: z.nullable(z.optional(membershipBenefitSchema)),
});
