// Generated by ts-to-zod
import * as z from "zod/mini";
import { netDiscountSchema } from './NetDiscount';
import { offerRestrictionsSchema } from './OfferRestrictions';
import { membershipBenefitSchema } from './MembershipBenefit';
export const offerSchema = z.object({
    id: z.string(),
    title: z.string(),
    label: z.string(),
    code: z.string(),
    description: z.nullable(z.string()),
    availabilityLocalDateStart: z.nullable(z.string()),
    availabilityLocalDateEnd: z.nullable(z.string()),
    netDiscount: z.nullable(netDiscountSchema),
    restrictions: offerRestrictionsSchema,
    usable: z.boolean(),
    unusableReason: z.nullable(z.string()),
    tags: z.array(z.string()),
    membershipBenefit: z.nullable(z.optional(membershipBenefitSchema)),
});
