// Generated by ts-to-zod
import * as z from 'zod/mini';
import { pricingSchema } from './Pricing';
import { unitSchema } from './Unit';
import { bookingSchema } from './Booking';
export const offerCombinationSchema = z.object({
	productId: z.string(),
	optionId: z.string(),
	offerCode: z.string(),
	offerTitle: z.string(),
	pricing: pricingSchema,
	shortDescription: z.optional(z.string()),
	units: z.array(unitSchema),
	booking: z.nullable(bookingSchema),
});
