// Generated by ts-to-zod
import * as z from 'zod/mini';
import { discountTaxSchema } from './DiscountTax';
export const offerDiscountSchema = z.object({
	net: z.nullable(z.number()),
	retail: z.number(),
	includedTaxes: z.array(discountTaxSchema),
});
