// Generated by ts-to-zod
import * as z from 'zod/mini';
import { durationUnitSchema } from './DurationUnit';
export const openingHoursSchema = z.object({
	from: z.string(),
	to: z.string(),
	frequency: z.nullable(z.optional(z.string())),
	frequencyAmount: z.nullable(z.optional(z.number())),
	frequencyUnit: z.optional(durationUnitSchema),
});
