// Generated by ts-to-zod
import * as z from 'zod/mini';
export const optionRestrictionsSchema = z.object({
	minUnits: z.nullable(z.number()),
	maxUnits: z.nullable(z.number()),
	minPaxCount: z.nullable(z.number()),
	maxPaxCount: z.nullable(z.number()),
});
