// Generated by ts-to-zod
import * as z from "zod/mini";
import { durationUnitSchema } from './DurationUnit';
import { contactFieldSchema } from './ContactField';
import { optionRestrictionsSchema } from './OptionRestrictions';
import { unitSchema } from './Unit';
import { itineraryItemSchema } from './ItineraryItem';
import { pointSchema } from './Point';
import { pickupPointSchema } from './PickupPoint';
import { pricingSchema } from './Pricing';
import { questionSchema } from './Question';
import { extraSchema } from './Extra';
import { packageIncludeSchema } from './PackageInclude';
import { rentalDurationSchema } from './RentalDuration';
import { type Option } from '../models/Option';
export const optionSchema: z.ZodMiniType<Option> = z.lazy(() => z.object({
    id: z.string(),
    default: z.boolean(),
    internalName: z.string(),
    reference: z.nullable(z.string()),
    availabilityLocalStartTimes: z.array(z.string()),
    availabilityLocalDateStart: z.nullable(z.string()),
    availabilityLocalDateEnd: z.nullable(z.string()),
    cancellationCutoff: z.string(),
    cancellationCutoffAmount: z.number(),
    cancellationCutoffUnit: durationUnitSchema,
    requiredContactFields: z.array(contactFieldSchema),
    availabilityCutoff: z.string(),
    availabilityCutoffAmount: z.number(),
    availabilityCutoffUnit: durationUnitSchema,
    availabilityNotice: z.nullable(z.string()),
    availabilityNoticeAmount: z.nullable(z.number()),
    availabilityNoticeUnit: z.nullable(durationUnitSchema),
    tags: z.array(z.string()),
    visibleContactFields: z.array(contactFieldSchema),
    restrictions: optionRestrictionsSchema,
    units: z.array(unitSchema),
    title: z.optional(z.string()),
    subtitle: z.nullable(z.optional(z.string())),
    language: z.optional(z.string()),
    shortDescription: z.nullable(z.optional(z.string())),
    duration: z.nullable(z.optional(z.string())),
    durationAmount: z.nullable(z.optional(z.number())),
    durationUnit: z.nullable(z.optional(durationUnitSchema)),
    coverImageUrl: z.nullable(z.optional(z.string())),
    itinerary: z.nullable(z.optional(z.array(itineraryItemSchema))),
    fromPoint: z.nullable(z.optional(pointSchema)),
    toPoint: z.nullable(z.optional(pointSchema)),
    meetingPoint: z.nullable(z.optional(z.string())),
    meetingPointCoordinates: z.nullable(z.optional(z.string())),
    meetingPointDirections: z.nullable(z.optional(z.string())),
    meetingPointLatitude: z.nullable(z.optional(z.number())),
    meetingPointLongitude: z.nullable(z.optional(z.number())),
    pickupAvailable: z.optional(z.boolean()),
    pickupRequired: z.optional(z.boolean()),
    pickupPoints: z.optional(z.array(pickupPointSchema)),
    pricingFrom: z.optional(z.array(pricingSchema)),
    pricing: z.optional(z.array(pricingSchema)),
    questions: z.optional(z.array(questionSchema)),
    extras: z.optional(z.array(extraSchema)),
    packageIncludes: z.optional(z.array(packageIncludeSchema)),
    rentalDurations: z.optional(z.array(rentalDurationSchema)),
}));
