// Generated by ts-to-zod
import * as z from 'zod/mini';
import { pricingSchema } from './Pricing';
export const optionPricingSchema = z.object({
	pricingFrom: z.optional(z.array(pricingSchema)),
	pricing: z.optional(z.array(pricingSchema)),
});
