// Generated by ts-to-zod
import * as z from "zod/mini";
import { pickupPointSchema } from './PickupPoint';
export const optionPickupsSchema = z.object({
    pickupAvailable: z.optional(z.boolean()),
    pickupRequired: z.optional(z.boolean()),
    pickupPoints: z.optional(z.array(pickupPointSchema)),
});
