// Generated by ts-to-zod
import * as z from 'zod/mini';
import { packageIncludeSchema } from './PackageInclude';
export const optionPackagesSchema = z.object({
	packageIncludes: z.optional(z.array(packageIncludeSchema)),
});
