// Generated by ts-to-zod
import * as z from 'zod/mini';
import { durationUnitSchema } from './DurationUnit';
import { itineraryItemSchema } from './ItineraryItem';
import { pointSchema } from './Point';
export const optionContentSchema = z.object({
	title: z.optional(z.string()),
	subtitle: z.nullable(z.optional(z.string())),
	language: z.optional(z.string()),
	shortDescription: z.nullable(z.optional(z.string())),
	duration: z.nullable(z.optional(z.string())),
	durationAmount: z.nullable(z.optional(z.number())),
	durationUnit: z.nullable(z.optional(durationUnitSchema)),
	coverImageUrl: z.nullable(z.optional(z.string())),
	itinerary: z.nullable(z.optional(z.array(itineraryItemSchema))),
	fromPoint: z.nullable(z.optional(pointSchema)),
	toPoint: z.nullable(z.optional(pointSchema)),
	meetingPoint: z.nullable(z.optional(z.string())),
	meetingPointCoordinates: z.nullable(z.optional(z.string())),
	meetingPointDirections: z.nullable(z.optional(z.string())),
	meetingPointLatitude: z.nullable(z.optional(z.number())),
	meetingPointLongitude: z.nullable(z.optional(z.number())),
});
