// Generated by ts-to-zod
import * as z from "zod/mini";
import { rentalDurationSchema } from './RentalDuration';
export const optionRentalsSchema = z.object({
    rentalDurations: z.optional(z.array(rentalDurationSchema)),
});
