// Generated by ts-to-zod
import * as z from "zod/mini";
export const orderVentrataCheckoutSchema = z.object({
    fingerprintLinkedId: z.nullable(z.optional(z.string())),
    fingerprintReceived: z.optional(z.boolean()),
    recaptchaEnterpriseReceived: z.nullable(z.optional(z.string())),
    recoveryUrl: z.nullable(z.optional(z.string())),
    segmentAnonymousId: z.nullable(z.optional(z.string())),
    utmCampaign: z.nullable(z.optional(z.string())),
    utmContent: z.nullable(z.optional(z.string())),
    utmMedium: z.nullable(z.optional(z.string())),
    utmSource: z.nullable(z.optional(z.string())),
});
