// Generated by ts-to-zod
import * as z from "zod/mini";
import { destinationSchema } from './Destination';
import { brandSchema } from './Brand';
export const orderContentSchema = z.object({
    termsAccepted: z.optional(z.boolean()),
    destination: z.optional(destinationSchema),
    brand: z.optional(brandSchema),
});
