// Generated by ts-to-zod
import * as z from 'zod/mini';
import { identitySchema } from './Identity';
export const orderIdentitiesSchema = z.object({
	identity: z.optional(identitySchema),
	identityId: z.optional(z.string()),
});
