// Generated by ts-to-zod
import * as z from "zod/mini";
import { offerCombinationSchema } from './OfferCombination';
export const orderOffersSchema = z.object({
    offerCombinations: z.optional(z.array(offerCombinationSchema)),
});
