// Generated by ts-to-zod
import * as z from "zod/mini";
import { giftPaymentSchema } from './GiftPayment';
import { giftSchema } from './Gift';
export const orderGiftsSchema = z.object({
    giftPayment: z.nullable(z.optional(giftPaymentSchema)),
    gifts: z.optional(z.array(giftSchema)),
});
