// Generated by ts-to-zod
import * as z from "zod/mini";
import { membershipSchema } from './Membership';
export const orderMembershipsSchema = z.object({
    membership: z.nullable(z.optional(membershipSchema)),
});
