// Generated by ts-to-zod
import * as z from 'zod/mini';
import { cardPaymentGatewaySchema } from './CardPaymentGateway';
export const orderCardPaymentsSchema = z.object({
	cardPayment: z.nullable(z.optional(cardPaymentGatewaySchema)),
	returnUrl: z.nullable(z.optional(z.string())),
});
