// Generated by ts-to-zod
import * as z from 'zod/mini';
import { settlementMethodSchema } from './SettlementMethod';
import { agentSchema } from './Agent';
import { customerContactSchema } from './CustomerContact';
import { bookingSchema } from './Booking';
import { contactFieldSchema } from './ContactField';
import { giftVoucherSchema } from './GiftVoucher';
import { destinationSchema } from './Destination';
import { brandSchema } from './Brand';
import { pricingSchema } from './Pricing';
import { questionAnswerSchema } from './QuestionAnswer';
import { identitySchema } from './Identity';
import { offerCombinationSchema } from './OfferCombination';
import { giftPaymentSchema } from './GiftPayment';
import { giftSchema } from './Gift';
import { membershipSchema } from './Membership';
import { cardPaymentGatewaySchema } from './CardPaymentGateway';
export const orderSchema = z.object({
	id: z.string(),
	testMode: z.boolean(),
	settlementMethod: settlementMethodSchema,
	settlementMethods: z.array(settlementMethodSchema),
	supplierReference: z.string(),
	quote: z.boolean(),
	status: z.string(),
	internalStatus: z.string(),
	utcCreatedAt: z.string(),
	utcExpiresAt: z.nullable(z.string()),
	utcConfirmedAt: z.nullable(z.string()),
	utcUpdatedAt: z.nullable(z.string()),
	cancellable: z.boolean(),
	confirmable: z.boolean(),
	updatable: z.boolean(),
	agent: z.optional(agentSchema),
	contact: z.optional(customerContactSchema),
	emailReceipt: z.optional(z.boolean()),
	notes: z.nullable(z.optional(z.string())),
	bookings: z.array(bookingSchema),
	visibleContactFields: z.array(contactFieldSchema),
	requiredContactFields: z.array(contactFieldSchema),
	voucher: z.nullable(giftVoucherSchema),
	active: z.boolean(),
	termsAccepted: z.optional(z.boolean()),
	destination: z.optional(destinationSchema),
	brand: z.optional(brandSchema),
	pricing: z.optional(pricingSchema),
	questionAnswers: z.optional(z.array(questionAnswerSchema)),
	identity: z.optional(identitySchema),
	identityId: z.optional(z.string()),
	offerCombinations: z.optional(z.array(offerCombinationSchema)),
	giftPayment: z.nullable(z.optional(giftPaymentSchema)),
	gifts: z.optional(z.array(giftSchema)),
	checkinAvailable: z.optional(z.boolean()),
	checkinUrl: z.nullable(z.optional(z.string())),
	membership: z.nullable(z.optional(membershipSchema)),
	cardPayment: z.nullable(z.optional(cardPaymentGatewaySchema)),
	returnUrl: z.nullable(z.optional(z.string())),
	fingerprintLinkedId: z.nullable(z.optional(z.string())),
	fingerprintReceived: z.optional(z.boolean()),
	recaptchaEnterpriseReceived: z.nullable(z.optional(z.string())),
	recoveryUrl: z.nullable(z.optional(z.string())),
	segmentAnonymousId: z.nullable(z.optional(z.string())),
	utmCampaign: z.nullable(z.optional(z.string())),
	utmContent: z.nullable(z.optional(z.string())),
	utmMedium: z.nullable(z.optional(z.string())),
	utmSource: z.nullable(z.optional(z.string())),
});
