// Generated by ts-to-zod
import * as z from "zod/mini";
import { includeSchema } from './Include';
import { type PackageInclude } from '../models/PackageInclude';
export const packageIncludeSchema: z.ZodMiniType<PackageInclude> = z.lazy(() => z.object({
    title: z.optional(z.string()),
    count: z.number(),
    includes: z.array(includeSchema),
}));
