// Generated by ts-to-zod
import * as z from 'zod/mini';
import { availableLanguagesItemSchema } from './AvailableLanguagesItem';
export const pageSchema = z.object({
	id: z.string(),
	body: z.optional(z.string()),
	fullscreen: z.boolean(),
	href: z.optional(z.string()),
	availableLanguages: z.nullable(availableLanguagesItemSchema),
	meta: z.optional(z.record(z.string(), z.string())),
	shortDescription: z.nullable(z.string()),
	showFooter: z.boolean(),
	showHeader: z.boolean(),
	title: z.nullable(z.string()),
});
