// Generated by ts-to-zod
import * as z from 'zod/mini';
export const paytrGatewaySchema = z.object({
	id: z.nullable(z.optional(z.string())),
	iframeUrl: z.nullable(z.optional(z.string())),
	error: z.nullable(z.optional(z.string())),
});
