// Generated by ts-to-zod
import * as z from 'zod/mini';
export const peachGatewaySchema = z.object({
	key: z.optional(z.any()),
	entityId: z.optional(z.string()),
	checkoutId: z.nullable(z.optional(z.string())),
});
