// Generated by ts-to-zod
import * as z from "zod/mini";
import { pointGroupSchema } from './PointGroup';
export const pointSchema = z.object({
    id: z.string(),
    internalName: z.nullable(z.string()),
    title: z.nullable(z.string()),
    shortDescription: z.nullable(z.string()),
    pointGroup: pointGroupSchema,
});
