// Generated by ts-to-zod
import * as z from 'zod/mini';
export const pointGroupSchema = z.object({
	id: z.string(),
	internalName: z.string(),
	title: z.string(),
	shortDescription: z.nullable(z.string()),
});
