// Generated by ts-to-zod
import * as z from "zod/mini";
import { taxSchema } from './Tax';
import { unitTypeSchema } from './UnitType';
import { offerDiscountSchema } from './OfferDiscount';
import { extraPricingSchema } from './ExtraPricing';
export const pricingUnitSchema = z.object({
    original: z.number(),
    retail: z.number(),
    net: z.nullable(z.number()),
    currency: z.string(),
    currencyPrecision: z.number(),
    includedTaxes: z.array(taxSchema),
    unitId: z.string(),
    unitType: unitTypeSchema,
    offerDiscount: z.nullable(z.optional(offerDiscountSchema)),
    extraPricing: z.optional(z.array(extraPricingSchema)),
    extraPricingFrom: z.optional(z.array(extraPricingSchema)),
});
