// Generated by ts-to-zod
import * as z from "zod/mini";
import { offerDiscountSchema } from './OfferDiscount';
export const pricingOffersSchema = z.object({
    offerDiscount: z.nullable(z.optional(offerDiscountSchema)),
});
