// Generated by ts-to-zod
import * as z from 'zod/mini';
import { extraPricingSchema } from './ExtraPricing';
export const pricingExtrasSchema = z.object({
	extraPricing: z.optional(z.array(extraPricingSchema)),
	extraPricingFrom: z.optional(z.array(extraPricingSchema)),
});
