// Generated by ts-to-zod
import * as z from "zod/mini";
import { destinationSchema } from './Destination';
import { categorySchema } from './Category';
import { fAQSchema } from './FAQ';
import { imageSchema } from './Image';
import { brandSchema } from './Brand';
export const productContentSchema = z.object({
    country: z.optional(z.string()),
    location: z.nullable(z.optional(z.string())),
    destination: z.optional(destinationSchema),
    alert: z.nullable(z.optional(z.string())),
    title: z.optional(z.string()),
    subtitle: z.nullable(z.optional(z.string())),
    description: z.nullable(z.optional(z.string())),
    shortDescription: z.nullable(z.optional(z.string())),
    categories: z.optional(z.array(categorySchema)),
    inclusions: z.optional(z.array(z.string())),
    exclusions: z.optional(z.array(z.string())),
    highlights: z.optional(z.array(z.string())),
    pointToPoint: z.optional(z.boolean()),
    bookingTerms: z.nullable(z.optional(z.string())),
    privacyTerms: z.nullable(z.optional(z.string())),
    redemptionInstructions: z.nullable(z.optional(z.string())),
    usageInstructions: z.nullable(z.optional(z.string())),
    cancellationPolicy: z.nullable(z.optional(z.string())),
    faqs: z.optional(z.array(fAQSchema)),
    coverImageUrl: z.nullable(z.optional(z.string())),
    bannerImageUrl: z.nullable(z.optional(z.string())),
    logoUrl: z.nullable(z.optional(z.string())),
    videoUrl: z.nullable(z.optional(z.string())),
    galleryImages: z.optional(z.array(imageSchema)),
    bannerImages: z.optional(z.array(imageSchema)),
    googlePlaceId: z.nullable(z.optional(z.string())),
    latitude: z.nullable(z.optional(z.number())),
    longitude: z.nullable(z.optional(z.number())),
    address: z.nullable(z.optional(z.string())),
    keywords: z.optional(z.array(z.string())),
    tagline: z.nullable(z.optional(z.string())),
    brand: z.optional(brandSchema),
});
