// Generated by ts-to-zod
import * as z from 'zod/mini';
export const productPackagesSchema = z.object({
	isPackage: z.optional(z.boolean()),
	packageBookingAvailabilityRequired: z.optional(z.boolean()),
	packageProduct: z.optional(z.boolean()),
});
