// Generated by ts-to-zod
import * as z from 'zod/mini';
import { availabilityTypeSchema } from './AvailabilityType';
import { deliveryFormatSchema } from './DeliveryFormat';
import { deliveryMethodSchema } from './DeliveryMethod';
import { redemptionMethodSchema } from './RedemptionMethod';
import { settlementMethodSchema } from './SettlementMethod';
import { durationUnitSchema } from './DurationUnit';
import { optionSchema } from './Option';
import { operatorSchema } from './Operator';
import { destinationSchema } from './Destination';
import { categorySchema } from './Category';
import { fAQSchema } from './FAQ';
import { imageSchema } from './Image';
import { brandSchema } from './Brand';
import { pricingPerSchema } from './PricingPer';
import { googleOptionsSchema } from './GoogleOptions';
import { checkoutConfigPricingDisplaySchema } from './CheckoutConfigPricingDisplay';
import { linkSchema } from './Link';
import { availableLanguagesItemSchema } from './AvailableLanguagesItem';
import { type Product } from '../models/Product';
export const productSchema: z.ZodMiniType<Product> = z.lazy(() =>
	z.object({
		id: z.string(),
		internalName: z.string(),
		reference: z.nullable(z.string()),
		locale: z.string(),
		timeZone: z.string(),
		allowFreesale: z.boolean(),
		instantConfirmation: z.boolean(),
		instantDelivery: z.boolean(),
		availabilityRequired: z.boolean(),
		availabilityAllowed: z.boolean(),
		availabilityType: availabilityTypeSchema,
		deliveryFormats: z.array(deliveryFormatSchema),
		deliveryMethods: z.array(deliveryMethodSchema),
		redemptionMethod: redemptionMethodSchema,
		tags: z.array(z.string()),
		settlementMethods: z.array(settlementMethodSchema),
		freesaleDurationAmount: z.number(),
		freesaleDurationUnit: durationUnitSchema,
		fixedWeight: z.boolean(),
		weightUnit: z.string(),
		freesaleDurationRoundup: z.boolean(),
		freesaleDurationRoundupUnit: z.string(),
		options: z.array(optionSchema),
		operator: z.nullable(operatorSchema),
		country: z.optional(z.string()),
		location: z.nullable(z.optional(z.string())),
		destination: z.optional(destinationSchema),
		alert: z.nullable(z.optional(z.string())),
		title: z.optional(z.string()),
		subtitle: z.nullable(z.optional(z.string())),
		description: z.nullable(z.optional(z.string())),
		shortDescription: z.nullable(z.optional(z.string())),
		categories: z.optional(z.array(categorySchema)),
		inclusions: z.optional(z.array(z.string())),
		exclusions: z.optional(z.array(z.string())),
		highlights: z.optional(z.array(z.string())),
		pointToPoint: z.optional(z.boolean()),
		bookingTerms: z.nullable(z.optional(z.string())),
		privacyTerms: z.nullable(z.optional(z.string())),
		redemptionInstructions: z.nullable(z.optional(z.string())),
		usageInstructions: z.nullable(z.optional(z.string())),
		cancellationPolicy: z.nullable(z.optional(z.string())),
		faqs: z.optional(z.array(fAQSchema)),
		coverImageUrl: z.nullable(z.optional(z.string())),
		bannerImageUrl: z.nullable(z.optional(z.string())),
		logoUrl: z.nullable(z.optional(z.string())),
		videoUrl: z.nullable(z.optional(z.string())),
		galleryImages: z.optional(z.array(imageSchema)),
		bannerImages: z.optional(z.array(imageSchema)),
		googlePlaceId: z.nullable(z.optional(z.string())),
		latitude: z.nullable(z.optional(z.number())),
		longitude: z.nullable(z.optional(z.number())),
		address: z.nullable(z.optional(z.string())),
		keywords: z.optional(z.array(z.string())),
		tagline: z.nullable(z.optional(z.string())),
		brand: z.optional(brandSchema),
		defaultCurrency: z.optional(z.string()),
		availableCurrencies: z.optional(z.array(z.string())),
		pricingPer: z.optional(pricingPerSchema),
		includeTax: z.optional(z.boolean()),
		hidePricingFrom: z.optional(z.boolean()),
		isPackage: z.optional(z.boolean()),
		packageBookingAvailabilityRequired: z.optional(z.boolean()),
		packageProduct: z.optional(z.boolean()),
		googleOptions: z.optional(googleOptionsSchema),
		isMembership: z.optional(z.boolean()),
		isRental: z.optional(z.boolean()),
		pricingDisplay: z.optional(checkoutConfigPricingDisplaySchema),
		outstandingBalanceShortDescription: z.optional(z.string()),
		outstandingBalanceTitle: z.optional(z.string()),
		href: z.nullable(z.optional(z.string())),
		meta: z.optional(z.record(z.string(), z.string())),
		links: z.optional(z.array(linkSchema)),
		giftCardAllowed: z.optional(z.boolean()),
		relatedProductIds: z.optional(z.array(z.string())),
		availableLanguages: z.nullable(z.optional(availableLanguagesItemSchema)),
	}),
);
