// Generated by ts-to-zod
import * as z from 'zod/mini';
import { pricingPerSchema } from './PricingPer';
export const productPricingSchema = z.object({
	defaultCurrency: z.optional(z.string()),
	availableCurrencies: z.optional(z.array(z.string())),
	pricingPer: z.optional(pricingPerSchema),
	includeTax: z.optional(z.boolean()),
	hidePricingFrom: z.optional(z.boolean()),
});
