// Generated by ts-to-zod
import * as z from "zod/mini";
import { googleOptionsSchema } from './GoogleOptions';
export const productGoogleSchema = z.object({
    googleOptions: z.optional(googleOptionsSchema),
});
