// Generated by ts-to-zod
import * as z from "zod/mini";
import { linkSchema } from './Link';
import { availableLanguagesSchema } from './AvailableLanguages';
export const productVentrataCheckoutContentSchema = z.object({
    href: z.nullable(z.optional(z.string())),
    meta: z.optional(z.record(z.string(), z.string())),
    links: z.optional(z.array(linkSchema)),
    giftCardAllowed: z.optional(z.boolean()),
    relatedProductIds: z.optional(z.array(z.string())),
    availableLanguages: z.nullable(z.optional(availableLanguagesSchema)),
});
