// Generated by ts-to-zod
import * as z from "zod/mini";
import { checkoutConfigPricingDisplaySchema } from './CheckoutConfigPricingDisplay';
export const productVentrataCheckoutSchema = z.object({
    pricingDisplay: z.optional(checkoutConfigPricingDisplaySchema),
    outstandingBalanceShortDescription: z.optional(z.string()),
    outstandingBalanceTitle: z.optional(z.string()),
});
