// Generated by ts-to-zod
import * as z from 'zod/mini';
import { questionSchema } from './Question';
export const questionAnswerSchema = z.object({
	questionId: z.string(),
	question: questionSchema,
	value: z.nullable(z.string()),
});
