// Generated by ts-to-zod
import * as z from "zod/mini";
import { questionInputTypeSchema } from './QuestionInputType';
import { selectOptionSchema } from './SelectOption';
import { dependentAnswerSchema } from './DependentAnswer';
export const questionSchema = z.object({
    id: z.string(),
    label: z.nullable(z.string()),
    maxLength: z.nullable(z.number()),
    inputType: questionInputTypeSchema,
    required: z.boolean(),
    selectOptions: z.array(selectOptionSchema),
    dependentAnswers: z.array(dependentAnswerSchema),
    coverImageUrl: z.nullable(z.string()),
    description: z.nullable(z.string()),
    shortDescription: z.nullable(z.string()),
    internalName: z.nullable(z.string()),
    title: z.nullable(z.string()),
    pattern: z.nullable(z.string()),
});
