// Generated by ts-to-zod
import * as z from 'zod/mini';
import { durationUnitSchema } from './DurationUnit';
export const rentalDurationSchema = z.object({
	id: z.string(),
	title: z.string(),
	shortDescription: z.nullable(z.string()),
	durationAmount: z.number(),
	durationUnit: durationUnitSchema,
	pricingMultiplier: z.number(),
});
