// Generated by ts-to-zod
import * as z from "zod/mini";
import { resourceGroupSchema } from './ResourceGroup';
import { resourceSchema } from './Resource';
import { seatSchema } from './Seat';
import { sellerSchema } from './Seller';
export const resourceAllocationSchema = z.object({
    id: z.string(),
    resourceGroupId: z.string(),
    resourceGroup: resourceGroupSchema,
    resourceId: z.string(),
    resource: resourceSchema,
    paxCount: z.number(),
    seatIds: z.array(z.string()),
    seats: z.array(seatSchema),
    guide: z.nullable(sellerSchema),
    driver: z.nullable(sellerSchema),
});
