// Generated by ts-to-zod
import * as z from 'zod/mini';
export const spreedlyGatewaySchema = z.object({
	env: z.optional(z.string()),
	nonce: z.optional(z.string()),
	timestamp: z.optional(z.string()),
	certificateToken: z.optional(z.string()),
	signature: z.optional(z.string()),
});
