// Generated by ts-to-zod
import * as z from 'zod/mini';
export const stripeGatewaySchema = z.object({
	version: z.optional(z.string()),
	paymentIntent: z.nullable(
		z.optional(
			z.object({
				id: z.string(),
				publishableKey: z.string(),
				clientSecret: z.string(),
				amount: z.number(),
				currency: z.string(),
			}),
		),
	),
	setupIntent: z.optional(
		z.object({
			id: z.string(),
			publishableKey: z.string(),
			clientSecret: z.string(),
		}),
	),
});
