// Generated by ts-to-zod
import * as z from "zod/mini";
import { destinationSchema } from './Destination';
export const supplierContentSchema = z.object({
    country: z.nullable(z.optional(z.string())),
    destinations: z.optional(z.array(destinationSchema)),
});
