// Generated by ts-to-zod
import * as z from "zod/mini";
export const supplierContactSchema = z.object({
    website: z.nullable(z.string()),
    email: z.nullable(z.string()),
    telephone: z.nullable(z.string()),
    address: z.nullable(z.string()),
});
