// Generated by ts-to-zod
import * as z from 'zod/mini';
import { supplierContactSchema } from './SupplierContact';
import { destinationSchema } from './Destination';
export const supplierSchema = z.object({
	id: z.string(),
	name: z.string(),
	endpoint: z.string(),
	contact: supplierContactSchema,
	country: z.nullable(z.optional(z.string())),
	destinations: z.optional(z.array(destinationSchema)),
});
