// Generated by ts-to-zod
import * as z from "zod/mini";
export const taxSchema = z.object({
    name: z.string(),
    retail: z.number(),
    original: z.number(),
    net: z.nullable(z.number()),
    shortDescription: z.nullable(z.string()),
});
