// Generated by ts-to-zod
import * as z from 'zod/mini';
import { unitTypeSchema } from './UnitType';
export const unitRestrictionsSchema = z.object({
	minAge: z.number(),
	maxAge: z.number(),
	idRequired: z.boolean(),
	minQuantity: z.nullable(z.number()),
	maxQuantity: z.nullable(z.number()),
	paxCount: z.number(),
	accompaniedBy: z.array(unitTypeSchema),
	minHeight: z.optional(z.number()),
	maxHeight: z.optional(z.number()),
	heightUnit: z.optional(z.string()),
	minWeight: z.optional(z.number()),
	maxWeight: z.optional(z.number()),
	weightUnit: z.optional(z.string()),
	required: z.boolean(),
	accompaniedByRatio: z.nullable(z.number()),
	accompaniedByRatioDenominator: z.optional(z.number()),
	notAccompaniedBy: z.array(unitTypeSchema),
});
