// Generated by ts-to-zod
import * as z from 'zod/mini';
export const unitItemIdentifierSchema = z.object({
	uuid: z.optional(z.string()),
	unitId: z.optional(z.string()),
	unitType: z.optional(z.string()),
	resellerReference: z.optional(z.string()),
	alias: z.optional(z.string()),
	weightValue: z.optional(z.number()),
	weightUnit: z.optional(z.string()),
});
