// Generated by ts-to-zod
import * as z from "zod/mini";
export const unitContentSchema = z.object({
    title: z.optional(z.string()),
    titlePlural: z.optional(z.string()),
    subtitle: z.nullable(z.optional(z.string())),
});
