// Generated by ts-to-zod
import * as z from "zod/mini";
import { unitTypeSchema } from './UnitType';
import { contactFieldSchema } from './ContactField';
import { unitRestrictionsSchema } from './UnitRestrictions';
import { pricingSchema } from './Pricing';
import { questionSchema } from './Question';
import { extraSchema } from './Extra';
import { membershipBenefitSchema } from './MembershipBenefit';
export const unitSchema = z.object({
    id: z.string(),
    internalName: z.string(),
    reference: z.nullable(z.string()),
    type: unitTypeSchema,
    requiredContactFields: z.array(contactFieldSchema),
    tags: z.array(z.string()),
    visibleContactFields: z.array(contactFieldSchema),
    restrictions: unitRestrictionsSchema,
    title: z.optional(z.string()),
    titlePlural: z.optional(z.string()),
    subtitle: z.nullable(z.optional(z.string())),
    pricingFrom: z.optional(z.array(pricingSchema)),
    pricing: z.optional(z.array(pricingSchema)),
    questions: z.optional(z.array(questionSchema)),
    extras: z.optional(z.array(extraSchema)),
    membershipBenefit: z.nullable(z.optional(membershipBenefitSchema)),
    redemptionCode: z.nullable(z.optional(z.string())),
});
