// Generated by ts-to-zod
import * as z from "zod/mini";
import { questionSchema } from './Question';
export const unitQuestionsSchema = z.object({
    questions: z.optional(z.array(questionSchema)),
});
