// Generated by ts-to-zod
import * as z from "zod/mini";
import { extraItemSchema } from './ExtraItem';
export const unitItemExtrasSchema = z.object({
    extraItems: z.optional(z.array(extraItemSchema)),
});
