// Generated by ts-to-zod
import * as z from 'zod/mini';
import { unitSchema } from './Unit';
import { bookingStatusSchema } from './BookingStatus';
import { customerContactSchema } from './CustomerContact';
import { ticketSchema } from './Ticket';
import { unitTypeSchema } from './UnitType';
import { pricingSchema } from './Pricing';
import { questionAnswerSchema } from './QuestionAnswer';
import { extraItemSchema } from './ExtraItem';
import { scanSchema } from './Scan';
export const unitItemSchema = z.object({
	uuid: z.nullable(z.string()),
	resellerReference: z.nullable(z.string()),
	supplierReference: z.nullable(z.string()),
	unitId: z.string(),
	unit: unitSchema,
	weightValue: z.number(),
	weightUnit: z.string(),
	status: bookingStatusSchema,
	internalStatus: z.string(),
	utcRedeemedAt: z.nullable(z.string()),
	contact: z.optional(customerContactSchema),
	ticket: z.nullable(ticketSchema),
	id: z.string(),
	alias: z.nullable(z.string()),
	rebookingUuid: z.nullable(z.string()),
	rebookingUnitItemUuid: z.nullable(z.string()),
	originalRebookingUuid: z.nullable(z.string()),
	originalRebookingUnitItemUuid: z.nullable(z.string()),
	utcRebookedAt: z.nullable(z.string()),
	utcNoshowedAt: z.nullable(z.string()),
	requiredContactFields: z.array(z.string()),
	visibleContactFields: z.array(z.string()),
	unitType: unitTypeSchema,
	localDateTimeStart: z.optional(z.string()),
	localDateTimeEnd: z.optional(z.string()),
	pricing: z.optional(pricingSchema),
	questionAnswers: z.optional(z.array(questionAnswerSchema)),
	extraItems: z.optional(z.array(extraItemSchema)),
	scans: z.optional(z.array(scanSchema)),
});
