// Generated by ts-to-zod
import * as z from 'zod/mini';
import { customerContactSchema } from './CustomerContact';
import { giftPaymentSchema } from './GiftPayment';
import { settlementMethodSchema } from './SettlementMethod';
export const updateGiftBodySchema = z.object({
	alias: z.optional(z.string()),
	amount: z.optional(z.number()),
	contact: z.optional(customerContactSchema),
	currency: z.optional(z.string()),
	emailReceipt: z.optional(z.boolean()),
	expirationMinutes: z.optional(z.number()),
	giftPayment: z.optional(giftPaymentSchema),
	message: z.optional(z.string()),
	notes: z.optional(z.string()),
	resellerReference: z.optional(z.string()),
	settlementMethod: z.optional(settlementMethodSchema),
});
