// Generated by ts-to-zod
import * as z from "zod/mini";
import { bookingContactSchema } from './BookingContact';
import { settlementMethodSchema } from './SettlementMethod';
export const updateOrderBodySchema = z.object({
    expirationMinutes: z.optional(z.number()),
    emailReceipt: z.optional(z.boolean()),
    contact: z.optional(bookingContactSchema),
    quote: z.optional(z.boolean()),
    settlementMethod: z.optional(settlementMethodSchema),
    notes: z.nullable(z.optional(z.string())),
    currency: z.optional(z.string()),
});
