// Generated by ts-to-zod
import * as z from 'zod/mini';
export const userSchema = z.object({
	id: z.string(),
	name: z.string(),
	reference: z.nullable(z.string()),
	tags: z.array(z.string()),
	emailAddress: z.string(),
	phoneNumber: z.nullable(z.string()),
});
