// Generated by ts-to-zod
import * as z from 'zod/mini';
import { defaultableIDSchema } from './DefaultableID';
import { waitlistUnitIdentifierSchema } from './WaitlistUnitIdentifier';
import { customerContactSchema } from './CustomerContact';
import { contactFieldSchema } from './ContactField';
export const waitlistSchema = z.object({
	id: z.string(),
	productId: z.string(),
	optionId: defaultableIDSchema,
	localDate: z.string(),
	units: z.array(waitlistUnitIdentifierSchema),
	contact: z.nullable(customerContactSchema),
	visibleContactFields: z.array(contactFieldSchema),
	requiredContactFields: z.array(contactFieldSchema),
});
