// Generated by ts-to-zod
import * as z from 'zod/mini';
import { supplierSchema } from './Supplier';
import { connectionSchema } from './Connection';
import { partnerSchema } from './Partner';
import { resellerSchema } from './Reseller';
import { checkoutSchema } from './Checkout';
import { operatorSchema } from './Operator';
import { terminalSchema } from './Terminal';
export const whoAmISchema = z.object({
	supplier: supplierSchema,
	connection: connectionSchema,
	partner: z.nullable(partnerSchema),
	reseller: z.nullable(resellerSchema),
	checkout: z.nullable(checkoutSchema),
	operator: z.nullable(operatorSchema),
	terminal: z.nullable(terminalSchema),
});
