// Generated by ts-to-zod
import { z } from 'zod';
import { adyenGatewaySessionSchema } from './AdyenGatewaySession';
import { adyenPaymentMethodsConfigurationSchema } from './AdyenPaymentMethodsConfiguration';

export const adyenGatewaySchema = z.object({
	environment: z.string().optional(),
	clientKey: z.string().optional(),
	session: adyenGatewaySessionSchema.optional().nullable(),
	countryCode: z.string().optional(),
	paymentMethodsConfiguration: adyenPaymentMethodsConfigurationSchema.optional(),
});
