// Generated by ts-to-zod
import * as z from 'zod';
import { AdyenPaymentMethodsConfigurationGooglePayBillingAddressParameters } from '../models/AdyenPaymentMethodsConfigurationGooglePayBillingAddressParameters';

export const adyenPaymentMethodsConfigurationGooglePayBillingAddressParametersSchema = z.enum(
	AdyenPaymentMethodsConfigurationGooglePayBillingAddressParameters,
);
