// Generated by ts-to-zod
import { z } from 'zod';
import { AdyenPaymentMethodsConfigurationGooglePayBillingAddressParameters } from '../models/AdyenPaymentMethodsConfigurationGooglePayBillingAddressParameters';

export const adyenPaymentMethodsConfigurationGooglePayBillingAddressParametersSchema = z.nativeEnum(
	AdyenPaymentMethodsConfigurationGooglePayBillingAddressParameters,
);
