// Generated by ts-to-zod
import { z } from 'zod';
import { adyenPaymentMethodsConfigurationCardSchema } from './AdyenPaymentMethodsConfigurationCard';
import { adyenPaymentMethodsConfigurationPayPaySchema } from './AdyenPaymentMethodsConfigurationPayPay';
import { adyenPaymentMethodsConfigurationApplePaySchema } from './AdyenPaymentMethodsConfigurationApplePay';
import { adyenPaymentMethodsConfigurationGooglePaySchema } from './AdyenPaymentMethodsConfigurationGooglePay';

export const adyenPaymentMethodsConfigurationSchema = z.object({
	card: adyenPaymentMethodsConfigurationCardSchema,
	paypal: adyenPaymentMethodsConfigurationPayPaySchema,
	applepay: adyenPaymentMethodsConfigurationApplePaySchema,
	googlepay: adyenPaymentMethodsConfigurationGooglePaySchema,
});
