// Generated by ts-to-zod
import { z } from 'zod';
import { AdyenPaymentMethodsConfigurationCardBillingAddressMode } from '../models/AdyenPaymentMethodsConfigurationCardBillingAddressMode';

export const adyenPaymentMethodsConfigurationCardBillingAddressModeSchema = z.nativeEnum(
	AdyenPaymentMethodsConfigurationCardBillingAddressMode,
);
