// Generated by ts-to-zod
import { z } from 'zod';
import { adyenPaymentMethodsConfigurationCardBillingAddressModeSchema } from './AdyenPaymentMethodsConfigurationCardBillingAddressMode';

export const adyenPaymentMethodsConfigurationCardSchema = z.object({
	hasHolderName: z.boolean(),
	billingAddressRequired: z.boolean(),
	billingAddressMode: adyenPaymentMethodsConfigurationCardBillingAddressModeSchema,
	data: z.object({
		holderName: z.string(),
		billingAddress: z.object({
			street: z.string(),
			postalCode: z.string(),
			city: z.string(),
			country: z.string(),
			stateOrProvince: z.string(),
		}),
	}),
	clickToPayConfiguration: z.object({
		merchantDisplayName: z.string(),
		shopperEmail: z.string(),
	}),
});
