// Generated by ts-to-zod
import { z } from 'zod';
import { adyenPaymentMethodsConfigurationGooglePayBillingAddressParametersSchema } from './AdyenPaymentMethodsConfigurationGooglePayBillingAddressParameters';

export const adyenPaymentMethodsConfigurationGooglePaySchema = z.object({
	billingAddressRequired: z.boolean(),
	billingAddressParameters: adyenPaymentMethodsConfigurationGooglePayBillingAddressParametersSchema,
});
