// Generated by ts-to-zod
import { z } from 'zod';

export const adyenPaymentMethodsConfigurationPayPaySchema = z.object({
	blockPayPalCreditButton: z.boolean(),
	blockPayPalPayLaterButton: z.boolean(),
	blockPayPalVenmoButton: z.boolean(),
});
