// Generated by ts-to-zod
import { z } from 'zod';
import { AdyenPaymentMethodsConfigurationGooglePayBillingAddressParameters } from '../models/AdyenPaymentMethodsConfigurationGooglePay';

export const adyenPaymentMethodsConfigurationGooglePaySchema = z.object({
	billingAddressRequired: z.boolean(),
	billingAddressParameters: z.literal(AdyenPaymentMethodsConfigurationGooglePay.billingAddressParameters),
});

export const adyenPaymentMethodsConfigurationGooglePayBillingAddressParametersSchema = z.nativeEnum(
	AdyenPaymentMethodsConfigurationGooglePayBillingAddressParameters,
);
