// Generated by ts-to-zod
import { z } from 'zod';

export const articleSchema = z.object({
	id: z.string(),
	bannerImageUrl: z.string().nullable(),
	coverImageUrl: z.string().nullable(),
	href: z.string().nullable(),
	keywords: z.array(z.string()),
	meta: z.record(z.string()),
	shortDescription: z.string().nullable(),
	title: z.string().nullable(),
	videoUrl: z.string().nullable(),
	availableLanguages: z.array(z.string()),
});
