// Generated by ts-to-zod
import { octo_AvailabilityCalendarErrorResponseSchema } from "./Octo_AvailabilityCalendarErrorResponse";

export const availabilityCalendarErrorResponseSchema = octo_AvailabilityCalendarErrorResponseSchema;
