// Generated by ts-to-zod
import { z } from 'zod';
import { availabilityStatusSchema } from './AvailabilityStatus';
import { openingHoursSchema } from './OpeningHours';
import { pickupPointSchema } from './PickupPoint';
import { pricingUnitSchema } from './PricingUnit';
import { pricingSchema } from './Pricing';
import { offerSchema } from './Offer';
import { tourGroupSchema } from './TourGroup';
import { noticeSchema } from './Notice';
import { extraPricingSchema } from './ExtraPricing';

export const availabilitySchema = z.object({
	id: z.string(),
	localDateTimeStart: z.string(),
	localDateTimeEnd: z.string(),
	utcCutoffAt: z.string(),
	allDay: z.boolean(),
	available: z.boolean(),
	status: availabilityStatusSchema,
	vacancies: z.number().nullable(),
	capacity: z.number().nullable(),
	maxUnits: z.number().nullable(),
	openingHours: z.array(openingHoursSchema),
	code: z.string().nullable(),
	totalCapacity: z.number().nullable(),
	limitCapacity: z.number().nullable(),
	limitPaxCount: z.number(),
	noShows: z.number(),
	totalNoShows: z.number(),
	totalPaxCount: z.number(),
	paxCount: z.number(),
	maxPaxCount: z.number().nullable(),
	pickupAvailable: z.boolean().optional(),
	pickupRequired: z.boolean().optional(),
	pickupPoints: z.array(pickupPointSchema).optional(),
	unitPricing: z.array(pricingUnitSchema).optional(),
	pricing: pricingSchema.optional(),
	offerCode: z.string().optional().nullable(),
	offerTitle: z.string().optional().nullable(),
	offers: z.array(offerSchema).optional(),
	offer: offerSchema.optional().nullable(),
	meetingPoint: z.string().optional().nullable(),
	meetingPointCoordinates: z.string().optional().nullable(),
	meetingPointDirections: z.string().optional().nullable(),
	meetingPointLatitude: z.number().optional().nullable(),
	meetingPointLongitude: z.number().optional().nullable(),
	meetingLocalDateTime: z.string().optional().nullable(),
	tourGroup: tourGroupSchema.optional().nullable(),
	fare: z.any().optional(),
	notices: z.array(noticeSchema).optional(),
	extraPricing: z.array(extraPricingSchema).optional(),
	hasResources: z.boolean().optional(),
});
