// Generated by ts-to-zod
import { z } from 'zod';
import { availabilityCheckBodySchema } from './AvailabilityCheckBody';

export const availabilityCheckRequestSchema = z.object({
	body: availabilityCheckBodySchema,
});
