// Generated by ts-to-zod
import { octo_AvailabilityCheckErrorResponseSchema } from './Octo_AvailabilityCheckErrorResponse';

export const availabilityCheckErrorResponseSchema = octo_AvailabilityCheckErrorResponseSchema;
