// Generated by ts-to-zod
import { z } from 'zod';
import { resourceSchema } from './Resource';
import { sellerSchema } from './Seller';
import { seatSchema } from './Seat';
import { availabilityStatusSchema } from './AvailabilityStatus';

export const availabilityResourceSchema = z.object({
	resourceId: z.string(),
	resource: resourceSchema,
	driver: sellerSchema.nullable(),
	guide: sellerSchema.nullable(),
	availableSeats: z.array(seatSchema),
	selectedSeats: z.array(seatSchema),
	available: z.boolean(),
	status: availabilityStatusSchema,
	statusMessage: z.string(),
	statusCode: z.string(),
	vacancies: z.number().nullable(),
	capacity: z.number().nullable(),
	maxUnits: z.number().nullable(),
	totalCapacity: z.number().nullable(),
	limitCapacity: z.number().nullable(),
	limitPaxCount: z.number(),
	maxPaxCount: z.number().nullable(),
	noShows: z.number(),
	paxCount: z.number(),
	totalNoShows: z.number(),
	totalPaxCount: z.number(),
});
