// Generated by ts-to-zod
import * as z from 'zod';
import { resourceGroupSchema } from './ResourceGroup';
import { availabilityResourceSchema } from './AvailabilityResource';

export const availabilityResourceGroupSchema = z.object({
	resourceGroupId: z.string(),
	resourceGroup: resourceGroupSchema,
	resources: z.array(availabilityResourceSchema),
});
