// Generated by ts-to-zod
import { availabilityCalendarErrorResponseSchema } from './AvailabilityCalendarErrorResponse';

export const availabilityCalendarBatchErrorResponseSchema = availabilityCalendarErrorResponseSchema;
