// Generated by ts-to-zod
import { z } from 'zod';

export const availabilityCheckQueryParamsSchema = z.object({
	productId: z.string(),
	optionId: z.string().optional(),
	uuid: z.string().optional(),
	localTime: z.string().optional(),
	localDate: z.string().optional(),
	localDateStart: z.string().optional(),
	localDateEnd: z.string().optional(),
	availabilityIds: z.array(z.string()).optional(),
});
