// Generated by ts-to-zod
import { z } from "zod";
import { availabilityCalendarBodySchema } from "./AvailabilityCalendarBody";

export const availabilityCalendarRequestSchema = z.object({
    body: availabilityCalendarBodySchema
});
