// Generated by ts-to-zod
import { z } from 'zod';
import { pricingUnitSchema } from './PricingUnit';
import { pricingSchema } from './Pricing';

export const availabilityCalendarPricingSchema = z.object({
	unitPricingFrom: z.array(pricingUnitSchema).optional(),
	pricingFrom: pricingSchema.optional(),
});
