// Generated by ts-to-zod
import * as z from 'zod';

export const availabilityResourcesQueryParamsSchema = z.object({
	productId: z.string(),
	optionId: z.string().optional(),
	availabilityId: z.string(),
});
