// Generated by ts-to-zod
import { z } from 'zod';
import { availabilityStatusSchema } from './AvailabilityStatus';
import { openingHoursSchema } from './OpeningHours';
import { pricingUnitSchema } from './PricingUnit';
import { pricingSchema } from './Pricing';
import { offerSchema } from './Offer';
import { extraPricingSchema } from './ExtraPricing';

export const availabilityCalendarSchema = z.object({
	localDate: z.string(),
	available: z.boolean(),
	status: availabilityStatusSchema,
	vacancies: z.number().nullable(),
	capacity: z.number().nullable(),
	openingHours: z.array(openingHoursSchema),
	limitCapacity: z.number().nullable(),
	totalCapacity: z.number().nullable(),
	limitPaxCount: z.number(),
	totalPaxCount: z.number(),
	paxCount: z.number(),
	utcCutoffAt: z.string(),
	availabilityLocalStartTimes: z.array(z.string()),
	unitPricingFrom: z.array(pricingUnitSchema).optional(),
	pricingFrom: pricingSchema.optional(),
	offerCode: z.string().optional().nullable(),
	offerTitle: z.string().optional().nullable(),
	offers: z.array(offerSchema).optional(),
	offer: offerSchema.optional().nullable(),
	extraPricingFrom: z.array(extraPricingSchema).optional(),
});
