// Generated by ts-to-zod
import { z } from "zod";
import { tourGroupSchema } from "./TourGroup";
import { noticeSchema } from "./Notice";

export const availabilityContentSchema = z.object({
    meetingPoint: z.string().optional(),
    meetingPointCoordinates: z.array(z.number()).optional(),
    meetingPointLatitude: z.number().optional(),
    meetingPointLongitude: z.number().optional(),
    meetingLocalDateTime: z.string().optional(),
    tourGroup: tourGroupSchema.optional(),
    notices: z.array(noticeSchema).optional()
});
