// Generated by ts-to-zod
import { z } from 'zod';
import { pricingUnitSchema } from './PricingUnit';
import { pricingSchema } from './Pricing';

export const availabilityPricingSchema = z.object({
	unitPricing: z.array(pricingUnitSchema).optional(),
	pricing: pricingSchema.optional(),
});
