// Generated by ts-to-zod
import { z } from "zod";
import { unitTypeSchema } from "./UnitType";

export const availabilityUnitSchema = z.object({
    id: z.string().optional(),
    type: unitTypeSchema.optional(),
    quantity: z.number()
});
