// Generated by ts-to-zod
import { z } from 'zod';
import { tourGroupSchema } from './TourGroup';
import { fareSchema } from './Fare';
import { noticeSchema } from './Notice';

export const availabilityContentSchema = z.object({
	meetingPoint: z.string().optional().nullable(),
	meetingPointCoordinates: z.string().optional().nullable(),
	meetingPointDirections: z.string().optional().nullable(),
	meetingPointLatitude: z.number().optional().nullable(),
	meetingPointLongitude: z.number().optional().nullable(),
	meetingLocalDateTime: z.string().optional().nullable(),
	tourGroup: tourGroupSchema.optional().nullable(),
	fare: fareSchema.optional().nullable(),
	notices: z.array(noticeSchema).optional(),
});
