// Generated by ts-to-zod
import { z } from 'zod';
import { availabilityUnitSchema } from './AvailabilityUnit';

export const availabilityCalendarBodySchema = z.object({
	productId: z.string(),
	optionId: z.string(),
	localDateStart: z.string().optional(),
	localDateEnd: z.string().optional(),
	units: z.array(availabilityUnitSchema).optional(),
	currency: z.string().optional(),
});
