// Generated by ts-to-zod
import { z } from 'zod';
import { offerSchema } from './Offer';

export const availabilityOffersSchema = z.object({
	offerCode: z.string().optional().nullable(),
	offerTitle: z.string().optional().nullable(),
	offers: z.array(offerSchema).optional(),
	offer: offerSchema.optional().nullable(),
});
