// Generated by ts-to-zod
import { z } from 'zod';
import { uuidSchema } from './UUID';

export const availabilityCalendarBatchBodySchema = z.object({
	productId: z.string().optional(),
	productIds: z.array(uuidSchema).optional(),
	localDateStart: z.string(),
	localDateEnd: z.string(),
});
