// Generated by ts-to-zod
import { z } from 'zod';
import { pricingSchema } from './Pricing';
import { pricingUnitSchema } from './PricingUnit';

export const availabilityPricingSchema = z.object({
	unitPricing: z.array(pricingUnitSchema).optional(),
	pricing: z.array(pricingSchema).optional(),
});
