// Generated by ts-to-zod
import { z } from 'zod';
import { pickupPointSchema } from './PickupPoint';
import { dropoffPointSchema } from './DropoffPoint';

export const availabilityPickupsSchema = z.object({
	pickupAvailable: z.boolean().optional(),
	pickupRequired: z.boolean().optional(),
	pickupPoints: z.array(pickupPointSchema).optional(),
	dropoffAvailable: z.boolean().optional(),
	dropoffRequired: z.boolean().optional(),
	dropoffPoints: z.array(dropoffPointSchema).optional(),
});
