// Generated by ts-to-zod
import { z } from 'zod';
import { webhookSchema } from './Webhook';
import { availabilitySchema } from './Availability';
import { supplierSchema } from './Supplier';

export const availabilityUpdateSchema = z.object({
	webhook: webhookSchema,
	availability: availabilitySchema,
	productId: z.string(),
	optionId: z.string(),
	supplier: supplierSchema,
});
