// Generated by ts-to-zod
import * as z from 'zod';
import { extraPricingSchema } from './ExtraPricing';

export const availabilityExtrasSchema = z.object({
	extraPricing: z.array(extraPricingSchema).optional(),
});
