// Generated by ts-to-zod
import { z } from 'zod';
import { extraPricingSchema } from './ExtraPricing';

export const availabilityCalendarExtrasSchema = z.object({
	extraPricingFrom: z.array(extraPricingSchema).optional(),
});
