// Generated by ts-to-zod
import { z } from 'zod';
import { availabilityStatusSchema } from './AvailabilityStatus';
import { openingHoursSchema } from './OpeningHours';
import { pricingUnitSchema } from './PricingUnit';
import { pricingSchema } from './Pricing';
import { offerSchema } from './Offer';
import { extraPricingSchema } from './ExtraPricing';

export const availabilityCalendarSchema = z.object({
	localDate: z.string(),
	localDateTimeStart: z.string().nullable(),
	localDateTimeEnd: z.string().nullable(),
	available: z.boolean(),
	status: availabilityStatusSchema,
	statusCode: z.string(),
	statusMessage: z.string(),
	vacancies: z.number().nullable(),
	capacity: z.number().nullable(),
	openingHours: z.array(openingHoursSchema),
	productId: z.string().optional(),
	optionId: z.string().optional(),
	limitCapacity: z.number().nullable(),
	totalCapacity: z.number().nullable(),
	totalMaxWeight: z.number().nullable(),
	totalPaxWeight: z.number(),
	paxWeight: z.number(),
	maxWeight: z.number().nullable(),
	weightUnit: z.string().nullable(),
	availableWeight: z.number().nullable(),
	limitPaxCount: z.number(),
	noShows: z.number(),
	totalNoShows: z.number(),
	totalPaxCount: z.number(),
	maxUnits: z.number().nullable(),
	maxPaxCount: z.number().nullable(),
	paxCount: z.number(),
	utcCutoffAt: z.string(),
	utcOnsaleAt: z.string().nullable(),
	availabilityLocalStartTimes: z.array(z.string()),
	unitPricingFrom: z.array(pricingUnitSchema).optional(),
	pricingFrom: pricingSchema.optional(),
	offerCode: z.string().optional().nullable(),
	offerTitle: z.string().optional().nullable(),
	offers: z.array(offerSchema).optional(),
	offer: offerSchema.optional().nullable(),
	extraPricingFrom: z.array(extraPricingSchema).optional(),
});
