// Generated by ts-to-zod
import * as z from 'zod';
import { packageAvailabilitySchema } from './PackageAvailability';

export const availabilityPackagesSchema = z.object({
	packageAvailabilities: z.array(packageAvailabilitySchema).optional(),
});
