// Generated by ts-to-zod
import { z } from 'zod';

export const bookingPickupBodySchema = z.object({
	pickupRequested: z.boolean().optional(),
	pickupPointId: z.string().optional(),
	pickupHotel: z.string().optional(),
	pickupHotelRoom: z.string().optional(),
});
