// Generated by ts-to-zod
import { z } from 'zod';
import { octo_BookingCancellationBodySchema } from './Octo_BookingCancellationBody';

export const bookingCancellationBodySchema = octo_BookingCancellationBodySchema.and(
	z.object({
		emailReceipt: z.boolean().optional(),
	}),
);
