// Generated by ts-to-zod
import { z } from "zod";
import { refundSchema } from "./Refund";

export const bookingCancellationSchema = z.object({
    refund: refundSchema,
    reason: z.string().nullable(),
    utcCancelledAt: z.string()
});
