// Generated by ts-to-zod
import { z } from 'zod';
import { bookingConfirmationBodySchema } from './BookingConfirmationBody';
import { octo_BookingConfirmationRequestSchema } from './Octo_BookingConfirmationRequest';

export const bookingConfirmationRequestSchema = octo_BookingConfirmationRequestSchema.and(
	z.object({
		body: bookingConfirmationBodySchema,
	}),
);
