// Generated by ts-to-zod
import * as z from 'zod';
import { questionAnswerSchema } from './QuestionAnswer';

export const bookingQuestionsSchema = z.object({
	questionAnswers: z.array(questionAnswerSchema).optional(),
});
