// Generated by ts-to-zod
import * as z from 'zod';

export const bookingCartSchema = z.object({
	primary: z.boolean().optional(),
	orderId: z.string().optional(),
	orderReference: z.string().optional(),
});
