// Generated by ts-to-zod
import { z } from 'zod';

export const bookingCheckinSchema = z.object({
	checkedIn: z.boolean().optional(),
	checkinAvailable: z.boolean().optional(),
	checkinUrl: z.string().optional().nullable(),
});
