// Generated by ts-to-zod
import { z } from "zod";
import { pickupPointSchema } from "./PickupPoint";

export const bookingPickupsSchema = z.object({
    pickupRequested: z.boolean().optional(),
    pickupId: z.string().optional().nullable(),
    pickupHotel: z.string().optional().nullable(),
    pickupRoom: z.string().optional().nullable(),
    pickupNotes: z.string().optional().nullable(),
    pickupPoint: pickupPointSchema.optional().nullable()
});
