// Generated by ts-to-zod
import { octo_BookingReservationErrorResponseSchema } from "./Octo_BookingReservationErrorResponse";

export const bookingReservationErrorResponseSchema = octo_BookingReservationErrorResponseSchema;
