// Generated by ts-to-zod
import { z } from 'zod';
import { adjustmentDiscountSchema } from './AdjustmentDiscount';
import { adjustmentPerSchema } from './AdjustmentPer';

export const bookingAdjustmentSchema = z.object({
	per: adjustmentPerSchema,
	amount: z.number(),
	notes: z.string().nullable(),
	netDiscount: adjustmentDiscountSchema,
});
