// Generated by ts-to-zod
import { z } from 'zod';
import { bookingSchema } from './Booking';
import { includeSchema } from './Include';

export const bookingPackagesSchema = z.object({
	isPackage: z.boolean().optional(),
	packageIncludeId: z.string().optional(),
	packageInclude: includeSchema.optional().nullable(),
	packageBookings: z.array(bookingSchema).optional(),
});
