// Generated by ts-to-zod
import { octo_BookingCancellationErrorResponseSchema } from "./Octo_BookingCancellationErrorResponse";

export const bookingCancellationErrorResponseSchema = octo_BookingCancellationErrorResponseSchema;
