// Generated by ts-to-zod
import * as z from 'zod';
import { giftPaymentSchema } from './GiftPayment';

export const bookingGiftsSchema = z.object({
	giftPayment: giftPaymentSchema.optional().nullable(),
});
