// Generated by ts-to-zod
import { z } from 'zod';
import { unitItemIdentifierSchema } from './UnitItemIdentifier';
import { bookingContactSchema } from './BookingContact';
import { settlementMethodSchema } from './SettlementMethod';

export const bookingReservationBodySchema = z.object({
	resellerReference: z.string().optional(),
	productId: z.string(),
	optionId: z.string(),
	availabilityId: z.string().optional(),
	expirationMinutes: z.number().optional(),
	notes: z.string().optional(),
	emailReceipt: z.boolean().optional(),
	unitItems: z.array(unitItemIdentifierSchema),
	contact: bookingContactSchema.optional(),
	currency: z.string().optional(),
	alias: z.string().optional(),
	settlementMethod: settlementMethodSchema.optional(),
	quote: z.boolean().optional(),
	freesale: z.boolean().optional(),
	redeemed: z.boolean().optional(),
	uuid: z.string().optional(),
	tags: z.array(z.string()).optional(),
	orderId: z.string().optional(),
	metadata: z.record(z.string()).optional(),
	pickupRequested: z.boolean().optional(),
	pickupPointId: z.string().optional(),
	pickupHotel: z.string().optional(),
	pickupHotelRoom: z.string().optional(),
});
