// Generated by ts-to-zod
import { z } from 'zod';
import { resourceAllocationRequestSchema } from './ResourceAllocationRequest';

export const bookingResourcesBodySchema = z.object({
	resourceAllocations: z.array(resourceAllocationRequestSchema).optional(),
});
