// Generated by ts-to-zod
import { z } from "zod";
import { bookingReservationBodySchema } from "./BookingReservationBody";

export const bookingReservationRequestSchema = z.object({
    body: bookingReservationBodySchema
});
