// Generated by ts-to-zod
import { z } from 'zod';
import { extraItemSchema } from './ExtraItem';
import { extraPricingSchema } from './ExtraPricing';

export const bookingExtrasSchema = z.object({
	extraItems: z.array(extraItemSchema).optional(),
	extraPricing: z.array(extraPricingSchema).optional(),
});
