// Generated by ts-to-zod
import { z } from 'zod';
import { bookingStatusSchema } from './BookingStatus';
import { productSchema } from './Product';
import { optionSchema } from './Option';
import { bookingCancellationSchema } from './BookingCancellation';
import { availabilitySchema } from './Availability';
import { customerContactSchema } from './CustomerContact';
import { deliveryMethodSchema } from './DeliveryMethod';
import { ticketSchema } from './Ticket';
import { unitItemSchema } from './UnitItem';
import { pricingSchema } from './Pricing';
import { settlementMethodSchema } from './SettlementMethod';
import { agentSchema } from './Agent';
import { resellerSchema } from './Reseller';
import { contactFieldSchema } from './ContactField';
import { bookingRejectionSchema } from './BookingRejection';
import { userSchema } from './User';
import { sellerSchema } from './Seller';
import { labelSchema } from './Label';
import { pickupPointSchema } from './PickupPoint';
import { durationUnitSchema } from './DurationUnit';
import { noticeSchema } from './Notice';
import { offerComparisonSchema } from './OfferComparison';
import { offerSchema } from './Offer';
import { questionAnswerSchema } from './QuestionAnswer';
import { resourceAllocationSchema } from './ResourceAllocation';
import { giftPaymentSchema } from './GiftPayment';
import { extraItemSchema } from './ExtraItem';
import { includeSchema } from './Include';
import { bookingAdjustmentSchema } from './BookingAdjustment';
import { identitySchema } from './Identity';

import { type Booking } from '../models/Booking';

export const bookingSchema: z.ZodSchema<Booking> = z.lazy(() =>
	z.object({
		id: z.string(),
		uuid: z.string(),
		testMode: z.boolean(),
		resellerReference: z.string().nullable(),
		supplierReference: z.string().nullable(),
		status: bookingStatusSchema,
		utcCreatedAt: z.string(),
		utcUpdatedAt: z.string(),
		utcExpiresAt: z.string().nullable(),
		utcRedeemedAt: z.string().nullable(),
		utcConfirmedAt: z.string().nullable(),
		productId: z.string(),
		product: productSchema.optional(),
		optionId: z.string(),
		option: optionSchema.optional(),
		cancellable: z.boolean(),
		cancellation: bookingCancellationSchema.nullable(),
		freesale: z.boolean(),
		availabilityId: z.string().nullable(),
		availability: availabilitySchema.optional().nullable(),
		contact: customerContactSchema.optional(),
		notes: z.string().nullable(),
		deliveryMethods: z.array(deliveryMethodSchema),
		voucher: ticketSchema.nullable(),
		unitItems: z.array(unitItemSchema),
		pricing: pricingSchema.optional(),
		rebookingUuid: z.string().nullable(),
		originalRebookingUuid: z.string().nullable(),
		alias: z.string().nullable(),
		settlementMethod: settlementMethodSchema,
		quote: z.boolean(),
		confirmable: z.boolean(),
		agent: agentSchema.nullable(),
		reseller: resellerSchema.nullable(),
		requiredContactFields: z.array(contactFieldSchema),
		visibleContactFields: z.array(contactFieldSchema),
		rejection: bookingRejectionSchema.nullable(),
		utcNoshowedAt: z.string().nullable(),
		utcRebookedAt: z.string().nullable(),
		tags: z.array(z.string()).optional(),
		user: userSchema.nullable(),
		seller: sellerSchema.nullable(),
		localDateTimeStart: z.string(),
		localDateTimeEnd: z.string(),
		emailReceipt: z.boolean(),
		label: labelSchema.nullable(),
		pickupRequested: z.boolean().optional(),
		pickupId: z.string().optional().nullable(),
		pickupHotel: z.string().optional().nullable(),
		pickupRoom: z.string().optional().nullable(),
		pickupNotes: z.string().optional().nullable(),
		pickupPoint: pickupPointSchema.optional().nullable(),
		duration: z.string().optional(),
		durationAmount: z.number().optional(),
		durationUnit: durationUnitSchema.optional(),
		meetingLocalDateTime: z.string().optional().nullable(),
		meetingPoint: z.string().optional().nullable(),
		meetingPointCoordinates: z.string().optional().nullable(),
		notices: z.array(noticeSchema).optional(),
		termsAccepted: z.boolean().optional(),
		primary: z.boolean().optional(),
		orderId: z.string().optional(),
		orderReference: z.string().optional(),
		offerCode: z.string().optional().nullable(),
		offerTitle: z.string().optional().nullable(),
		offerComparisons: z.array(offerComparisonSchema).optional(),
		offerIsCombination: z.boolean().optional(),
		offers: z.array(offerSchema).optional(),
		offer: offerSchema.optional().nullable(),
		questionAnswers: z.array(questionAnswerSchema).optional(),
		resourceAllocations: z.array(resourceAllocationSchema).optional(),
		giftPayment: giftPaymentSchema.optional().nullable(),
		extraItems: z.array(extraItemSchema).optional(),
		isPackage: z.boolean().optional(),
		packageIncludeId: z.string().optional(),
		packageInclude: includeSchema.optional().nullable(),
		packageBookings: z.array(bookingSchema).optional(),
		adjustments: z.array(bookingAdjustmentSchema).optional(),
		identity: identitySchema.optional(),
		identityId: z.string().optional(),
	}),
);
