// Generated by ts-to-zod
import { z } from "zod";
import { unitItemIdentifierSchema } from "./UnitItemIdentifier";
import { bookingContactSchema } from "./BookingContact";

export const bookingConfirmationBodySchema = z.object({
    emailReceipt: z.boolean().optional(),
    resellerReference: z.string().optional(),
    unitItems: z.array(unitItemIdentifierSchema),
    contact: bookingContactSchema
});
