// Generated by ts-to-zod
import { octo_BookingConfirmationErrorResponseSchema } from "./Octo_BookingConfirmationErrorResponse";

export const bookingConfirmationErrorResponseSchema = octo_BookingConfirmationErrorResponseSchema;
