// Generated by ts-to-zod
import { z } from 'zod';
import { membershipBenefitSchema } from './MembershipBenefit';
import { membershipSchema } from './Membership';

export const bookingMembershipsSchema = z.object({
	membershipBenefit: membershipBenefitSchema.optional().nullable(),
	membership: membershipSchema.optional().nullable(),
	isMembership: z.boolean().optional(),
	appendMembershipValidity: z.boolean().optional(),
});
