// Generated by ts-to-zod
import { z } from "zod";
import { adjustmentPerSchema } from "./AdjustmentPer";
import { adjustmentDiscountSchema } from "./AdjustmentDiscount";

export const bookingAdjustmentSchema = z.object({
    per: adjustmentPerSchema,
    amount: z.number(),
    notes: z.string().nullable(),
    netDiscount: adjustmentDiscountSchema
});
