// Generated by ts-to-zod
import * as z from 'zod';
import { resourceAllocationSchema } from './ResourceAllocation';

export const bookingResourcesSchema = z.object({
	resourceAllocations: z.array(resourceAllocationSchema).optional(),
});
