// Generated by ts-to-zod
import { z } from 'zod';
import { webhookSchema } from './Webhook';
import { bookingSchema } from './Booking';
import { diffSchema } from './Diff';
import { supplierSchema } from './Supplier';

export const bookingUpdateSchema = z.object({
	webhook: webhookSchema,
	booking: bookingSchema,
	diff: z.array(diffSchema),
	supplier: supplierSchema,
});
