// Generated by ts-to-zod
import { z } from 'zod';
import { offerSchema } from './Offer';
import { offerComparisonSchema } from './OfferComparison';

export const bookingOffersSchema = z.object({
	offerCode: z.string().optional().nullable(),
	offerTitle: z.string().optional().nullable(),
	offerComparisons: z.array(offerComparisonSchema).optional(),
	offerIsCombination: z.boolean().optional(),
	offers: z.array(offerSchema).optional(),
	offer: offerSchema.optional().nullable(),
});
