// Generated by ts-to-zod
import { z } from 'zod';
import { bookingContactSchema } from './BookingContact';
import { unitItemIdentifierSchema } from './UnitItemIdentifier';

export const bookingConfirmationBodySchema = z.object({
	emailReceipt: z.boolean().optional(),
	resellerReference: z.string().optional(),
	unitItems: z.array(unitItemIdentifierSchema),
	contact: bookingContactSchema,
});
