// Generated by ts-to-zod
import { z } from 'zod';
import { unitItemIdentifierSchema } from './UnitItemIdentifier';
import { bookingContactSchema } from './BookingContact';
import { settlementMethodSchema } from './SettlementMethod';
import { resourceAllocationRequestSchema } from './ResourceAllocationRequest';

export const bookingUpdateBodySchema = z.object({
	resellerReference: z.string().optional(),
	productId: z.string().optional(),
	optionId: z.string().optional(),
	availabilityId: z.string().optional(),
	expirationMinutes: z.number().optional(),
	notes: z.string().optional(),
	emailReceipt: z.boolean().optional(),
	unitItems: z.array(unitItemIdentifierSchema).optional(),
	contact: bookingContactSchema.optional(),
	alias: z.string().optional(),
	settlementMethod: settlementMethodSchema.optional(),
	quote: z.boolean().optional(),
	freesale: z.boolean().optional(),
	redeemed: z.boolean().optional(),
	uuid: z.string().optional(),
	tags: z.array(z.string()).optional(),
	meta: z.record(z.string()).optional(),
	pickupRequested: z.boolean().optional(),
	pickupPointId: z.string().optional(),
	pickupHotel: z.string().optional(),
	pickupHotelRoom: z.string().optional(),
	termsAccepted: z.boolean().optional(),
	offerCode: z.string().optional(),
	resourceAllocations: z.array(resourceAllocationRequestSchema).optional(),
});
