// Generated by ts-to-zod
import { z } from "zod";

export const bookingContactSchema = z.object({
    fullName: z.string().optional(),
    firstName: z.string().optional(),
    lastName: z.string().optional(),
    emailAddress: z.string().optional(),
    phoneNumber: z.string().optional(),
    locales: z.array(z.string()).optional(),
    postalCode: z.string().optional(),
    country: z.string().optional(),
    notes: z.string().optional(),
    taxId: z.string().optional().nullable(),
    streetAddress: z.string().optional().nullable(),
    city: z.string().optional().nullable(),
    state: z.string().optional().nullable(),
    allowMarketing: z.boolean().optional()
});
