// Generated by ts-to-zod
import { z } from 'zod';
import { unitItemIdentifierSchema } from './UnitItemIdentifier';
import { bookingContactSchema } from './BookingContact';
import { settlementMethodSchema } from './SettlementMethod';

export const bookingUpdateBodySchema = z.object({
	resellerReference: z.string().optional(),
	productId: z.string().optional(),
	optionId: z.string().optional(),
	availabilityId: z.string().optional(),
	expirationMinutes: z.number().optional(),
	notes: z.string().optional(),
	emailReceipt: z.boolean().optional(),
	unitItems: z.array(unitItemIdentifierSchema).optional(),
	contact: bookingContactSchema.optional(),
	alias: z.string().optional(),
	settlementMethod: settlementMethodSchema.optional(),
	quote: z.boolean().optional(),
	freesale: z.boolean().optional(),
	redeemed: z.boolean().optional(),
	uuid: z.string().optional(),
	tags: z.array(z.string()).optional(),
});
