// Generated by ts-to-zod
import { z } from 'zod';

export const bookingCancellationBodySchema = z.object({
	reason: z.string().optional(),
	force: z.boolean().optional(),
	emailReceipt: z.boolean().optional(),
});
