// Generated by ts-to-zod
import { z } from 'zod';
import { bookingCancellationBodySchema } from './BookingCancellationBody';
import { octo_BookingCancellationRequestSchema } from './Octo_BookingCancellationRequest';

export const bookingCancellationRequestSchema = octo_BookingCancellationRequestSchema.and(
	z.object({
		body: bookingCancellationBodySchema,
	}),
);
