// Generated by ts-to-zod
import { z } from 'zod';
import { bookingUpdateBodySchema } from './BookingUpdateBody';

export const bookingUpdateRequestSchema = z.object({
	body: bookingUpdateBodySchema,
});
