// Generated by ts-to-zod
import { z } from "zod";
import { durationUnitSchema } from "./DurationUnit";
import { noticeSchema } from "./Notice";

export const bookingContentSchema = z.object({
    duration: z.string().optional(),
    durationAmount: z.number().optional(),
    durationUnit: durationUnitSchema.optional(),
    meetingLocalDateTime: z.string().optional().nullable(),
    meetingPoint: z.string().optional().nullable(),
    meetingPointCoordinates: z.string().optional().nullable(),
    notices: z.array(noticeSchema).optional(),
    termsAccepted: z.boolean().optional()
});
