// Generated by ts-to-zod
import { z } from "zod";
import { octo_BookingCancellationRequestSchema } from "./Octo_BookingCancellationRequest";
import { bookingCancellationBodySchema } from "./BookingCancellationBody";

export const bookingCancellationRequestSchema = octo_BookingCancellationRequestSchema.and(z.object({
    body: bookingCancellationBodySchema
}));
