// Generated by ts-to-zod
import { z } from 'zod';
import { rentalDurationSchema } from './RentalDuration';

export const bookingRentalsSchema = z.object({
	isRental: z.boolean().optional(),
	rentalDurationId: z.string().optional().nullable(),
	rentalDuration: rentalDurationSchema.optional().nullable(),
});
