// Generated by ts-to-zod
import { z } from "zod";
import { bookingAdjustmentSchema } from "./BookingAdjustment";

export const bookingAdjustmentsSchema = z.object({
    adjustments: z.array(bookingAdjustmentSchema).optional()
});
