// Generated by ts-to-zod
import { z } from 'zod';
import { brandContactSchema } from './BrandContact';
import { fontSchema } from './Font';

export const brandSchema = z.object({
	id: z.string().nullable(),
	name: z.string().nullable(),
	contact: brandContactSchema.nullable(),
	color: z.string().nullable(),
	secondaryColor: z.string().nullable(),
	backgroundColor: z.string().nullable(),
	accentFont: fontSchema.nullable(),
	bodyFont: fontSchema.nullable(),
	headerFont: fontSchema.nullable(),
	checkoutLogoUrl: z.string().nullable(),
	logoUrl: z.string().nullable(),
	logoWhiteUrl: z.string().nullable(),
	faviconUrl: z.string().nullable(),
});
