// Generated by ts-to-zod
import { z } from 'zod';

export const brandVentrataCheckoutContentSchema = z.object({
	headerBackgroundColor: z.string().optional(),
	footerBackgroundColor: z.string().optional(),
});
