// Generated by ts-to-zod
import { z } from 'zod';
import { CancellationCutoffUnit } from '../models/CancellationCutoffUnit';

export const cancellationCutoffUnitSchema = z.nativeEnum(CancellationCutoffUnit);
