// Generated by ts-to-zod
import { z } from 'zod';
import { refundSchema } from './Refund';

export const cancellationSchema = z.object({
	refund: refundSchema,
	reason: z.string().nullable(),
	utcCancelledAt: z.string(),
});
