// Generated by ts-to-zod
import { z } from 'zod';

export const cardSchema = z.object({
	id: z.string(),
	brand: z.string(),
	bin: z.string(),
	last4: z.string(),
	expMonth: z.number(),
	expYear: z.number(),
});
