// Generated by ts-to-zod
import { z } from 'zod';
import { externalGatewayRequestSchema } from './ExternalGatewayRequest';
import { paypalGatewayRequestSchema } from './PaypalGatewayRequest';

export const cardPaymentSchema = z.object({
	amount: z.number().nullable(),
	cancel: z.boolean().optional().nullable(),
	cardId: z.string().nullable(),
	currency: z.string().nullable(),
	external: externalGatewayRequestSchema.nullable(),
	gateway: z.string().nullable(),
	notes: z.string().optional().nullable(),
	paypal: paypalGatewayRequestSchema.nullable(),
});
