// Generated by ts-to-zod
import { z } from 'zod';
import { cardSchema } from './Card';
import { adyenGatewaySchema } from './AdyenGateway';
import { vivawalletGatewaySchema } from './VivawalletGateway';
import { stripeGatewaySchema } from './StripeGateway';
import { bridgepayGatewaySchema } from './BridgepayGateway';
import { realaxGatewaySchema } from './RealaxGateway';
import { paypalGatewaySchema } from './PaypalGateway';
import { externalGatewaySchema } from './ExternalGateway';
import { paytrGatewaySchema } from './PaytrGateway';
import { spreedlyGatewaySchema } from './SpreedlyGateway';
import { peachGatewaySchema } from './PeachGateway';

export const cardPaymentSchema = z.object({
	id: z.string(),
	gateway: z.string(),
	source: z.string(),
	paid: z.number(),
	paidSurcharge: z.number(),
	balance: z.number(),
	surcharge: z.number(),
	outstandingBalance: z.number(),
	currency: z.string(),
	currencyPrecision: z.number(),
	reusableCards: z.array(cardSchema),
	adyen: adyenGatewaySchema.optional(),
	vivawallet: vivawalletGatewaySchema.optional(),
	stripe: stripeGatewaySchema.optional(),
	bridgepay: bridgepayGatewaySchema.optional(),
	realax: realaxGatewaySchema.optional(),
	paypal: paypalGatewaySchema.optional(),
	external: externalGatewaySchema.optional(),
	paytr: paytrGatewaySchema.optional(),
	spreedly: spreedlyGatewaySchema.optional(),
	peach: peachGatewaySchema.optional(),
});
