// Generated by ts-to-zod
import { z } from 'zod';

export const categoryVentrataCheckoutContentSchema = z.object({
	href: z.string().optional().nullable(),
	availableLanguages: z.array(z.string()).optional(),
	meta: z.record(z.any()).optional(),
});
