// Generated by ts-to-zod
import { z } from 'zod';
import { availableLanguagesItemSchema } from './AvailableLanguagesItem';

export const categorySchema = z.object({
	id: z.string(),
	default: z.boolean(),
	name: z.string().nullable(),
	title: z.string().nullable(),
	tags: z.array(z.string()),
	shortDescription: z.string().nullable(),
	coverImageUrl: z.string().nullable(),
	bannerImageUrl: z.string().nullable(),
	productIds: z.array(z.string()).optional(),
	href: z.string().optional().nullable(),
	availableLanguages: availableLanguagesItemSchema.optional().nullable(),
	meta: z.record(z.string(), z.string()).optional(),
});
