// Generated by ts-to-zod
import { z } from 'zod';
import { availableLanguagesSchema } from './AvailableLanguages';

export const categoryVentrataCheckoutContentSchema = z.object({
	href: z.string().optional().nullable(),
	availableLanguages: availableLanguagesSchema.optional().nullable(),
	meta: z.record(z.string()).optional(),
});
