// Generated by ts-to-zod
import { z } from 'zod';
import { giftExpiryUnitSchema } from './GiftExpiryUnit';
import { giftsRestrictionsSchema } from './GiftsRestrictions';
import { checkoutConfigPricingDisplaySchema } from './CheckoutConfigPricingDisplay';
import { resellerSchema } from './Reseller';
import { agentSchema } from './Agent';
import { destinationContactSchema } from './DestinationContact';
import { brandSchema } from './Brand';
import { categorySchema } from './Category';
import { noticeSchema } from './Notice';
import { pageSchema } from './Page';
import { articleSchema } from './Article';
import { navSchema } from './Nav';
import { claimSchema } from './Claim';
import { destinationSchema } from './Destination';
import { checkoutDomainSchema } from './CheckoutDomain';
import { checkoutSitemapEntrySchema } from './CheckoutSitemapEntry';

export const checkoutConfigSchema = z.object({
	allowedCheckinMethods: z.array(z.string()),
	conversionHtml: z.string().nullable(),
	defaultMarketingAllowed: z.boolean(),
	fingerprintPublicKey: z.string(),
	giftsAllowed: z.boolean(),
	giftsDuration: z.string(),
	giftsDurationAmount: z.number(),
	giftsDurationUnit: giftExpiryUnitSchema,
	giftsRestrictions: giftsRestrictionsSchema,
	googleAnalyticsMeasurementId: z.string().nullable(),
	googleMapsApiKey: z.string(),
	googleUniversalAnalyticsId: z.string().nullable(),
	includeTax: z.boolean(),
	loqateApiKey: z.string().nullable(),
	memberSignupUrl: z.string().nullable(),
	membersAllowed: z.boolean(),
	noindex: z.boolean(),
	postHogExperiment: z.string().nullable(),
	pricingDisplay: checkoutConfigPricingDisplaySchema,
	quotesAllowed: z.boolean(),
	recaptchaEnterpriseSiteKey: z.string().nullable(),
	segmentKey: z.string().nullable(),
	theme: z.string(),
	waitlistsAllowed: z.boolean(),
	widgetCss: z.string().nullable(),
	marketingConsent: z.boolean().nullable(),
	reseller: resellerSchema.nullable(),
	agent: agentSchema.nullable(),
	id: z.string(),
	default: z.boolean(),
	name: z.string().nullable(),
	title: z.string().nullable(),
	shortDescription: z.string().nullable(),
	featured: z.boolean(),
	country: z.string().nullable(),
	contact: destinationContactSchema,
	brand: brandSchema,
	latitude: z.number().nullable(),
	longitude: z.number().nullable(),
	googlePlaceId: z.string().nullable(),
	bannerImageUrl: z.string().nullable(),
	coverImageUrl: z.string().nullable(),
	videoUrl: z.string().nullable(),
	facebookUrl: z.string().nullable(),
	googleUrl: z.string().nullable(),
	tripadvisorUrl: z.string().nullable(),
	twitterUrl: z.string().nullable(),
	youtubeUrl: z.string().nullable(),
	instagramUrl: z.string().nullable(),
	categories: z.array(categorySchema).optional(),
	tags: z.array(z.string()),
	address: z.string().nullable(),
	notices: z.array(noticeSchema),
	defaultCurrency: z.string().optional(),
	availableCurrencies: z.array(z.string()).optional(),
	href: z.string().optional().nullable(),
	availableLanguages: z.array(z.string()).optional(),
	meta: z.record(z.any()).optional(),
	pages: z.array(pageSchema).optional(),
	articles: z.array(articleSchema).optional(),
	navs: z.array(navSchema).optional(),
	claims: z.array(claimSchema).optional(),
	featuredCategories: z.array(categorySchema).optional(),
	bodyHtml: z.string().optional().nullable(),
	destinations: z.array(destinationSchema).optional(),
	domains: z.array(checkoutDomainSchema).optional(),
	footerHtml: z.string().optional().nullable(),
	headHtml: z.string().optional().nullable(),
	legacyWidgetToken: z.string().optional().nullable(),
	redirects: z.record(z.string()).optional(),
	showFooter: z.boolean().optional(),
	showHeader: z.boolean().optional(),
	sitemap: z.record(checkoutSitemapEntrySchema).optional(),
});
