// Generated by ts-to-zod
import { z } from 'zod';
import { CheckoutConfigPricingDisplay } from '../models/CheckoutConfigPricingDisplay';

export const checkoutConfigPricingDisplaySchema = z.nativeEnum(CheckoutConfigPricingDisplay);
