// Generated by ts-to-zod
import { z } from 'zod';
import { checkoutSitemapEntryRelSchema } from './CheckoutSitemapEntryRel';

export const checkoutSitemapEntrySchema = z.object({
	id: z.string().nullable(),
	description: z.string().nullable(),
	destinationId: z.string().optional(),
	keywords: z.array(z.string()),
	language: z.string(),
	name: z.string().nullable(),
	rel: checkoutSitemapEntryRelSchema,
	title: z.string().nullable(),
});
