// Generated by ts-to-zod
import { z } from 'zod';
import { CheckoutSitemapEntryRel } from '../models/CheckoutSitemapEntryRel';

export const checkoutSitemapEntryRelSchema = z.nativeEnum(CheckoutSitemapEntryRel);
