// Generated by ts-to-zod
import * as z from 'zod';
import { bookingSchema } from './Booking';

export const checkinLookupSchema = z.object({
	message: z.string().nullable(),
	verified: z.boolean(),
	bookings: z.array(bookingSchema),
});
