// Generated by ts-to-zod
import { z } from 'zod';

export const checkinLookupBodySchema = z.object({
	page: z.number().optional(),
	email: z.string().optional(),
	mobile: z.string().optional(),
	country: z.string().optional(),
	reference: z.string().optional(),
	verification: z.string().optional(),
});
