// Generated by ts-to-zod
import * as z from 'zod';
import { CheckoutConfigPricingDisplay } from '../models/CheckoutConfigPricingDisplay';

export const checkoutConfigPricingDisplaySchema = z.enum(CheckoutConfigPricingDisplay);
