// Generated by ts-to-zod
import { z } from 'zod';
import { bookingContactSchema } from './BookingContact';

export const confirmOrderBodySchema = z.object({
	expirationMinutes: z.number().optional(),
	emailReceipt: z.boolean().optional(),
	contact: bookingContactSchema.optional(),
	currency: z.string().optional(),
});
