// Generated by ts-to-zod
import { z } from 'zod';
import { bookingReservationBodySchema } from './BookingReservationBody';
import { bookingContactSchema } from './BookingContact';
import { settlementMethodSchema } from './SettlementMethod';
import { cardPaymentSchema } from './CardPayment';
import { createGiftBodySchema } from './CreateGiftBody';

export const createOrderBodySchema = z.object({
	bookings: z.array(bookingReservationBodySchema).optional(),
	contact: bookingContactSchema.optional(),
	emailReceipt: z.boolean().optional(),
	expirationMinutes: z.number().optional(),
	quote: z.boolean().optional(),
	settlementMethod: settlementMethodSchema.optional(),
	currency: z.string().optional(),
	cardPayment: cardPaymentSchema.optional(),
	returnUrl: z.string().optional().nullable(),
	gatewayId: z.string().optional(),
	gifts: z.array(createGiftBodySchema).optional(),
	identityId: z.string().optional(),
});
