// Generated by ts-to-zod
import { z } from 'zod';
import { webhookEventSchema } from './WebhookEvent';
import { capabilityIdSchema } from './CapabilityId';

export const createWebhookBodySchema = z.object({
	url: z.string(),
	function: z.string().optional().nullable(),
	event: webhookEventSchema,
	useContactLanguage: z.boolean().optional(),
	headers: z.record(z.string(), z.string()).optional(),
	capabilities: z.array(capabilityIdSchema).optional(),
});
