// Generated by ts-to-zod
import * as z from 'zod';
import { createGiftBodySchema } from './CreateGiftBody';

export const createOrderGiftsBodySchema = z.object({
	gifts: z.array(createGiftBodySchema).optional(),
});
