// Generated by ts-to-zod
import { z } from 'zod';
import { createWebhookBodySchema } from './CreateWebhookBody';

export const createWebhookRequestSchema = z.object({
	body: createWebhookBodySchema,
});
