// Generated by ts-to-zod
import { z } from 'zod';
import { bookingContactSchema } from './BookingContact';
import { defaultableIDSchema } from './DefaultableID';
import { waitlistUnitItemIdentifierSchema } from './WaitlistUnitItemIdentifier';

export const createWaitlistRequestSchema = z.object({
	productId: z.string(),
	optionId: defaultableIDSchema,
	returnUrl: z.string().optional(),
	localDate: z.string(),
	contact: bookingContactSchema,
	units: z.array(waitlistUnitItemIdentifierSchema),
});
