// Generated by ts-to-zod
import { z } from 'zod';
import { cardPaymentSchema } from './CardPayment';

export const createOrderCardPaymentsBodySchema = z.object({
	cardPayment: cardPaymentSchema.optional(),
	returnUrl: z.string().optional().nullable(),
	gatewayId: z.string().optional(),
});
