// Generated by ts-to-zod
import { z } from 'zod';
import { createIdentityBodySchema } from './CreateIdentityBody';

export const createIdentityRequestSchema = z.object({
	body: createIdentityBodySchema,
});
