// Generated by ts-to-zod
import { z } from "zod";

export const customerContactSchema = z.object({
    fullName: z.string().nullable(),
    firstName: z.string().nullable(),
    lastName: z.string().nullable(),
    emailAddress: z.string().nullable(),
    phoneNumber: z.string().nullable(),
    locales: z.array(z.string()).nullable(),
    postalCode: z.string().nullable(),
    country: z.string().nullable(),
    notes: z.string().nullable(),
    taxId: z.string().nullable(),
    title: z.string().nullable(),
    streetAddress: z.string().nullable(),
    city: z.string().nullable(),
    state: z.string().nullable(),
    allowMarketing: z.boolean()
});
