// Generated by ts-to-zod
import * as z from 'zod';
import { deliveryFormatSchema } from './DeliveryFormat';

export const deliveryOptionSchema = z.object({
	deliveryFormat: deliveryFormatSchema,
	deliveryValue: z.string(),
});
