// Generated by ts-to-zod
import { z } from 'zod';
import { octo_DeliveryFormatSchema } from './Octo_DeliveryFormat';

export const deliveryOptionSchema = z.object({
	deliveryFormat: octo_DeliveryFormatSchema,
	deliveryValue: z.string(),
});
