// Generated by ts-to-zod
import { z } from 'zod';
import { destinationContactSchema } from './DestinationContact';
import { brandSchema } from './Brand';
import { categorySchema } from './Category';
import { noticeSchema } from './Notice';

export const destinationSchema = z.object({
	id: z.string(),
	default: z.boolean(),
	name: z.string().nullable(),
	title: z.string().nullable(),
	shortDescription: z.string().nullable(),
	featured: z.boolean(),
	country: z.string().nullable(),
	contact: destinationContactSchema,
	brand: brandSchema,
	latitude: z.number().nullable(),
	longitude: z.number().nullable(),
	googlePlaceId: z.string().nullable(),
	bannerImageUrl: z.string().nullable(),
	coverImageUrl: z.string().nullable(),
	videoUrl: z.string().nullable(),
	facebookUrl: z.string().nullable(),
	googleUrl: z.string().nullable(),
	tripadvisorUrl: z.string().nullable(),
	twitterUrl: z.string().nullable(),
	youtubeUrl: z.string().nullable(),
	instagramUrl: z.string().nullable(),
	categories: z.array(categorySchema),
	tags: z.array(z.string()),
	address: z.string().nullable(),
	notices: z.array(noticeSchema),
});
