// Generated by ts-to-zod
import { z } from 'zod';
import { pageSchema } from './Page';
import { articleSchema } from './Article';
import { navSchema } from './Nav';
import { claimSchema } from './Claim';
import { categorySchema } from './Category';

export const destinationVentrataCheckoutContentSchema = z.object({
	href: z.string().optional().nullable(),
	availableLanguages: z.array(z.string()).optional(),
	meta: z.record(z.any()).optional(),
	pages: z.array(pageSchema).optional(),
	articles: z.array(articleSchema).optional(),
	navs: z.array(navSchema).optional(),
	claims: z.array(claimSchema).optional(),
	featuredCategories: z.array(categorySchema).optional(),
});
