// Generated by ts-to-zod
import { z } from 'zod';

export const destinationPricingSchema = z.object({
	defaultCurrency: z.string().optional(),
	availableCurrencies: z.array(z.string()).optional(),
});
