// Generated by ts-to-zod
import { z } from "zod";

export const destinationContactSchema = z.object({
    name: z.string().nullable(),
    email: z.string().nullable(),
    telephone: z.string().nullable(),
    address: z.string().nullable(),
    website: z.string().nullable()
});
