// Generated by ts-to-zod
import { z } from 'zod';

export const discountTaxSchema = z.object({
	name: z.string(),
	retail: z.number(),
	net: z.number().nullable(),
	shortDescription: z.string().nullable(),
});
