// Generated by ts-to-zod
import { z } from 'zod';
import { extendReservationBodySchema } from './ExtendReservationBody';
import { octo_ExtendReservationRequestSchema } from './Octo_ExtendReservationRequest';

export const extendReservationRequestSchema = octo_ExtendReservationRequestSchema.and(
	z.object({
		body: extendReservationBodySchema,
	}),
);
