// Generated by ts-to-zod
import { octo_ExtendReservationErrorResponseSchema } from './Octo_ExtendReservationErrorResponse';

export const extendReservationErrorResponseSchema = octo_ExtendReservationErrorResponseSchema;
