// Generated by ts-to-zod
import { z } from "zod";
import { octo_ExtendReservationRequestSchema } from "./Octo_ExtendReservationRequest";
import { extendReservationBodySchema } from "./ExtendReservationBody";

export const extendReservationRequestSchema = octo_ExtendReservationRequestSchema.and(z.object({
    body: extendReservationBodySchema
}));
