// Generated by ts-to-zod
import { z } from "zod";

export const extraRestrictionsSchema = z.object({
    default: z.boolean(),
    required: z.boolean(),
    minQuantity: z.number(),
    maxQuantity: z.number().nullable()
});
