// Generated by ts-to-zod
import { z } from 'zod';
import { taxSchema } from './Tax';

export const extraPricingSchema = z.object({
	extraId: z.string(),
	original: z.number(),
	retail: z.number(),
	net: z.number().nullable(),
	currency: z.string(),
	currencyPrecision: z.number(),
	includedTaxes: z.array(taxSchema),
});
