// Generated by ts-to-zod
import { z } from 'zod';
import { unitTypeSchema } from './UnitType';

export const extraRestrictionsSchema = z.object({
	default: z.boolean(),
	required: z.boolean(),
	minAge: z.number(),
	maxAge: z.number(),
	idRequired: z.boolean(),
	minQuantity: z.number().nullable(),
	maxQuantity: z.number().nullable(),
	minCustomRetail: z.number(),
	maxCustomRetail: z.number().nullable(),
	paxCount: z.number(),
	accompaniedBy: z.array(unitTypeSchema),
	accompaniedByRatio: z.number().nullable(),
	accompaniedByRatioDenominator: z.number(),
	notAccompaniedBy: z.array(unitTypeSchema),
});
