// Generated by ts-to-zod
import { z } from 'zod';
import { extraRestrictionsSchema } from './ExtraRestrictions';
import { customRetailOptionSchema } from './CustomRetailOption';
import { pricingSchema } from './Pricing';

export const extraSchema = z.object({
	id: z.string(),
	internalName: z.string(),
	reference: z.string().nullable(),
	restrictions: extraRestrictionsSchema,
	tags: z.array(z.string()),
	customRetail: z.boolean(),
	customRetailOptions: z.array(customRetailOptionSchema),
	pricingFrom: z.array(pricingSchema).optional(),
	pricing: z.array(pricingSchema).optional(),
	title: z.string().optional().nullable(),
});
