// Generated by ts-to-zod
import { z } from "zod";
import { extraRestrictionsSchema } from "./ExtraRestrictions";
import { pricingSchema } from "./Pricing";

export const extraSchema = z.object({
    id: z.string(),
    internalName: z.string().nullable(),
    title: z.string().nullable(),
    description: z.string().nullable(),
    reference: z.string().nullable(),
    restrictions: extraRestrictionsSchema,
    pricingFrom: z.array(pricingSchema).optional(),
    pricing: z.array(pricingSchema).optional(),
    shortDescription: z.string().nullable()
});
