// Generated by ts-to-zod
import { z } from 'zod';
import { extraSchema } from './Extra';
import { pricingSchema } from './Pricing';

export const extraItemSchema = z.object({
	id: z.string(),
	extraId: z.string(),
	extra: extraSchema,
	pricing: pricingSchema,
});
