// Generated by ts-to-zod
import { z } from 'zod';
import { fareGroupSchema } from './FareGroup';
import { type Fare } from '../models/Fare';

export const fareSchema: z.ZodType<Fare> = z.object({
	id: z.string(),
	internalName: z.string(),
	title: z.string(),
	shortDescription: z.any(),
	fareGroup: fareGroupSchema.nullable(),
}) as z.ZodType<Fare>;
