// Generated by ts-to-zod
import { z } from 'zod';
import { type FareGroup } from '../models/FareGroup';

export const fareGroupSchema: z.ZodType<FareGroup> = z.object({
	id: z.string(),
	internalName: z.string(),
	title: z.string(),
	shortDescription: z.any(),
}) as z.ZodType<FareGroup>;
