// Generated by ts-to-zod
import { z } from 'zod';
import { fareGroupSchema } from './FareGroup';

export const fareSchema = z.object({
	id: z.string(),
	internalName: z.string(),
	title: z.string(),
	shortDescription: z.any(),
	fareGroup: fareGroupSchema.nullable(),
});
