// Generated by ts-to-zod
import { z } from "zod";

export const fontSchema = z.object({
    id: z.string(),
    name: z.string().nullable(),
    normalTtfUrl: z.string().nullable(),
    italicTtfUrl: z.string().nullable(),
    boldTtfUrl: z.string().nullable(),
    boldItalicTtfUrl: z.string().nullable()
});
