// Generated by ts-to-zod
import { z } from 'zod';
import { resellerStatusSchema } from './ResellerStatus';

export const getMappingsRequestSchema = z.object({
	productId: z.string().optional(),
	optionId: z.string().optional(),
	resellerReference: z.string().optional(),
	resellerStatus: resellerStatusSchema.optional(),
});
