// Generated by ts-to-zod
import { z } from 'zod';
import { octo_GetProductsRequestSchema } from './Octo_GetProductsRequest';

export const getProductsRequestSchema = octo_GetProductsRequestSchema.and(
	z.object({
		categoryId: z.string().optional(),
		destinationId: z.string().optional(),
		featured: z.boolean().optional(),
		productIds: z.array(z.string()).optional(),
	}),
);
