// Generated by ts-to-zod
import { z } from 'zod';

export const getYourGuideActivateBodySchema = z.object({
	gygLoginOTPSecret: z.string(),
	gygSupplierId: z.string(),
	gygSupplierName: z.string(),
});
