// Generated by ts-to-zod
import { z } from "zod";
import { getYourGuideActivateBodySchema } from "./GetYourGuideActivateBody";

export const getYourGuideActivateRequestSchema = z.object({
    body: getYourGuideActivateBodySchema
});
