// Generated by ts-to-zod
import { z } from "zod";
import { partnersConnectionSchema } from "./PartnersConnection";

export const getYourGuideConnectionSchema = partnersConnectionSchema.and(z.object({
    gygConnectId: z.string(),
    gygLoginEmail: z.string(),
    gygLoginPassword: z.string(),
    gygLoginOTPSecret: z.string().optional(),
    gygSupplierId: z.string().optional(),
    gygSupplierName: z.string().optional(),
    gygActivated: z.boolean()
}));
