// Generated by ts-to-zod
import { z } from 'zod';
import { giftsRestrictionItemSchema } from './GiftsRestrictionItem';

export const giftsRestrictionsSchema = z.object({
	maxAmounts: z.array(giftsRestrictionItemSchema),
	minAmounts: z.array(giftsRestrictionItemSchema),
});
