// Generated by ts-to-zod
import * as z from 'zod';
import { identitySchema } from './Identity';

export const giftIdentitiesSchema = z.object({
	identity: identitySchema.optional(),
	identityId: z.string().optional(),
});
