// Generated by ts-to-zod
import * as z from 'zod';
import { redemptionMethodSchema } from './RedemptionMethod';
import { deliveryOptionSchema } from './DeliveryOption';

export const giftVoucherSchema = z.object({
	redemptionMethod: redemptionMethodSchema,
	utcRedeemedAt: z.string().nullable(),
	deliveryOptions: z.array(deliveryOptionSchema),
});
