// Generated by ts-to-zod
import { z } from 'zod';
import { googleNullableLocalizedTextSchema } from './GoogleNullableLocalizedText';

export const googleNullableLocalizedNameSchema = z.object({
	localized_texts: z.array(googleNullableLocalizedTextSchema),
});
