// Generated by ts-to-zod
import { z } from 'zod';
import { googleOperatorSchema } from './GoogleOperator';
import { googleRatingSchema } from './GoogleRating';
import { googleUrlSchema } from './GoogleUrl';
import { googleOptionCategorySchema } from './GoogleOptionCategory';
import { googleRelatedLocationSchema } from './GoogleRelatedLocation';
import { googleLocalizedNameSchema } from './GoogleLocalizedName';

export const googleOptionsSchema = z.object({
	operator: googleOperatorSchema.nullable(),
	rating: googleRatingSchema.nullable(),
	landing_page: googleUrlSchema,
	inventory_types: z.array(z.string()),
	landing_page_list_view: googleUrlSchema.nullable(),
	option_categories: z.array(googleOptionCategorySchema),
	related_locations: z.array(googleRelatedLocationSchema),
	brand_name: googleLocalizedNameSchema,
});
