// Generated by ts-to-zod
import { z } from 'zod';
import { googleLocalizedTextSchema } from './GoogleLocalizedText';

export const googleLocalizedNameSchema = z.object({
	localized_texts: z.array(googleLocalizedTextSchema),
});
