// Generated by ts-to-zod
import { z } from 'zod';
import { googleOperatorSchema } from './GoogleOperator';
import { googleOptionCategorySchema } from './GoogleOptionCategory';
import { googleRatingSchema } from './GoogleRating';
import { googleRelatedLocationSchema } from './GoogleRelatedLocation';
import { googleUrlSchema } from './GoogleUrl';

export const googleOptionsSchema = z.object({
	operator: googleOperatorSchema.nullable(),
	rating: googleRatingSchema.nullable(),
	landing_page: googleUrlSchema,
	inventory_type: z.string(),
	landing_page_list_view: googleUrlSchema,
	option_categories: z.array(googleOptionCategorySchema),
	related_locations: z.array(googleRelatedLocationSchema),
});
