// Generated by ts-to-zod
import { z } from 'zod';
import { googleNullableLocalizedNameSchema } from './GoogleNullableLocalizedName';
import { googleLocationSchema } from './GoogleLocation';

export const googleOperatorSchema = z.object({
	google_business_profile_name: googleNullableLocalizedNameSchema,
	locations: z.array(googleLocationSchema),
});
