// Generated by ts-to-zod
import { z } from "zod";
import { googleLocalizedTextSchema } from "./GoogleLocalizedText";
import { googleLocationSchema } from "./GoogleLocation";

export const googleOperatorSchema = z.object({
    name: z.string(),
    google_business_profile_name: z.object({
        localized_texts: z.array(googleLocalizedTextSchema)
    }),
    phone_number: z.string(),
    locations: z.array(googleLocationSchema)
});
