// Generated by ts-to-zod
import { type Include } from '../models/Include';
import { z } from 'zod';
import { productSchema } from './Product';
import { defaultableIDSchema } from './DefaultableID';
import { optionSchema } from './Option';

export const includeSchema: z.ZodSchema<Include> = z.lazy(() =>
	z.object({
		id: z.string(),
		required: z.boolean(),
		limit: z.number(),
		validityDays: z.number().nullable(),
		availabilityRequired: z.boolean(),
		productId: z.string(),
		product: productSchema.nullable(),
		optionId: defaultableIDSchema,
		option: optionSchema.nullable(),
	}),
);
