// Generated by ts-to-zod
import { z } from 'zod';
import { productSchema } from './Product';
import { defaultableIDSchema } from './DefaultableID';
import { optionSchema } from './Option';

export const includeSchema = z.object({
	id: z.string(),
	required: z.boolean(),
	limit: z.number(),
	validityDays: z.number().optional(),
	productId: z.string(),
	product: productSchema.nullable(),
	optionId: defaultableIDSchema,
	option: optionSchema.nullable(),
});
