// Generated by ts-to-zod
import { z } from "zod";
import { itineraryItemTypeSchema } from "./ItineraryItemType";
import { durationUnitSchema } from "./DurationUnit";

export const itineraryItemSchema = z.object({
    name: z.string(),
    type: itineraryItemTypeSchema,
    description: z.string().nullable(),
    address: z.string().nullable(),
    googlePlaceId: z.string().nullable(),
    latitude: z.number().nullable(),
    longitude: z.number().nullable(),
    travelTime: z.string().nullable(),
    travelTimeAmount: z.number().nullable(),
    travelTimeUnit: durationUnitSchema.nullable(),
    duration: z.string().nullable(),
    durationAmount: z.number(),
    durationUnit: durationUnitSchema
});
