// Generated by ts-to-zod
import { z } from 'zod';

export const linkSchema = z.object({
	id: z.string(),
	href: z.string().nullable(),
	shortDescription: z.string().nullable(),
	title: z.string().nullable(),
});
