// Generated by ts-to-zod
import { z } from 'zod';

export const listOrdersRequestSchema = z.object({
	contactEmailAddress: z.string().optional(),
	contactLastName: z.string().optional(),
	contactPhoneNumber: z.string().optional(),
	supplierReference: z.string().optional(),
	utcCreatedAtEnd: z.string().optional(),
	utcCreatedAtStart: z.string().optional(),
	utcUpdatedAtEnd: z.string().optional(),
	utcUpdatedAtStart: z.string().optional(),
});
