// Generated by ts-to-zod
import { z } from 'zod';

export const listGiftsQueryParamsSchema = z.object({
	resellerReference: z.string().optional(),
	supplierReference: z.string().optional(),
	utcCreatedAtStart: z.string().optional(),
	utcCreatedAtEnd: z.string().optional(),
	utcUpdatedAtStart: z.string().optional(),
	utcUpdatedAtEnd: z.string().optional(),
	contactEmailAddress: z.string().optional(),
});
