// Generated by ts-to-zod
import { z } from "zod";
import { resellerStatusSchema } from "./ResellerStatus";

export const mappingSchema = z.object({
    id: z.string(),
    resellerReference: z.string(),
    resellerStatus: resellerStatusSchema,
    title: z.string(),
    url: z.string(),
    webhookUrl: z.string().nullable(),
    optionRequired: z.boolean(),
    unitRequired: z.boolean(),
    productId: z.string().nullable(),
    optionId: z.string().nullable(),
    unitId: z.string().nullable(),
    connected: z.boolean()
});
