// Generated by ts-to-zod
import { z } from 'zod';
import { resellerStatusSchema } from './ResellerStatus';

export const mappingToUpdateSchema = z.object({
	resellerReference: z.string(),
	resellerStatus: resellerStatusSchema,
	title: z.string(),
	url: z.string(),
	webhookUrl: z.string().nullable(),
	optionRequired: z.boolean(),
	unitRequired: z.boolean(),
});
