// Generated by ts-to-zod
import { z } from 'zod';
import { membershipSchema } from './Membership';

export const membershipLookupSchema = z.object({
	memberships: z.array(membershipSchema),
	message: z.string().nullable(),
	verified: z.boolean(),
});
