// Generated by ts-to-zod
import { z } from 'zod';

export const membershipLookupBodySchema = z.object({
	country: z.string().optional().nullable(),
	email: z.string().optional().nullable(),
	mobile: z.string().optional().nullable(),
	reference: z.string().optional().nullable(),
	verification: z.string().optional().nullable(),
});
