// Generated by ts-to-zod
import { z } from 'zod';
import { customerContactSchema } from './CustomerContact';

export const membershipSchema = z.object({
	id: z.string(),
	title: z.string(),
	contact: customerContactSchema,
	reference: z.string().nullable(),
	resellerReference: z.string(),
	supplierReference: z.string(),
	availabilityLocalDateStart: z.string().nullable(),
	availabilityLocalDateEnd: z.string().nullable(),
});
