// Generated by ts-to-zod
import { z } from 'zod';

export const navSchema = z.object({
	id: z.string(),
	title: z.string().nullable(),
	parentTitle: z.string().nullable(),
	inFooter: z.boolean().nullable(),
	inHeader: z.boolean().nullable(),
	href: z.string().nullable(),
});
