// Generated by ts-to-zod
import { z } from "zod";

export const noticeSchema = z.object({
    id: z.string(),
    title: z.string().nullable(),
    shortDescription: z.string(),
    coverImageUrl: z.string().nullable()
});
