// Generated by ts-to-zod
import { z } from "zod";
import { octo_ExtendReservationBodySchema } from "./Octo_ExtendReservationBody";

export const octo_ExtendReservationRequestSchema = z.object({
    uuid: z.string(),
    body: octo_ExtendReservationBodySchema
});
