// Generated by ts-to-zod
import { z } from 'zod';
import { octo_AvailabilityCalendarBodySchema } from './Octo_AvailabilityCalendarBody';

export const octo_AvailabilityCalendarRequestSchema = z.object({
	body: octo_AvailabilityCalendarBodySchema,
});
