// Generated by ts-to-zod
import { z } from "zod";
import { octo_PricingSchema } from "./Octo_Pricing";

export const octo_PricingUnitSchema = octo_PricingSchema.and(z.object({
    unitId: z.string()
}));
