// Generated by ts-to-zod
import { z } from 'zod';
import { octo_ErrorForbiddenSchema } from './Octo_ErrorForbidden';
import { octo_ErrorInternalServerErrorSchema } from './Octo_ErrorInternalServerError';
import { octo_ErrorInvalidBookingUUIDSchema } from './Octo_ErrorInvalidBookingUUID';
import { octo_ErrorUnauthorizedSchema } from './Octo_ErrorUnauthorized';
import { octo_ErrorUnprocessableEntitySchema } from './Octo_ErrorUnprocessableEntity';

export const octo_BookingCancellationErrorResponseSchema = z.object({
	body: z.union([
		octo_ErrorInvalidBookingUUIDSchema,
		octo_ErrorUnprocessableEntitySchema,
		octo_ErrorUnauthorizedSchema,
		octo_ErrorInternalServerErrorSchema,
		octo_ErrorForbiddenSchema,
	]),
});
