// Generated by ts-to-zod
import { z } from 'zod';
import { octo_BookingReservationBodySchema } from './Octo_BookingReservationBody';

export const octo_BookingReservationRequestSchema = z.object({
	body: octo_BookingReservationBodySchema,
});
