// Generated by ts-to-zod
import { z } from 'zod';
import { octo_AvailabilityCheckBodySchema } from './Octo_AvailabilityCheckBody';

export const octo_AvailabilityCheckRequestSchema = z.object({
	body: octo_AvailabilityCheckBodySchema,
});
