// Generated by ts-to-zod
import { z } from 'zod';
import { octo_ErrorBadRequestSchema } from './Octo_ErrorBadRequest';
import { octo_ErrorForbiddenSchema } from './Octo_ErrorForbidden';
import { octo_ErrorInternalServerErrorSchema } from './Octo_ErrorInternalServerError';
import { octo_ErrorInvalidOptionIDSchema } from './Octo_ErrorInvalidOptionID';
import { octo_ErrorInvalidProductIDSchema } from './Octo_ErrorInvalidProductID';
import { octo_ErrorUnauthorizedSchema } from './Octo_ErrorUnauthorized';

export const octo_AvailabilityCheckErrorResponseSchema = z.object({
	body: z.union([
		octo_ErrorInvalidProductIDSchema,
		octo_ErrorInvalidOptionIDSchema,
		octo_ErrorBadRequestSchema,
		octo_ErrorUnauthorizedSchema,
		octo_ErrorInternalServerErrorSchema,
		octo_ErrorForbiddenSchema,
	]),
});
