// Generated by ts-to-zod
import { z } from 'zod';
import { octo_BookingUnitItemSchema } from './Octo_BookingUnitItem';

export const octo_BookingReservationBodySchema = z.object({
	uuid: z.string().optional(),
	productId: z.string(),
	optionId: z.string(),
	availabilityId: z.string().optional(),
	expirationMinutes: z.number().optional(),
	notes: z.string().optional(),
	unitItems: z.array(octo_BookingUnitItemSchema),
	currency: z.string().optional(),
});
