// Generated by ts-to-zod
import { z } from 'zod';
import { octo_BaseErrorSchema } from './Octo_BaseError';

export const octo_ErrorInvalidUnitIDSchema = octo_BaseErrorSchema.and(
	z.object({
		unitId: z.string(),
	}),
);
