// Generated by ts-to-zod
import { z } from 'zod';
import { availabilityStatusSchema } from './AvailabilityStatus';
import { octo_OpeningHoursSchema } from './Octo_OpeningHours';
import { octo_PricingSchema } from './Octo_Pricing';
import { octo_PricingUnitSchema } from './Octo_PricingUnit';

export const octo_AvailabilityCalendarSchema = z.object({
	localDate: z.string(),
	available: z.boolean(),
	status: availabilityStatusSchema,
	vacancies: z.number().nullable(),
	capacity: z.number().nullable(),
	openingHours: z.array(octo_OpeningHoursSchema),
	unitPricingFrom: z.array(octo_PricingUnitSchema).optional(),
	pricingFrom: z.array(octo_PricingSchema).optional(),
});
