// Generated by ts-to-zod
import { z } from "zod";
import { octo_BaseErrorSchema } from "./Octo_BaseError";

export const octo_ErrorInvalidBookingUUIDSchema = octo_BaseErrorSchema.and(z.object({
    uuid: z.string()
}));
