// Generated by ts-to-zod
import { z } from 'zod';

export const octo_GetBookingsRequestSchema = z.object({
	resellerReference: z.string().optional(),
	supplierReference: z.string().optional(),
	localDate: z.string().optional(),
	localDateStart: z.string().optional(),
	localDateEnd: z.string().optional(),
	productId: z.string().optional(),
	optionId: z.string().optional(),
});
