// Generated by ts-to-zod
import { z } from 'zod';
import { octo_BookingContactSchema } from './Octo_BookingContact';
import { octo_BookingUnitItemSchema } from './Octo_BookingUnitItem';

export const octo_BookingConfirmationBodySchema = z.object({
	emailReceipt: z.boolean().optional(),
	resellerReference: z.string().optional(),
	contact: octo_BookingContactSchema,
	unitItems: z.array(octo_BookingUnitItemSchema).optional(),
});
