// Generated by ts-to-zod
import { z } from 'zod';
import { octo_AvailabilityUnitSchema } from './Octo_AvailabilityUnit';

export const octo_AvailabilityCalendarBodySchema = z.object({
	productId: z.string(),
	optionId: z.string(),
	localDateStart: z.string().optional(),
	localDateEnd: z.string().optional(),
	units: z.array(octo_AvailabilityUnitSchema).optional(),
	currency: z.string().optional(),
});
