// Generated by ts-to-zod
import { z } from 'zod';
import { octo_TaxSchema } from './Octo_Tax';

export const octo_PricingSchema = z.object({
	original: z.number(),
	retail: z.number(),
	net: z.number().nullable(),
	currency: z.string(),
	currencyPrecision: z.number(),
	includedTaxes: z.array(octo_TaxSchema),
});
