// Generated by ts-to-zod
import { z } from 'zod';
import { octo_BookingConfirmationBodySchema } from './Octo_BookingConfirmationBody';

export const octo_BookingConfirmationRequestSchema = z.object({
	uuid: z.string(),
	body: octo_BookingConfirmationBodySchema,
});
