// Generated by ts-to-zod
import { z } from "zod";
import { mediaTypeSchema } from "./MediaType";
import { mediaRelSchema } from "./MediaRel";

export const octo_MediaSchema = z.object({
    src: z.string(),
    type: mediaTypeSchema,
    rel: mediaRelSchema,
    title: z.string().nullable(),
    caption: z.string().nullable(),
    copyright: z.string().nullable()
});
