// Generated by ts-to-zod
import { z } from 'zod';
import { octo_BaseErrorSchema } from './Octo_BaseError';

export const octo_ErrorInvalidProductIDSchema = octo_BaseErrorSchema.and(
	z.object({
		productId: z.string(),
	}),
);
