// Generated by ts-to-zod
import { z } from 'zod';

export const octo_BookingContactSchema = z.object({
	fullName: z.string().optional(),
	firstName: z.string().optional(),
	lastName: z.string().optional(),
	emailAddress: z.string().optional(),
	phoneNumber: z.string().optional(),
	locales: z.array(z.string()).optional(),
	postalCode: z.string().optional(),
	country: z.string().optional(),
	notes: z.string().optional(),
});
