// Generated by ts-to-zod
import { z } from 'zod';
import { octo_ErrorForbiddenSchema } from './Octo_ErrorForbidden';
import { octo_ErrorInternalServerErrorSchema } from './Octo_ErrorInternalServerError';
import { octo_ErrorInvalidAvailabilityIDSchema } from './Octo_ErrorInvalidAvailabilityID';
import { octo_ErrorInvalidOptionIDSchema } from './Octo_ErrorInvalidOptionID';
import { octo_ErrorInvalidProductIDSchema } from './Octo_ErrorInvalidProductID';
import { octo_ErrorInvalidUnitIDSchema } from './Octo_ErrorInvalidUnitID';
import { octo_ErrorUnauthorizedSchema } from './Octo_ErrorUnauthorized';
import { octo_ErrorUnprocessableEntitySchema } from './Octo_ErrorUnprocessableEntity';

export const octo_BookingReservationErrorResponseSchema = z.object({
	body: z.union([
		octo_ErrorInvalidProductIDSchema,
		octo_ErrorInvalidOptionIDSchema,
		octo_ErrorInvalidUnitIDSchema,
		octo_ErrorInvalidAvailabilityIDSchema,
		octo_ErrorUnprocessableEntitySchema,
		octo_ErrorUnauthorizedSchema,
		octo_ErrorInternalServerErrorSchema,
		octo_ErrorForbiddenSchema,
	]),
});
