// Generated by ts-to-zod
import { z } from 'zod';
import { octo_BookingCancellationBodySchema } from './Octo_BookingCancellationBody';

export const octo_BookingCancellationRequestSchema = z.object({
	uuid: z.string(),
	body: octo_BookingCancellationBodySchema,
});
