// Generated by ts-to-zod
import { z } from 'zod';
import { octo_CapabilityIdSchema } from './Octo_CapabilityId';

export const octo_CapabilitySchema = z.object({
	id: octo_CapabilityIdSchema,
	revision: z.number(),
	required: z.boolean(),
	dependencies: z.array(octo_CapabilityIdSchema),
	docs: z.string().nullable(),
});
