// Generated by ts-to-zod
import { z } from "zod";

export const offerRestrictionsSchema = z.object({
    minUnits: z.number().nullable(),
    maxUnits: z.number().nullable(),
    minTotal: z.number().nullable(),
    maxTotal: z.number().nullable(),
    unitIds: z.array(z.string())
});
