// Generated by ts-to-zod
import { z } from 'zod';
import { pricingSchema } from './Pricing';
import { productSchema } from './Product';
import { unitSchema } from './Unit';

export const offerComparisonSchema = z.object({
	productId: z.string(),
	optionId: z.string(),
	pricing: pricingSchema,
	product: productSchema,
	shortDescription: z.string().optional(),
	units: z.array(unitSchema),
});
