// Generated by ts-to-zod
import { z } from 'zod';
import { taxSchema } from './Tax';

export const offerDiscountSchema = z.object({
	original: z.number(),
	retail: z.number(),
	includedTaxes: z.array(taxSchema),
});
