// Generated by ts-to-zod
import { z } from 'zod';
import { netDiscountSchema } from './NetDiscount';
import { offerRestrictionsSchema } from './OfferRestrictions';

export const offerSchema = z.object({
	title: z.string(),
	code: z.string(),
	description: z.string().nullable(),
	netDiscount: netDiscountSchema.nullable(),
	restrictions: offerRestrictionsSchema,
	usable: z.boolean(),
});
