// Generated by ts-to-zod
import { z } from 'zod';
import { membershipBenefitSchema } from './MembershipBenefit';

export const offerMembershipsSchema = z.object({
	membershipBenefit: membershipBenefitSchema.optional().nullable(),
});
