// Generated by ts-to-zod
import { z } from 'zod';
import { netDiscountSchema } from './NetDiscount';
import { offerRestrictionsSchema } from './OfferRestrictions';
import { membershipBenefitSchema } from './MembershipBenefit';

export const offerSchema = z.object({
	id: z.string(),
	title: z.string(),
	label: z.string(),
	code: z.string(),
	description: z.string().nullable(),
	availabilityLocalDateStart: z.string().nullable(),
	availabilityLocalDateEnd: z.string().nullable(),
	netDiscount: netDiscountSchema.nullable(),
	restrictions: offerRestrictionsSchema,
	usable: z.boolean(),
	unusableReason: z.string().nullable(),
	tags: z.array(z.string()),
	membershipBenefit: membershipBenefitSchema.optional().nullable(),
});
