// Generated by ts-to-zod
import { z } from 'zod';
import { discountTaxSchema } from './DiscountTax';

export const offerDiscountSchema = z.object({
	net: z.number(),
	retail: z.number(),
	includedTaxes: z.array(discountTaxSchema),
});
