// Generated by ts-to-zod
import { z } from 'zod';
import { pricingSchema } from './Pricing';
import { unitSchema } from './Unit';
import { bookingSchema } from './Booking';

export const offerCombinationSchema = z.object({
	productId: z.string(),
	optionId: z.string(),
	offerCode: z.string(),
	offerTitle: z.string(),
	pricing: pricingSchema,
	shortDescription: z.string().optional(),
	units: z.array(unitSchema),
	booking: bookingSchema.nullable(),
});
