// Generated by ts-to-zod
import { z } from 'zod';
import { offerTaxSchema } from './OfferTax';

export const offerDiscountSchema = z.object({
	net: z.number(),
	retail: z.number(),
	includedTaxes: z.array(offerTaxSchema),
});
