// Generated by ts-to-zod
import { z } from 'zod';

export const openingHoursSchema = z.object({
	from: z.string(),
	to: z.string(),
	frequency: z.string().optional(),
	frequencyAmount: z.number().optional(),
	frequencyUnit: z.string().optional(),
});
