// Generated by ts-to-zod
import { z } from 'zod';
import { durationUnitSchema } from './DurationUnit';

export const openingHoursContentSchema = z.object({
	frequency: z.string().optional().nullable(),
	frequencyAmount: z.number().optional().nullable(),
	frequencyUnit: durationUnitSchema.optional(),
});
