// Generated by ts-to-zod
import { z } from 'zod';

export const openingHoursContentSchema = z.object({
	frequency: z.string().optional(),
	frequencyAmount: z.number().optional(),
	frequencyUnit: z.string().optional(),
});
