// Generated by ts-to-zod
import { z } from 'zod';
import { durationUnitSchema } from './DurationUnit';

export const openingHoursSchema = z.object({
	from: z.string(),
	to: z.string(),
	frequency: z.string().optional().nullable(),
	frequencyAmount: z.number().optional().nullable(),
	frequencyUnit: durationUnitSchema.optional(),
});
