// Generated by ts-to-zod
import { z } from 'zod';
import { durationUnitSchema } from './DurationUnit';
import { itineraryItemSchema } from './ItineraryItem';
import { pointSchema } from './Point';

export const optionContentSchema = z.object({
	title: z.string().optional(),
	subtitle: z.string().optional().nullable(),
	language: z.string().optional(),
	shortDescription: z.string().optional().nullable(),
	duration: z.string().optional().nullable(),
	durationAmount: z.number().optional().nullable(),
	durationUnit: durationUnitSchema.optional().nullable(),
	coverImageUrl: z.string().optional().nullable(),
	itinerary: z.array(itineraryItemSchema).optional().nullable(),
	fromPoint: pointSchema.optional().nullable(),
	toPoint: pointSchema.optional().nullable(),
	meetingPoint: z.string().optional().nullable(),
	meetingPointCoordinates: z.string().optional().nullable(),
	meetingPointDirections: z.string().optional().nullable(),
	meetingPointLatitude: z.number().optional().nullable(),
	meetingPointLongitude: z.number().optional().nullable(),
});
