// Generated by ts-to-zod
import * as z from 'zod';
import { packageIncludeSchema } from './PackageInclude';

export const optionPackagesSchema = z.object({
	packageIncludes: z.array(packageIncludeSchema).optional(),
});
