// Generated by ts-to-zod
import { z } from 'zod';
import { durationUnitSchema } from './DurationUnit';
import { contactFieldSchema } from './ContactField';
import { optionRestrictionsSchema } from './OptionRestrictions';
import { unitSchema } from './Unit';
import { itineraryItemSchema } from './ItineraryItem';
import { pointSchema } from './Point';
import { pickupPointSchema } from './PickupPoint';
import { pricingSchema } from './Pricing';
import { questionSchema } from './Question';
import { extraSchema } from './Extra';
import { packageIncludeSchema } from './PackageInclude';
import { rentalDurationSchema } from './RentalDuration';

export const optionSchema: z.ZodTypeAny = z.lazy(() =>
	z.object({
		id: z.string(),
		default: z.boolean(),
		internalName: z.string(),
		reference: z.string().nullable(),
		availabilityLocalStartTimes: z.array(z.string()),
		availabilityLocalDateStart: z.string().nullable(),
		availabilityLocalDateEnd: z.string().nullable(),
		cancellationCutoff: z.string(),
		cancellationCutoffAmount: z.number(),
		cancellationCutoffUnit: durationUnitSchema,
		requiredContactFields: z.array(contactFieldSchema),
		availabilityCutoff: z.string(),
		availabilityCutoffAmount: z.number(),
		availabilityCutoffUnit: durationUnitSchema,
		availabilityNotice: z.string().nullable(),
		availabilityNoticeAmount: z.number().nullable(),
		availabilityNoticeUnit: durationUnitSchema.nullable(),
		tags: z.array(z.string()),
		visibleContactFields: z.array(contactFieldSchema),
		restrictions: optionRestrictionsSchema,
		units: z.array(unitSchema),
		title: z.string().optional(),
		subtitle: z.string().optional().nullable(),
		language: z.string().optional(),
		shortDescription: z.string().optional().nullable(),
		duration: z.string().optional().nullable(),
		durationAmount: z.number().optional().nullable(),
		durationUnit: durationUnitSchema.optional().nullable(),
		coverImageUrl: z.string().optional().nullable(),
		itinerary: z.array(itineraryItemSchema).optional().nullable(),
		fromPoint: pointSchema.optional().nullable(),
		toPoint: pointSchema.optional().nullable(),
		meetingPoint: z.string().optional().nullable(),
		meetingPointCoordinates: z.string().optional().nullable(),
		meetingPointDirections: z.string().optional().nullable(),
		meetingPointLatitude: z.number().optional().nullable(),
		meetingPointLongitude: z.number().optional().nullable(),
		pickupAvailable: z.boolean().optional(),
		pickupRequired: z.boolean().optional(),
		pickupPoints: z.array(pickupPointSchema).optional(),
		pricingFrom: z.array(pricingSchema).optional(),
		pricing: z.array(pricingSchema).optional(),
		questions: z.array(questionSchema).optional(),
		extras: z.array(extraSchema).optional(),
		packageIncludes: z.array(packageIncludeSchema).optional(),
		rentalDurations: z.array(rentalDurationSchema).optional(),
	}),
);
