// Generated by ts-to-zod
import * as z from 'zod';
import { rentalDurationSchema } from './RentalDuration';

export const optionRentalsSchema = z.object({
	rentalDurations: z.array(rentalDurationSchema).optional(),
});
