// Generated by ts-to-zod
import { z } from 'zod';

export const optionRestrictionsSchema = z.object({
	minUnits: z.number().nullable(),
	maxUnits: z.number().nullable(),
	minPaxCount: z.number().nullable(),
	maxPaxCount: z.number().nullable(),
});
