// Generated by ts-to-zod
import { z } from 'zod';
import { pickupPointSchema } from './PickupPoint';

export const optionPickupsSchema = z.object({
	pickupAvailable: z.boolean().optional(),
	pickupRequired: z.boolean().optional(),
	pickupPoints: z.array(pickupPointSchema).optional(),
});
