// Generated by ts-to-zod
import { z } from 'zod';
import { giftPaymentSchema } from './GiftPayment';
import { giftSchema } from './Gift';

export const orderGiftsSchema = z.object({
	giftPayment: giftPaymentSchema.optional().nullable(),
	gifts: z.array(giftSchema).optional(),
});
