// Generated by ts-to-zod
import * as z from 'zod';
import { destinationSchema } from './Destination';
import { brandSchema } from './Brand';

export const orderContentSchema = z.object({
	termsAccepted: z.boolean().optional(),
	destination: destinationSchema.optional(),
	brand: brandSchema.optional(),
});
