// Generated by ts-to-zod
import { z } from 'zod';
import { cardPaymentSchema } from './CardPayment';

export const orderCardPaymentsSchema = z.object({
	cardPayment: cardPaymentSchema.optional().nullable(),
	returnUrl: z.string().optional().nullable(),
});
