// Generated by ts-to-zod
import { z } from "zod";
import { giftPaymentSchema } from "./GiftPayment";

export const orderGiftsSchema = z.object({
    giftPayment: giftPaymentSchema.optional().nullable()
});
