// Generated by ts-to-zod
import { z } from 'zod';
import { agentSchema } from './Agent';
import { bookingSchema } from './Booking';
import { contactFieldSchema } from './ContactField';
import { customerContactSchema } from './CustomerContact';
import { giftPaymentSchema } from './GiftPayment';
import { identitySchema } from './Identity';
import { offerCombinationSchema } from './OfferCombination';
import { resellerSchema } from './Reseller';
import { sellerSchema } from './Seller';
import { settlementMethodSchema } from './SettlementMethod';
import { userSchema } from './User';

export const orderSchema = z.object({
	id: z.string(),
	testMode: z.boolean(),
	settlementMethod: settlementMethodSchema,
	supplierReference: z.string(),
	quote: z.boolean(),
	status: z.string(),
	utcExpiresAt: z.string().nullable(),
	utcConfirmedAt: z.string().nullable(),
	cancellable: z.boolean(),
	confirmable: z.boolean(),
	reseller: resellerSchema.optional(),
	agent: agentSchema.optional(),
	contact: customerContactSchema.optional(),
	emailReceipt: z.boolean().optional(),
	bookings: z.array(bookingSchema),
	visibleContactFields: z.array(contactFieldSchema),
	requiredContactFields: z.array(contactFieldSchema),
	user: userSchema.nullable(),
	seller: sellerSchema.nullable(),
	identity: identitySchema.optional(),
	identityId: z.string().optional(),
	offerCombinations: z.array(offerCombinationSchema).optional(),
	giftPayment: giftPaymentSchema.optional().nullable(),
});
