// Generated by ts-to-zod
import { z } from 'zod';
import { offerCombinationSchema } from './OfferCombination';

export const orderOffersSchema = z.object({
	offerCombinations: z.array(offerCombinationSchema).optional(),
});
