// Generated by ts-to-zod
import * as z from 'zod';
import { cardPaymentGatewaySchema } from './CardPaymentGateway';

export const orderCardPaymentsSchema = z.object({
	cardPayment: cardPaymentGatewaySchema.optional().nullable(),
	returnUrl: z.string().optional().nullable(),
});
