// Generated by ts-to-zod
import { z } from "zod";
import { identitySchema } from "./Identity";

export const orderIdentitiesSchema = z.object({
    identity: identitySchema.optional(),
    identityId: z.string().optional()
});
