// Generated by ts-to-zod
import { z } from 'zod';

export const orderVentrataCheckoutSchema = z.object({
	fingerprintLinkedId: z.string().optional().nullable(),
	fingerprintReceived: z.boolean().optional(),
	recaptchaEnterpriseReceived: z.string().optional().nullable(),
	recoveryUrl: z.string().optional().nullable(),
	segmentAnonymousId: z.string().optional().nullable(),
	utmCampaign: z.string().optional().nullable(),
	utmContent: z.string().optional().nullable(),
	utmMedium: z.string().optional().nullable(),
	utmSource: z.string().optional().nullable(),
});
