// Generated by ts-to-zod
import * as z from 'zod';
import { offerCombinationSchema } from './OfferCombination';

export const orderOffersSchema = z.object({
	offerCombinations: z.array(offerCombinationSchema).optional(),
});
