// Generated by ts-to-zod
import { z } from 'zod';
import { questionAnswerSchema } from './QuestionAnswer';

export const orderQuestionsSchema = z.object({
	questionAnswers: z.array(questionAnswerSchema).optional(),
});
