// Generated by ts-to-zod
import * as z from 'zod';
import { membershipSchema } from './Membership';

export const orderMembershipsSchema = z.object({
	membership: membershipSchema.optional().nullable(),
});
