// Generated by ts-to-zod
import { z } from 'zod';
import { includeSchema } from './Include';

export const packageIncludeSchema = z.object({
	title: z.string().optional(),
	count: z.number(),
	includes: z.array(includeSchema),
});
