// Generated by ts-to-zod
import { type PackageInclude } from '../models/PackageInclude';
import { z } from 'zod';
import { includeSchema } from './Include';

export const packageIncludeSchema: z.ZodSchema<PackageInclude> = z.lazy(() =>
	z.object({
		title: z.string().optional(),
		count: z.number(),
		includes: z.array(includeSchema),
	}),
);
