// Generated by ts-to-zod
import { z } from 'zod';

export const pageSchema = z.object({
	id: z.string(),
	body: z.string().optional().nullable(),
	fullscreen: z.boolean(),
	href: z.string().nullable(),
	availableLanguages: z.array(z.string()),
	meta: z.record(z.any()),
	shortDescription: z.string().optional().nullable(),
	showFooter: z.boolean(),
	showHeader: z.boolean(),
	title: z.string().nullable(),
});
