// Generated by ts-to-zod
import { z } from 'zod';
import { availableLanguagesItemSchema } from './AvailableLanguagesItem';

export const pageSchema = z.object({
	id: z.string(),
	body: z.string().optional(),
	fullscreen: z.boolean(),
	href: z.string().optional(),
	availableLanguages: availableLanguagesItemSchema.nullable(),
	meta: z.record(z.string()).optional(),
	shortDescription: z.string().nullable(),
	showFooter: z.boolean(),
	showHeader: z.boolean(),
	title: z.string().nullable(),
});
