// Generated by ts-to-zod
import { z } from 'zod';
import { supplierSchema } from './Supplier';
import { partnersConnectionSchema } from './PartnersConnection';
import { getYourGuideConnectionSchema } from './GetYourGuideConnection';

export const partnersListConnectionSchema = z.object({
	supplier: supplierSchema,
	connection: z.union([partnersConnectionSchema, getYourGuideConnectionSchema]),
	apiKey: z.string(),
});
