// Generated by ts-to-zod
import { z } from 'zod';

export const paytrGatewaySchema = z.object({
	id: z.string().optional().nullable(),
	iframeUrl: z.string().optional().nullable(),
	error: z.string().optional().nullable(),
});
