// Generated by ts-to-zod
import { z } from 'zod';

export const peachGatewaySchema = z.object({
	key: z.any().optional(),
	entityId: z.string().optional(),
	checkoutId: z.string().optional().nullable(),
});
