// Generated by ts-to-zod
import { z } from 'zod';

export const pickupPointSchema = z.object({
	id: z.string(),
	name: z.string(),
	directions: z.string().nullable(),
	address: z.string().nullable(),
	latitude: z.number().nullable(),
	longitude: z.number().nullable(),
	localDateTime: z.string().nullable(),
	localDateTimeTo: z.string().nullable(),
	googlePlaceId: z.string().nullable(),
	street: z.string().nullable(),
	postalCode: z.string().nullable(),
	locality: z.string().nullable(),
	region: z.string().nullable(),
	state: z.string().nullable(),
	country: z.string().nullable(),
});
