// Generated by ts-to-zod
import { z } from "zod";

export const pointGroupSchema = z.object({
    id: z.string(),
    internalName: z.string(),
    title: z.string(),
    shortDescription: z.string()
});
