// Generated by ts-to-zod
import * as z from 'zod';
import { pointGroupSchema } from './PointGroup';

export const pointSchema = z.object({
	id: z.string(),
	internalName: z.string().nullable(),
	title: z.string().nullable(),
	shortDescription: z.string().nullable(),
	pointGroup: pointGroupSchema,
});
