// Generated by ts-to-zod
import { z } from 'zod';
import { pricingSchema } from './Pricing';
import { taxSchema } from './Tax';

export const pricingUnitSchema = z.object({
	original: z.number(),
	retail: z.number(),
	net: z.number().nullable(),
	currency: z.string(),
	currencyPrecision: z.number(),
	includedTaxes: z.array(taxSchema),
	unitId: z.string(),
	extraPricing: z.array(pricingSchema).optional(),
});
