// Generated by ts-to-zod
import { z } from 'zod';
import { taxSchema } from './Tax';
import { offerDiscountSchema } from './OfferDiscount';

export const pricingSchema = z.object({
	original: z.number(),
	retail: z.number(),
	net: z.number().nullable(),
	currency: z.string(),
	currencyPrecision: z.number(),
	includedTaxes: z.array(taxSchema),
	offerDiscount: offerDiscountSchema.optional().nullable(),
	extraId: z.array(z.string()).optional(),
});
