// Generated by ts-to-zod
import { z } from 'zod';
import { extraPricingSchema } from './ExtraPricing';

export const pricingUnitExtrasSchema = z.object({
	extraPricing: z.array(extraPricingSchema).optional(),
	extraPricingFrom: z.array(extraPricingSchema).optional(),
});
