// Generated by ts-to-zod
import { z } from "zod";
import { pricingSchema } from "./Pricing";

export const pricingUnitExtrasSchema = z.object({
    extraPricing: z.array(pricingSchema).optional()
});
