// Generated by ts-to-zod
import { z } from 'zod';
import { taxSchema } from './Tax';
import { offerDiscountSchema } from './OfferDiscount';
import { extraPricingSchema } from './ExtraPricing';

export const pricingSchema = z.object({
	original: z.number(),
	retail: z.number(),
	net: z.number().nullable(),
	currency: z.string(),
	currencyPrecision: z.number(),
	includedTaxes: z.array(taxSchema),
	offerDiscount: offerDiscountSchema.optional().nullable(),
	extraPricing: z.array(extraPricingSchema).optional(),
	extraPricingFrom: z.array(extraPricingSchema).optional(),
});
