// Generated by ts-to-zod
import { z } from 'zod';
import { offerDiscountSchema } from './OfferDiscount';

export const pricingOffersSchema = z.object({
	offerDiscount: offerDiscountSchema.optional().nullable(),
});
