// Generated by ts-to-zod
import { z } from "zod";
import { googleOptionsSchema } from "./GoogleOptions";

export const productGoogleSchema = z.object({
    googleOptions: z.array(googleOptionsSchema).optional()
});
