// Generated by ts-to-zod
import { z } from 'zod';
import { linkSchema } from './Link';
import { availableLanguagesSchema } from './AvailableLanguages';

export const productVentrataCheckoutContentSchema = z.object({
	href: z.string().optional().nullable(),
	meta: z.record(z.string()).optional(),
	links: z.array(linkSchema).optional(),
	giftCardAllowed: z.boolean().optional(),
	relatedProductIds: z.array(z.string()).optional(),
	availableLanguages: availableLanguagesSchema.optional().nullable(),
});
