// Generated by ts-to-zod
import { z } from 'zod';

export const productPackagesSchema = z.object({
	isPackage: z.boolean().optional(),
	packageBookingAvailabilityRequired: z.boolean().optional(),
});
