// Generated by ts-to-zod
import { z } from "zod";
import { availabilityTypeSchema } from "./AvailabilityType";
import { type Product } from "../models/Product";
import { deliveryFormatSchema } from "./DeliveryFormat";
import { deliveryMethodSchema } from "./DeliveryMethod";
import { redemptionMethodSchema } from "./RedemptionMethod";
import { settlementMethodSchema } from "./SettlementMethod";
import { durationUnitSchema } from "./DurationUnit";
import { optionSchema } from "./Option";
import { destinationSchema } from "./Destination";
import { categorySchema } from "./Category";
import { fAQSchema } from "./FAQ";
import { imageSchema } from "./Image";
import { brandSchema } from "./Brand";
import { pricingPerSchema } from "./PricingPer";
import { googleOptionsSchema } from "./GoogleOptions";

export const productSchema: z.ZodSchema<Product> = z.lazy(() => z.object({
    id: z.string(),
    internalName: z.string(),
    reference: z.string().nullable(),
    locale: z.string(),
    timeZone: z.string(),
    allowFreesale: z.boolean(),
    instantConfirmation: z.boolean(),
    instantDelivery: z.boolean(),
    availabilityRequired: z.boolean(),
    availabilityType: availabilityTypeSchema,
    deliveryFormats: z.array(deliveryFormatSchema),
    deliveryMethods: z.array(deliveryMethodSchema),
    redemptionMethod: redemptionMethodSchema,
    tags: z.array(z.string()),
    settlementMethods: z.array(settlementMethodSchema),
    freesaleDurationAmount: z.number(),
    freesaleDurationUnit: durationUnitSchema,
    options: z.array(optionSchema),
    country: z.string().optional(),
    location: z.string().optional(),
    destination: destinationSchema.optional(),
    alert: z.string().optional(),
    title: z.string().optional(),
    subtitle: z.string().optional(),
    description: z.string().optional(),
    shortDescription: z.string().optional(),
    categories: z.array(categorySchema).optional(),
    inclusions: z.array(z.string()).optional(),
    exclusions: z.array(z.string()).optional(),
    highlights: z.array(z.string()).optional(),
    pointToPoint: z.boolean().optional(),
    bookingTerms: z.string().optional(),
    privacyTerms: z.string().optional(),
    redemptionInstructions: z.string().optional(),
    cancellationPolicy: z.string().optional(),
    faqs: z.array(fAQSchema).optional(),
    coverImageUrl: z.string().optional(),
    bannerImageUrl: z.string().optional(),
    videoUrl: z.string().optional(),
    galleryImages: z.array(imageSchema).optional(),
    bannerImages: z.array(imageSchema).optional(),
    googlePlaceId: z.string().optional(),
    address: z.string().optional(),
    keywords: z.array(z.string()).optional(),
    tagline: z.string().optional(),
    brand: brandSchema.optional(),
    defaultCurrency: z.string().optional(),
    availableCurrencies: z.array(z.string()).optional(),
    pricingPer: pricingPerSchema.optional(),
    includeTax: z.boolean().optional(),
    isPackage: z.boolean().optional(),
    packageBookingAvailabilityRequired: z.boolean().optional(),
    googleOptions: z.array(googleOptionsSchema).optional()
}));
