// Generated by ts-to-zod
import { z } from 'zod';
import { checkoutConfigPricingDisplaySchema } from './CheckoutConfigPricingDisplay';

export const productVentrataCheckoutSchema = z.object({
	pricingDisplay: checkoutConfigPricingDisplaySchema.optional(),
	outstandingBalanceShortDescription: z.string().optional(),
	outstandingBalanceTitle: z.string().optional(),
});
