// Generated by ts-to-zod
import { z } from "zod";
import { pricingPerSchema } from "./PricingPer";

export const productPricingSchema = z.object({
    defaultCurrency: z.string().optional(),
    availableCurrencies: z.array(z.string()).optional(),
    pricingPer: pricingPerSchema.optional(),
    includeTax: z.boolean().optional()
});
