// Generated by ts-to-zod
import { z } from 'zod';
import { destinationSchema } from './Destination';
import { categorySchema } from './Category';
import { fAQSchema } from './FAQ';
import { imageSchema } from './Image';
import { brandSchema } from './Brand';

export const productContentSchema = z.object({
	country: z.string().optional(),
	location: z.string().optional(),
	destination: destinationSchema.optional(),
	alert: z.string().optional().nullable(),
	title: z.string().optional(),
	subtitle: z.string().optional().nullable(),
	description: z.string().optional().nullable(),
	shortDescription: z.string().optional().nullable(),
	categories: z.array(categorySchema).optional(),
	inclusions: z.array(z.string()).optional(),
	exclusions: z.array(z.string()).optional(),
	highlights: z.array(z.string()).optional(),
	pointToPoint: z.boolean().optional(),
	bookingTerms: z.string().optional().nullable(),
	privacyTerms: z.string().optional().nullable(),
	redemptionInstructions: z.string().optional().nullable(),
	cancellationPolicy: z.string().optional().nullable(),
	faqs: z.array(fAQSchema).optional(),
	coverImageUrl: z.string().optional().nullable(),
	bannerImageUrl: z.string().optional().nullable(),
	videoUrl: z.string().optional().nullable(),
	galleryImages: z.array(imageSchema).optional(),
	bannerImages: z.array(imageSchema).optional(),
	googlePlaceId: z.string().optional().nullable(),
	latitude: z.number().optional(),
	longitude: z.number().optional(),
	address: z.string().optional(),
	keywords: z.array(z.string()).optional(),
	tagline: z.string().optional().nullable(),
	brand: brandSchema.optional(),
});
