// Generated by ts-to-zod
import { z } from 'zod';
import { availabilityTypeSchema } from './AvailabilityType';
import { type Product } from '../models/Product';
import { deliveryFormatSchema } from './DeliveryFormat';
import { deliveryMethodSchema } from './DeliveryMethod';
import { redemptionMethodSchema } from './RedemptionMethod';
import { settlementMethodSchema } from './SettlementMethod';
import { durationUnitSchema } from './DurationUnit';
import { optionSchema } from './Option';
import { destinationSchema } from './Destination';
import { categorySchema } from './Category';
import { fAQSchema } from './FAQ';
import { imageSchema } from './Image';
import { brandSchema } from './Brand';
import { pricingPerSchema } from './PricingPer';
import { googleOptionsSchema } from './GoogleOptions';

export const productSchema: z.ZodSchema<Product> = z.lazy(() =>
	z.object({
		id: z.string(),
		internalName: z.string(),
		reference: z.string().nullable(),
		locale: z.string(),
		timeZone: z.string(),
		allowFreesale: z.boolean(),
		instantConfirmation: z.boolean(),
		instantDelivery: z.boolean(),
		availabilityRequired: z.boolean(),
		availabilityType: availabilityTypeSchema,
		deliveryFormats: z.array(deliveryFormatSchema),
		deliveryMethods: z.array(deliveryMethodSchema),
		redemptionMethod: redemptionMethodSchema,
		tags: z.array(z.string()),
		settlementMethods: z.array(settlementMethodSchema),
		freesaleDurationAmount: z.number(),
		freesaleDurationUnit: durationUnitSchema,
		options: z.array(optionSchema),
		country: z.string().optional(),
		location: z.string().optional(),
		destination: destinationSchema.optional(),
		alert: z.string().optional().nullable(),
		title: z.string().optional(),
		subtitle: z.string().optional().nullable(),
		description: z.string().optional().nullable(),
		shortDescription: z.string().optional().nullable(),
		categories: z.array(categorySchema).optional(),
		inclusions: z.array(z.string()).optional(),
		exclusions: z.array(z.string()).optional(),
		highlights: z.array(z.string()).optional(),
		pointToPoint: z.boolean().optional(),
		bookingTerms: z.string().optional().nullable(),
		privacyTerms: z.string().optional().nullable(),
		redemptionInstructions: z.string().optional().nullable(),
		cancellationPolicy: z.string().optional().nullable(),
		faqs: z.array(fAQSchema).optional(),
		coverImageUrl: z.string().optional().nullable(),
		bannerImageUrl: z.string().optional().nullable(),
		videoUrl: z.string().optional().nullable(),
		galleryImages: z.array(imageSchema).optional(),
		bannerImages: z.array(imageSchema).optional(),
		googlePlaceId: z.string().optional().nullable(),
		latitude: z.number().optional(),
		longitude: z.number().optional(),
		address: z.string().optional(),
		keywords: z.array(z.string()).optional(),
		tagline: z.string().optional().nullable(),
		brand: brandSchema.optional(),
		defaultCurrency: z.string().optional(),
		availableCurrencies: z.array(z.string()).optional(),
		pricingPer: pricingPerSchema.optional(),
		includeTax: z.boolean().optional(),
		isPackage: z.boolean().optional(),
		packageBookingAvailabilityRequired: z.boolean().optional(),
		googleOptions: googleOptionsSchema.optional(),
		isMembership: z.boolean().optional(),
		isRental: z.boolean().optional(),
	}),
);
