// Generated by ts-to-zod
import * as z from 'zod';
import { googleOptionsSchema } from './GoogleOptions';

export const productGoogleSchema = z.object({
	googleOptions: googleOptionsSchema.optional(),
});
