// Generated by ts-to-zod
import * as z from 'zod';

export const productPackagesSchema = z.object({
	isPackage: z.boolean().optional(),
	packageBookingAvailabilityRequired: z.boolean().optional(),
	packageProduct: z.boolean().optional(),
});
