// Generated by ts-to-zod
import { z } from "zod";
import { questionInputTypeSchema } from "./QuestionInputType";
import { selectOptionSchema } from "./SelectOption";

export const questionSchema = z.object({
    id: z.string(),
    label: z.string().nullable(),
    hint: z.string().nullable(),
    maxLength: z.number().nullable(),
    inputType: questionInputTypeSchema,
    required: z.boolean(),
    selectOptions: z.array(selectOptionSchema),
    coverImageUrl: z.string().nullable(),
    description: z.string().nullable(),
    shortDescription: z.string().nullable(),
    internalName: z.string().nullable(),
    title: z.string().nullable()
});
