// Generated by ts-to-zod
import * as z from 'zod';
import { questionSchema } from './Question';

export const questionAnswerSchema = z.object({
	questionId: z.string(),
	question: questionSchema,
	value: z.string().nullable(),
});
