// Generated by ts-to-zod
import { z } from 'zod';
import { bookingStatusSchema } from './BookingStatus';
import { productSchema } from './Product';
import { optionSchema } from './Option';
import { cancellationSchema } from './Cancellation';
import { availabilitySchema } from './Availability';
import { customerContactSchema } from './CustomerContact';
import { deliveryMethodSchema } from './DeliveryMethod';
import { ticketSchema } from './Ticket';
import { unitItemSchema } from './UnitItem';
import { pricingSchema } from './Pricing';
import { settlementMethodSchema } from './SettlementMethod';
import { agentSchema } from './Agent';
import { resellerSchema } from './Reseller';
import { contactFieldSchema } from './ContactField';
import { bookingRejectionSchema } from './BookingRejection';
import { userSchema } from './User';
import { sellerSchema } from './Seller';
import { labelSchema } from './Label';
import { pickupPointSchema } from './PickupPoint';
import { durationUnitSchema } from './DurationUnit';
import { noticeSchema } from './Notice';
import { offerComparisonSchema } from './OfferComparison';
import { offerSchema } from './Offer';
import { questionAnswerSchema } from './QuestionAnswer';
import { resourceAllocationSchema } from './ResourceAllocation';
import { giftPaymentSchema } from './GiftPayment';
import { extraItemSchema } from './ExtraItem';
import { extraPricingSchema } from './ExtraPricing';
import { includeSchema } from './Include';
import { bookingSchema } from './Booking';
import { bookingAdjustmentSchema } from './BookingAdjustment';
import { identitySchema } from './Identity';
import { membershipBenefitSchema } from './MembershipBenefit';
import { membershipSchema } from './Membership';
import { rentalDurationSchema } from './RentalDuration';
import { cardPaymentGatewaySchema } from './CardPaymentGateway';

export const redemptionLookupSchema = z.object({
	redemptionCode: z.string(),
	redeemable: z.boolean(),
	unredeemableReason: z.string(),
	unredeemableReasonCode: z.string(),
	id: z.string(),
	uuid: z.string(),
	testMode: z.boolean(),
	resellerReference: z.string().nullable(),
	supplierReference: z.string().nullable(),
	status: bookingStatusSchema,
	utcCreatedAt: z.string(),
	utcUpdatedAt: z.string(),
	utcExpiresAt: z.string().nullable(),
	utcRedeemedAt: z.string().nullable(),
	utcConfirmedAt: z.string().nullable(),
	productId: z.string(),
	product: productSchema.optional(),
	optionId: z.string(),
	option: optionSchema,
	cancellable: z.boolean(),
	cancellation: cancellationSchema.nullable(),
	freesale: z.boolean(),
	availabilityId: z.string().nullable(),
	availability: availabilitySchema.optional().nullable(),
	contact: customerContactSchema.optional(),
	notes: z.string().nullable(),
	deliveryMethods: z.array(deliveryMethodSchema),
	voucher: ticketSchema.nullable(),
	unitItems: z.array(unitItemSchema),
	pricing: pricingSchema.optional(),
	rebookingUuid: z.string().nullable(),
	originalRebookingUuid: z.string().nullable(),
	alias: z.string().nullable(),
	settlementMethod: settlementMethodSchema,
	quote: z.boolean(),
	confirmable: z.boolean(),
	agent: agentSchema.nullable(),
	reseller: resellerSchema.nullable(),
	requiredContactFields: z.array(contactFieldSchema),
	visibleContactFields: z.array(contactFieldSchema),
	rejection: bookingRejectionSchema.nullable(),
	utcNoshowedAt: z.string().nullable(),
	utcRebookedAt: z.string().nullable(),
	tags: z.array(z.string()).optional(),
	user: userSchema.nullable(),
	seller: sellerSchema.nullable(),
	localDateTimeStart: z.string(),
	localDateTimeEnd: z.string(),
	emailReceipt: z.boolean(),
	label: labelSchema.nullable(),
	metadata: z.record(z.any()),
	updatable: z.boolean(),
	availabilityLocalDateStart: z.string().nullable(),
	availabilityLocalDateEnd: z.string().nullable(),
	guide: sellerSchema.nullable(),
	driver: sellerSchema.nullable(),
	active: z.boolean(),
	pickupRequested: z.boolean().optional(),
	pickupHotel: z.string().optional().nullable(),
	pickupRoom: z.string().optional().nullable(),
	pickupNotes: z.string().optional().nullable(),
	pickupPoint: pickupPointSchema.optional().nullable(),
	pickupPointId: z.string().optional().nullable(),
	pickupHotelRoom: z.string().optional().nullable(),
	pickupDispatch: z.string().optional().nullable(),
	dropoffDispatch: z.string().optional().nullable(),
	duration: z.string().optional(),
	durationAmount: z.number().optional(),
	durationUnit: durationUnitSchema.optional(),
	meetingLocalDateTime: z.string().optional().nullable(),
	meetingPoint: z.string().optional().nullable(),
	meetingPointCoordinates: z.string().optional().nullable(),
	meetingPointDirections: z.string().optional().nullable(),
	notices: z.array(noticeSchema).optional(),
	termsAccepted: z.boolean().optional(),
	primary: z.boolean().optional(),
	orderId: z.string().optional(),
	orderReference: z.string().optional(),
	offerCode: z.string().optional().nullable(),
	offerTitle: z.string().optional().nullable(),
	offerComparisons: z.array(offerComparisonSchema).optional(),
	offerIsCombination: z.boolean().optional(),
	offers: z.array(offerSchema).optional(),
	offer: offerSchema.optional().nullable(),
	questionAnswers: z.array(questionAnswerSchema).optional(),
	resourceAllocations: z.array(resourceAllocationSchema).optional(),
	giftPayment: giftPaymentSchema.optional().nullable(),
	extraItems: z.array(extraItemSchema).optional(),
	extraPricing: z.array(extraPricingSchema).optional(),
	isPackage: z.boolean().optional(),
	packageIncludeId: z.string().optional().nullable(),
	packageInclude: includeSchema.optional().nullable(),
	packageBookings: z.array(bookingSchema).optional(),
	packageUnitItemUuid: z.any().optional(),
	adjustments: z.array(bookingAdjustmentSchema).optional(),
	identity: identitySchema.optional(),
	identityId: z.string().optional(),
	checkedIn: z.boolean().optional(),
	checkinAvailable: z.boolean().optional(),
	checkinUrl: z.string().optional().nullable(),
	membershipBenefit: membershipBenefitSchema.optional().nullable(),
	membership: membershipSchema.optional().nullable(),
	isMembership: z.boolean().optional(),
	appendMembershipValidity: z.boolean().optional(),
	isRental: z.boolean().optional(),
	rentalDurationId: z.string().optional().nullable(),
	rentalDuration: rentalDurationSchema.optional().nullable(),
	cardPayment: cardPaymentGatewaySchema.optional().nullable(),
	returnUrl: z.string().optional().nullable(),
});
