// Generated by ts-to-zod
import { z } from 'zod';
import { durationUnitSchema } from './DurationUnit';

export const rentalDurationSchema = z.object({
	id: z.string(),
	title: z.string(),
	shortDescription: z.string().nullable(),
	durationAmount: z.number(),
	durationUnit: durationUnitSchema,
	pricingMultiplier: z.number(),
});
