// Generated by ts-to-zod
import { z } from "zod";
import { seatSchema } from "./Seat";

export const resourceSchema = z.object({
    id: z.string(),
    title: z.string(),
    seating: z.boolean(),
    seats: z.array(seatSchema)
});
