// Generated by ts-to-zod
import { z } from "zod";
import { resourceGroupSchema } from "./ResourceGroup";
import { resourceSchema } from "./Resource";
import { seatSchema } from "./Seat";

export const resourceAllocationSchema = z.object({
    id: z.string(),
    resourceGroupId: z.string(),
    resourceGroup: resourceGroupSchema,
    resourceId: z.string(),
    resource: resourceSchema,
    paxCount: z.number(),
    seatIds: z.array(z.string()),
    seats: z.array(seatSchema)
});
