// Generated by ts-to-zod
import { z } from 'zod';

export const spreedlyGatewaySchema = z.object({
	env: z.string().optional(),
	nonce: z.string().optional(),
	timestamp: z.string().optional(),
	certificateToken: z.string().optional(),
	signature: z.string().optional(),
});
