// Generated by ts-to-zod
import { z } from 'zod';

export const stripeGatewaySchema = z.object({
	version: z.string().optional(),
	paymentIntent: z
		.object({
			id: z.string(),
			publishableKey: z.string(),
			clientSecret: z.string(),
			amount: z.number(),
			currency: z.string(),
		})
		.optional()
		.nullable(),
	setupIntent: z
		.object({
			id: z.string(),
			publishableKey: z.string(),
			clientSecret: z.string(),
		})
		.optional(),
});
