// Generated by ts-to-zod
import * as z from 'zod';

export const supplierContactSchema = z.object({
	website: z.string().nullable(),
	email: z.string().nullable(),
	telephone: z.string().nullable(),
	address: z.string().nullable(),
});
