// Generated by ts-to-zod
import * as z from 'zod';
import { destinationSchema } from './Destination';

export const supplierContentSchema = z.object({
	country: z.string().optional().nullable(),
	destinations: z.array(destinationSchema).optional(),
});
