// Generated by ts-to-zod
import { z } from 'zod';
import { supplierContactSchema } from './SupplierContact';
import { destinationSchema } from './Destination';

export const supplierSchema = z.object({
	id: z.string(),
	name: z.string(),
	endpoint: z.string(),
	contact: supplierContactSchema,
	country: z.string().optional().nullable(),
	destinations: z.array(destinationSchema).optional(),
});
