// Generated by ts-to-zod
import { z } from 'zod';
import { supplierContactSchema } from './SupplierContact';
import { octo_MediaSchema } from './Octo_Media';
import { destinationSchema } from './Destination';

export const supplierSchema = z.object({
	id: z.string(),
	name: z.string(),
	endpoint: z.string(),
	contact: supplierContactSchema,
	shortDescription: z.string().optional().nullable(),
	media: z.array(octo_MediaSchema).optional(),
	country: z.string().optional().nullable(),
	destinations: z.array(destinationSchema).optional(),
});
