// Generated by ts-to-zod
import { z } from "zod";

export const unitItemIdentifierSchema = z.object({
    uuid: z.string().optional(),
    unitId: z.string().optional(),
    unitType: z.string().optional(),
    resellerReference: z.string().optional(),
    alias: z.string().optional()
});
