// Generated by ts-to-zod
import * as z from 'zod';
import { extraItemSchema } from './ExtraItem';

export const unitItemExtrasSchema = z.object({
	extraItems: z.array(extraItemSchema).optional(),
});
