// Generated by ts-to-zod
import { z } from 'zod';
import { unitTypeSchema } from './UnitType';
import { contactFieldSchema } from './ContactField';
import { unitRestrictionsSchema } from './UnitRestrictions';
import { pricingSchema } from './Pricing';
import { questionSchema } from './Question';
import { extraSchema } from './Extra';

export const unitSchema = z.object({
	id: z.string(),
	internalName: z.string(),
	reference: z.string().nullable(),
	type: unitTypeSchema,
	requiredContactFields: z.array(contactFieldSchema),
	tags: z.array(z.string()),
	visibleContactFields: z.array(contactFieldSchema),
	restrictions: unitRestrictionsSchema,
	title: z.string().optional(),
	titlePlural: z.string().optional(),
	subtitle: z.string().optional().nullable(),
	pricingFrom: z.array(pricingSchema).optional(),
	pricing: z.array(pricingSchema).optional(),
	questions: z.array(questionSchema).optional(),
	extras: z.array(extraSchema).optional(),
});
