// Generated by ts-to-zod
import { z } from "zod";

export const unitRestrictionsSchema = z.object({
    minAge: z.number(),
    maxAge: z.number(),
    idRequired: z.boolean(),
    minQuantity: z.number().nullable(),
    maxQuantity: z.number().nullable(),
    paxCount: z.number(),
    accompaniedBy: z.array(z.string()),
    minHeight: z.number().optional(),
    maxHeight: z.number().optional(),
    heightUnit: z.string().optional(),
    minWeight: z.number().optional(),
    maxWeight: z.number().optional(),
    weightUnit: z.string().optional(),
    required: z.boolean(),
    accompaniedByRatio: z.number().nullable()
});
