// Generated by ts-to-zod
import { z } from 'zod';
import { unitTypeSchema } from './UnitType';

export const unitRestrictionsSchema = z.object({
	minAge: z.number(),
	maxAge: z.number(),
	idRequired: z.boolean(),
	minQuantity: z.number().nullable(),
	maxQuantity: z.number().nullable(),
	paxCount: z.number(),
	accompaniedBy: z.array(unitTypeSchema),
	minHeight: z.number().optional(),
	maxHeight: z.number().optional(),
	heightUnit: z.string().optional(),
	minWeight: z.number().optional(),
	maxWeight: z.number().optional(),
	weightUnit: z.string().optional(),
	required: z.boolean(),
	accompaniedByRatio: z.number().nullable(),
	accompaniedByRatioDenominator: z.number().optional(),
	notAccompaniedBy: z.array(unitTypeSchema),
});
