// Generated by ts-to-zod
import * as z from 'zod';
import { pricingSchema } from './Pricing';

export const unitPricingSchema = z.object({
	pricingFrom: z.array(pricingSchema).optional(),
	pricing: z.array(pricingSchema).optional(),
});
