// Generated by ts-to-zod
import { z } from 'zod';

export const unitContentSchema = z.object({
	title: z.string().optional(),
	titlePlural: z.string().optional(),
	subtitle: z.string().optional().nullable(),
});
