// Generated by ts-to-zod
import { z } from 'zod';
import { unitSchema } from './Unit';
import { bookingStatusSchema } from './BookingStatus';
import { customerContactSchema } from './CustomerContact';
import { ticketSchema } from './Ticket';
import { unitTypeSchema } from './UnitType';
import { pricingSchema } from './Pricing';
import { questionAnswerSchema } from './QuestionAnswer';
import { extraItemSchema } from './ExtraItem';
import { scanSchema } from './Scan';

export const unitItemSchema = z.object({
	uuid: z.string().optional(),
	resellerReference: z.string().nullable(),
	supplierReference: z.string().nullable(),
	unitId: z.string(),
	unit: unitSchema.optional(),
	status: bookingStatusSchema,
	utcRedeemedAt: z.string().nullable(),
	contact: customerContactSchema.optional(),
	ticket: ticketSchema.nullable(),
	id: z.string().optional(),
	alias: z.string().nullable(),
	rebookingUuid: z.string().nullable(),
	rebookingUnitItemUuid: z.string().nullable(),
	originalRebookingUuid: z.string().nullable(),
	originalRebookingUnitItemUuid: z.string().nullable(),
	utcRebookedAt: z.string().nullable(),
	utcNoshowedAt: z.string().nullable(),
	requiredContactFields: z.array(z.string()),
	visibleContactFields: z.array(z.string()),
	unitType: unitTypeSchema,
	localDateTimeStart: z.string().nullable(),
	localDateTimeEnd: z.string().nullable(),
	pricing: pricingSchema.optional(),
	questionAnswers: z.array(questionAnswerSchema).optional(),
	extraItems: z.array(extraItemSchema).optional(),
	scans: z.array(scanSchema).optional(),
});
