// Generated by ts-to-zod
import { z } from 'zod';
import { mappingToUpdateSchema } from './MappingToUpdate';

export const updateMappingsRequestSchema = z.object({
	body: z.array(mappingToUpdateSchema),
});
