// Generated by ts-to-zod
import { z } from 'zod';
import { bookingContactSchema } from './BookingContact';
import { settlementMethodSchema } from './SettlementMethod';

export const updateOrderBodySchema = z.object({
	expirationMinutes: z.number().optional(),
	emailReceipt: z.boolean().optional(),
	contact: bookingContactSchema.optional(),
	quote: z.boolean().optional(),
	settlementMethod: settlementMethodSchema.optional(),
	currency: z.string().optional(),
});
