// Generated by ts-to-zod
import { z } from 'zod';
import { customerContactSchema } from './CustomerContact';
import { giftPaymentSchema } from './GiftPayment';
import { settlementMethodSchema } from './SettlementMethod';

export const updateGiftBodySchema = z.object({
	alias: z.string().optional(),
	amount: z.number().optional(),
	contact: customerContactSchema.optional(),
	currency: z.string().optional(),
	emailReceipt: z.boolean().optional(),
	expirationMinutes: z.number().optional(),
	giftPayment: giftPaymentSchema.optional(),
	message: z.string().optional(),
	notes: z.string().optional(),
	resellerReference: z.string().optional(),
	settlementMethod: settlementMethodSchema.optional(),
});
