// Generated by ts-to-zod
import { z } from 'zod';

export const userSchema = z.object({
	id: z.string(),
	name: z.string(),
	reference: z.string().nullable(),
	tags: z.array(z.string()),
	emailAddress: z.string(),
	phoneNumber: z.string().nullable(),
});
