// Generated by ts-to-zod
import { z } from 'zod';
import { webhookEventSchema } from './WebhookEvent';
import { capabilityIdSchema } from './CapabilityId';

export const webhookSchema = z.object({
	id: z.string(),
	event: webhookEventSchema,
	url: z.string().nullable(),
	function: z.string().nullable(),
	useContactLanguage: z.boolean(),
	headers: z.record(z.string(), z.string()),
	capabilities: z.array(capabilityIdSchema),
});
