// Generated by ts-to-zod
import { z } from 'zod';
import { webhookEventSchema } from './WebhookEvent';
import { capabilitySchema } from './Capability';

export const webhookSchema = z.object({
	id: z.string(),
	event: webhookEventSchema,
	url: z.string().optional(),
	retryOnError: z.boolean(),
	useContactLanguage: z.boolean(),
	headers: z.record(z.string()),
	capabilities: z.array(capabilitySchema),
});
