// Generated by ts-to-zod
import { z } from 'zod';
import { supplierSchema } from './Supplier';
import { connectionSchema } from './Connection';
import { partnerSchema } from './Partner';
import { resellerSchema } from './Reseller';
import { checkoutSchema } from './Checkout';
import { operatorSchema } from './Operator';
import { terminalSchema } from './Terminal';

export const whoAmISchema = z.object({
	supplier: supplierSchema,
	connection: connectionSchema,
	partner: partnerSchema.nullable(),
	reseller: resellerSchema.nullable(),
	checkout: checkoutSchema.nullable(),
	operator: operatorSchema.nullable(),
	terminal: terminalSchema.nullable(),
});
