// Generated by ts-to-zod
import { z } from 'zod';
import { getYourGuideConnectionSchema } from './GetYourGuideConnection';
import { partnerSchema } from './Partner';
import { partnersConnectionSchema } from './PartnersConnection';
import { resellerSchema } from './Reseller';
import { supplierSchema } from './Supplier';

export const whoIAmSchema = z.object({
	supplier: supplierSchema,
	connection: z.union([getYourGuideConnectionSchema, partnersConnectionSchema]),
	partner: partnerSchema,
	reseller: resellerSchema,
	checkout: z.any(),
	operator: z.any(),
	terminal: z.any(),
});
