/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

export { AdjustmentDiscount } from './models/AdjustmentDiscount';
export { AdjustmentPer } from './models/AdjustmentPer';
export type { AdyenGateway } from './models/AdyenGateway';
export type { AdyenGatewaySession } from './models/AdyenGatewaySession';
export type { AdyenPaymentMethodsConfiguration } from './models/AdyenPaymentMethodsConfiguration';
export type { AdyenPaymentMethodsConfigurationApplePay } from './models/AdyenPaymentMethodsConfigurationApplePay';
export { AdyenPaymentMethodsConfigurationCard } from './models/AdyenPaymentMethodsConfigurationCard';
export { AdyenPaymentMethodsConfigurationGooglePay } from './models/AdyenPaymentMethodsConfigurationGooglePay';
export type { AdyenPaymentMethodsConfigurationPayPay } from './models/AdyenPaymentMethodsConfigurationPayPay';
export type { Agent } from './models/Agent';
export type { Availability } from './models/Availability';
export type { AvailabilityCalendar } from './models/AvailabilityCalendar';
export type { AvailabilityCalendarBody } from './models/AvailabilityCalendarBody';
export type { AvailabilityCalendarErrorResponse } from './models/AvailabilityCalendarErrorResponse';
export type { AvailabilityCalendarExtras } from './models/AvailabilityCalendarExtras';
export type { AvailabilityCalendarOffers } from './models/AvailabilityCalendarOffers';
export type { AvailabilityCalendarPricing } from './models/AvailabilityCalendarPricing';
export type { AvailabilityCalendarRequest } from './models/AvailabilityCalendarRequest';
export type { AvailabilityCheckBody } from './models/AvailabilityCheckBody';
export type { AvailabilityCheckErrorResponse } from './models/AvailabilityCheckErrorResponse';
export type { AvailabilityCheckRequest } from './models/AvailabilityCheckRequest';
export type { AvailabilityContent } from './models/AvailabilityContent';
export type { AvailabilityExtras } from './models/AvailabilityExtras';
export type { AvailabilityOffers } from './models/AvailabilityOffers';
export type { AvailabilityPickups } from './models/AvailabilityPickups';
export type { AvailabilityPricing } from './models/AvailabilityPricing';
export type { AvailabilityResources } from './models/AvailabilityResources';
export { AvailabilityStatus } from './models/AvailabilityStatus';
export { AvailabilityType } from './models/AvailabilityType';
export type { AvailabilityUnit } from './models/AvailabilityUnit';
export type { AvailabilityUpdate } from './models/AvailabilityUpdate';
export type { Booking } from './models/Booking';
export type { BookingAdjustment } from './models/BookingAdjustment';
export type { BookingAdjustments } from './models/BookingAdjustments';
export type { BookingCancellation } from './models/BookingCancellation';
export type { BookingCancellationBody } from './models/BookingCancellationBody';
export type { BookingCancellationErrorResponse } from './models/BookingCancellationErrorResponse';
export type { BookingCancellationPathParams } from './models/BookingCancellationPathParams';
export type { BookingCancellationRequest_uuid } from './models/BookingCancellationRequest_uuid';
export type { BookingCardPayments } from './models/BookingCardPayments';
export type { BookingCart } from './models/BookingCart';
export type { BookingCheckin } from './models/BookingCheckin';
export type { BookingConfirmationBody } from './models/BookingConfirmationBody';
export type { BookingConfirmationErrorResponse } from './models/BookingConfirmationErrorResponse';
export type { BookingConfirmationPathParams } from './models/BookingConfirmationPathParams';
export type { BookingConfirmationRequest_uuid } from './models/BookingConfirmationRequest_uuid';
export type { BookingContact } from './models/BookingContact';
export type { BookingContent } from './models/BookingContent';
export type { BookingExtras } from './models/BookingExtras';
export type { BookingGifts } from './models/BookingGifts';
export type { BookingIdentities } from './models/BookingIdentities';
export type { BookingMemberships } from './models/BookingMemberships';
export type { BookingOffers } from './models/BookingOffers';
export type { BookingPackages } from './models/BookingPackages';
export type { BookingPickupBody } from './models/BookingPickupBody';
export type { BookingPickups } from './models/BookingPickups';
export type { BookingPricing } from './models/BookingPricing';
export type { BookingQuestions } from './models/BookingQuestions';
export type { BookingRejection } from './models/BookingRejection';
export type { BookingRentals } from './models/BookingRentals';
export type { BookingReservationBody } from './models/BookingReservationBody';
export type { BookingReservationErrorResponse } from './models/BookingReservationErrorResponse';
export type { BookingReservationRequest } from './models/BookingReservationRequest';
export type { BookingResources } from './models/BookingResources';
export { BookingStatus } from './models/BookingStatus';
export type { BookingUpdate } from './models/BookingUpdate';
export type { BookingUpdateBody } from './models/BookingUpdateBody';
export type { BookingUpdatePathParams } from './models/BookingUpdatePathParams';
export type { BookingUpdateRequest_uuid } from './models/BookingUpdateRequest_uuid';
export type { Brand } from './models/Brand';
export type { BrandContact } from './models/BrandContact';
export type { BridgepayGateway } from './models/BridgepayGateway';
export type { CancelOrderBody } from './models/CancelOrderBody';
export type { CancelOrderRequest_id } from './models/CancelOrderRequest_id';
export type { Capability } from './models/Capability';
export { CapabilityId } from './models/CapabilityId';
export type { Card } from './models/Card';
export type { CardPayment } from './models/CardPayment';
export type { Category } from './models/Category';
export type { ConfirmOrderBody } from './models/ConfirmOrderBody';
export type { ConfirmOrderPricingBody } from './models/ConfirmOrderPricingBody';
export type { ConfirmOrderRequest_id } from './models/ConfirmOrderRequest_id';
export { ContactField } from './models/ContactField';
export type { CreateOrderBody } from './models/CreateOrderBody';
export type { CreateOrderPricingBody } from './models/CreateOrderPricingBody';
export type { CreateOrderRequest_id } from './models/CreateOrderRequest_id';
export type { CreateWaitlistRequest } from './models/CreateWaitlistRequest';
export type { CreateWebhookBody } from './models/CreateWebhookBody';
export type { CreateWebhookRequest } from './models/CreateWebhookRequest';
export type { CreateWebhookRequestHeaders_octoCapabilities } from './models/CreateWebhookRequestHeaders_octoCapabilities';
export type { CustomerContact } from './models/CustomerContact';
export type { DefaultableID } from './models/DefaultableID';
export type { DeleteWebhookPathParams } from './models/DeleteWebhookPathParams';
export type { DeleteWebhookRequest_id } from './models/DeleteWebhookRequest_id';
export type { DeleteWebhookRequestHeaders_octoCapabilities } from './models/DeleteWebhookRequestHeaders_octoCapabilities';
export { DeliveryFormat } from './models/DeliveryFormat';
export { DeliveryMethod } from './models/DeliveryMethod';
export type { DeliveryOption } from './models/DeliveryOption';
export type { Destination } from './models/Destination';
export type { DestinationContact } from './models/DestinationContact';
export type { DestinationPricing } from './models/DestinationPricing';
export type { Diff } from './models/Diff';
export { DurationUnit } from './models/DurationUnit';
export type { ExtendOrderBody } from './models/ExtendOrderBody';
export type { ExtendOrderRequest_id } from './models/ExtendOrderRequest_id';
export type { ExtendReservationBody } from './models/ExtendReservationBody';
export type { ExtendReservationErrorResponse } from './models/ExtendReservationErrorResponse';
export type { ExtendReservationPathParams } from './models/ExtendReservationPathParams';
export type { ExtendReservationRequest_uuid } from './models/ExtendReservationRequest_uuid';
export type { ExternalGateway } from './models/ExternalGateway';
export type { Extra } from './models/Extra';
export type { ExtraItem } from './models/ExtraItem';
export type { ExtraPricing } from './models/ExtraPricing';
export type { ExtraRestrictions } from './models/ExtraRestrictions';
export type { FAQ } from './models/FAQ';
export type { Font } from './models/Font';
export type { GetBookingRequest } from './models/GetBookingRequest';
export type { GetBookingsRequest } from './models/GetBookingsRequest';
export type { GetMappingsQueryParams_optionId } from './models/GetMappingsQueryParams_optionId';
export type { GetMappingsQueryParams_productId } from './models/GetMappingsQueryParams_productId';
export type { GetMappingsQueryParams_resellerReference } from './models/GetMappingsQueryParams_resellerReference';
export type { GetMappingsQueryParams_resellerStatus } from './models/GetMappingsQueryParams_resellerStatus';
export type { GetMappingsRequest } from './models/GetMappingsRequest';
export type { GetOrderRequest_id } from './models/GetOrderRequest_id';
export type { GetProductRequest } from './models/GetProductRequest';
export type { GetProductsRequest } from './models/GetProductsRequest';
export type { GetSupplierRequest } from './models/GetSupplierRequest';
export type { GetYourGuideActivateBody } from './models/GetYourGuideActivateBody';
export type { GetYourGuideActivateRequest } from './models/GetYourGuideActivateRequest';
export type { GetYourGuideActivateRequestHeaders_octoCapabilities } from './models/GetYourGuideActivateRequestHeaders_octoCapabilities';
export type { GetYourGuideConnection } from './models/GetYourGuideConnection';
export type { Gift } from './models/Gift';
export type { GiftCardPayments } from './models/GiftCardPayments';
export type { GiftIdentities } from './models/GiftIdentities';
export type { GiftPayment } from './models/GiftPayment';
export type { GoogleLocalizedText } from './models/GoogleLocalizedText';
export type { GoogleLocation } from './models/GoogleLocation';
export type { GoogleOperator } from './models/GoogleOperator';
export type { GoogleOptionCategory } from './models/GoogleOptionCategory';
export type { GoogleOptions } from './models/GoogleOptions';
export type { GoogleRating } from './models/GoogleRating';
export type { GoogleRelatedLocation } from './models/GoogleRelatedLocation';
export type { GoogleUrl } from './models/GoogleUrl';
export type { Identity } from './models/Identity';
export type { Image } from './models/Image';
export type { Include } from './models/Include';
export type { ItineraryItem } from './models/ItineraryItem';
export { ItineraryItemType } from './models/ItineraryItemType';
export type { Label } from './models/Label';
export type { ListCapabilitiesRequest } from './models/ListCapabilitiesRequest';
export type { ListCapabilitiesRequestHeaders } from './models/ListCapabilitiesRequestHeaders';
export type { ListOrdersRequest } from './models/ListOrdersRequest';
export type { ListWebhooksRequest } from './models/ListWebhooksRequest';
export type { ListWebhooksRequestHeaders_octoCapabilities } from './models/ListWebhooksRequestHeaders_octoCapabilities';
export type { Mapping } from './models/Mapping';
export type { MappingToUpdate } from './models/MappingToUpdate';
export { MediaRel } from './models/MediaRel';
export { MediaType } from './models/MediaType';
export type { Membership } from './models/Membership';
export type { MembershipBenefit } from './models/MembershipBenefit';
export { NetDiscount } from './models/NetDiscount';
export type { Notice } from './models/Notice';
export type { Octo_AvailabilityCalendarErrorResponse } from './models/Octo_AvailabilityCalendarErrorResponse';
export type { Octo_AvailabilityCheckErrorResponse } from './models/Octo_AvailabilityCheckErrorResponse';
export type { Octo_BaseError } from './models/Octo_BaseError';
export type { Octo_BookingCancellationBody } from './models/Octo_BookingCancellationBody';
export type { Octo_BookingCancellationErrorResponse } from './models/Octo_BookingCancellationErrorResponse';
export type { Octo_BookingConfirmationErrorResponse } from './models/Octo_BookingConfirmationErrorResponse';
export type { Octo_BookingReservationErrorResponse } from './models/Octo_BookingReservationErrorResponse';
export { Octo_CapabilityId } from './models/Octo_CapabilityId';
export { Octo_DeliveryFormat } from './models/Octo_DeliveryFormat';
export type { Octo_ErrorBadRequest } from './models/Octo_ErrorBadRequest';
export type { Octo_ErrorForbidden } from './models/Octo_ErrorForbidden';
export type { Octo_ErrorInternalServerError } from './models/Octo_ErrorInternalServerError';
export type { Octo_ErrorInvalidAvailabilityID } from './models/Octo_ErrorInvalidAvailabilityID';
export type { Octo_ErrorInvalidBookingUUID } from './models/Octo_ErrorInvalidBookingUUID';
export type { Octo_ErrorInvalidOptionID } from './models/Octo_ErrorInvalidOptionID';
export type { Octo_ErrorInvalidProductID } from './models/Octo_ErrorInvalidProductID';
export type { Octo_ErrorInvalidUnitID } from './models/Octo_ErrorInvalidUnitID';
export type { Octo_ErrorUnauthorized } from './models/Octo_ErrorUnauthorized';
export type { Octo_ErrorUnprocessableEntity } from './models/Octo_ErrorUnprocessableEntity';
export type { Octo_ExtendReservationBody } from './models/Octo_ExtendReservationBody';
export type { Octo_ExtendReservationErrorResponse } from './models/Octo_ExtendReservationErrorResponse';
export type { Octo_GetBookingRequest } from './models/Octo_GetBookingRequest';
export type { Octo_GetBookingRequest_uuid } from './models/Octo_GetBookingRequest_uuid';
export type { Octo_GetBookingsRequest } from './models/Octo_GetBookingsRequest';
export type { Octo_GetBookingsRequest_localDate } from './models/Octo_GetBookingsRequest_localDate';
export type { Octo_GetBookingsRequest_localDateEnd } from './models/Octo_GetBookingsRequest_localDateEnd';
export type { Octo_GetBookingsRequest_localDateStart } from './models/Octo_GetBookingsRequest_localDateStart';
export type { Octo_GetBookingsRequest_optionId } from './models/Octo_GetBookingsRequest_optionId';
export type { Octo_GetBookingsRequest_productId } from './models/Octo_GetBookingsRequest_productId';
export type { Octo_GetBookingsRequest_resellerReference } from './models/Octo_GetBookingsRequest_resellerReference';
export type { Octo_GetBookingsRequest_supplierReference } from './models/Octo_GetBookingsRequest_supplierReference';
export type { Octo_GetProductRequest } from './models/Octo_GetProductRequest';
export type { Octo_GetProductRequest_id } from './models/Octo_GetProductRequest_id';
export type { Octo_GetProductsRequest } from './models/Octo_GetProductsRequest';
export type { Octo_GetSupplierRequest } from './models/Octo_GetSupplierRequest';
export type { Octo_Media } from './models/Octo_Media';
export type { Octo_RequestHeaders } from './models/Octo_RequestHeaders';
export type { Octo_RequestHeaders_octoCapabilities } from './models/Octo_RequestHeaders_octoCapabilities';
export type { Octo_RequestHeadersContent } from './models/Octo_RequestHeadersContent';
export type { Octo_ResponseHeaders } from './models/Octo_ResponseHeaders';
export type { Offer } from './models/Offer';
export type { OfferCombination } from './models/OfferCombination';
export type { OfferComparison } from './models/OfferComparison';
export type { OfferDiscount } from './models/OfferDiscount';
export type { OfferMemberships } from './models/OfferMemberships';
export type { OfferRestrictions } from './models/OfferRestrictions';
export type { OfferTax } from './models/OfferTax';
export type { OpeningHours } from './models/OpeningHours';
export type { OpeningHoursContent } from './models/OpeningHoursContent';
export type { Option } from './models/Option';
export type { OptionContent } from './models/OptionContent';
export type { OptionExtras } from './models/OptionExtras';
export type { OptionPackages } from './models/OptionPackages';
export type { OptionPickups } from './models/OptionPickups';
export type { OptionPricing } from './models/OptionPricing';
export type { OptionQuestions } from './models/OptionQuestions';
export type { OptionRentals } from './models/OptionRentals';
export type { OptionRestrictions } from './models/OptionRestrictions';
export type { Order } from './models/Order';
export type { OrderCardPayments } from './models/OrderCardPayments';
export type { OrderCheckin } from './models/OrderCheckin';
export type { OrderContent } from './models/OrderContent';
export type { OrderGifts } from './models/OrderGifts';
export type { OrderIdentities } from './models/OrderIdentities';
export type { OrderMemberships } from './models/OrderMemberships';
export type { OrderOffers } from './models/OrderOffers';
export type { OrderPathParams } from './models/OrderPathParams';
export type { OrderPricing } from './models/OrderPricing';
export type { OrderQuestions } from './models/OrderQuestions';
export type { PackageInclude } from './models/PackageInclude';
export type { Partner } from './models/Partner';
export { PartnerEnum } from './models/PartnerEnum';
export type { PartnersConnection } from './models/PartnersConnection';
export type { PartnersListConnection } from './models/PartnersListConnection';
export type { PartnersListConnectionsRequest } from './models/PartnersListConnectionsRequest';
export type { PartnersListConnectionsRequestHeaders } from './models/PartnersListConnectionsRequestHeaders';
export type { PartnersListConnectionsRequestHeaders_octoCapabilities } from './models/PartnersListConnectionsRequestHeaders_octoCapabilities';
export type { PartnersListConnectionsRequestHeaders_ventrataPartnerKey } from './models/PartnersListConnectionsRequestHeaders_ventrataPartnerKey';
export type { PaypalGateway } from './models/PaypalGateway';
export type { PaytrGateway } from './models/PaytrGateway';
export type { PeachGateway } from './models/PeachGateway';
export type { PickupPoint } from './models/PickupPoint';
export type { Point } from './models/Point';
export type { PointGroup } from './models/PointGroup';
export type { Pricing } from './models/Pricing';
export type { PricingExtras } from './models/PricingExtras';
export type { PricingOffers } from './models/PricingOffers';
export { PricingPer } from './models/PricingPer';
export type { PricingUnit } from './models/PricingUnit';
export type { PricingUnitExtras } from './models/PricingUnitExtras';
export type { Product } from './models/Product';
export type { ProductContent } from './models/ProductContent';
export type { ProductGoogle } from './models/ProductGoogle';
export type { ProductMemberships } from './models/ProductMemberships';
export type { ProductPackages } from './models/ProductPackages';
export type { ProductPricing } from './models/ProductPricing';
export type { ProductRentals } from './models/ProductRentals';
export type { Question } from './models/Question';
export type { QuestionAnswer } from './models/QuestionAnswer';
export { QuestionInputType } from './models/QuestionInputType';
export type { RealaxGateway } from './models/RealaxGateway';
export { RedemptionMethod } from './models/RedemptionMethod';
export { Refund } from './models/Refund';
export type { RentalDuration } from './models/RentalDuration';
export type { RequestHeaders } from './models/RequestHeaders';
export type { Reseller } from './models/Reseller';
export { ResellerStatus } from './models/ResellerStatus';
export type { Resource } from './models/Resource';
export type { ResourceAllocation } from './models/ResourceAllocation';
export type { ResourceGroup } from './models/ResourceGroup';
export type { ResponseHeaders } from './models/ResponseHeaders';
export type { Scan } from './models/Scan';
export type { Seat } from './models/Seat';
export type { SelectOption } from './models/SelectOption';
export type { Seller } from './models/Seller';
export { SettlementMethod } from './models/SettlementMethod';
export type { SpreedlyGateway } from './models/SpreedlyGateway';
export type { StripeGateway } from './models/StripeGateway';
export type { Supplier } from './models/Supplier';
export type { SupplierContact } from './models/SupplierContact';
export type { SupplierContent } from './models/SupplierContent';
export type { Tax } from './models/Tax';
export type { Ticket } from './models/Ticket';
export type { TourGroup } from './models/TourGroup';
export type { Unit } from './models/Unit';
export type { UnitContent } from './models/UnitContent';
export type { UnitExtras } from './models/UnitExtras';
export type { UnitItem } from './models/UnitItem';
export type { UnitItemExtras } from './models/UnitItemExtras';
export type { UnitItemIdentifier } from './models/UnitItemIdentifier';
export type { UnitItemPricing } from './models/UnitItemPricing';
export type { UnitItemQuestions } from './models/UnitItemQuestions';
export type { UnitItemRedemption } from './models/UnitItemRedemption';
export type { UnitMemberships } from './models/UnitMemberships';
export type { UnitPricing } from './models/UnitPricing';
export type { UnitQuestions } from './models/UnitQuestions';
export type { UnitRestrictions } from './models/UnitRestrictions';
export { UnitType } from './models/UnitType';
export type { UpdateMappingsRequest } from './models/UpdateMappingsRequest';
export type { UpdateOrderBody } from './models/UpdateOrderBody';
export type { UpdateOrderPricingBody } from './models/UpdateOrderPricingBody';
export type { UpdateOrderRequest_id } from './models/UpdateOrderRequest_id';
export type { User } from './models/User';
export type { UUID } from './models/UUID';
export type { VivawalletGateway } from './models/VivawalletGateway';
export type { Waitlist } from './models/Waitlist';
export type { WaitlistUnitIdentifier } from './models/WaitlistUnitIdentifier';
export type { WaitlistUnitItemIdentifier } from './models/WaitlistUnitItemIdentifier';
export type { Webhook } from './models/Webhook';
export { WebhookEvent } from './models/WebhookEvent';
export type { WhoIAm } from './models/WhoIAm';
export type { WhoIAmRequest } from './models/WhoIAmRequest';

// Zod Schemas
export { whoIAmRequestSchema } from './schemas/WhoIAmRequest';
export { whoIAmSchema } from './schemas/WhoIAm';
export { webhookEventSchema } from './schemas/WebhookEvent';
export { webhookSchema } from './schemas/Webhook';
export { waitlistUnitItemIdentifierSchema } from './schemas/WaitlistUnitItemIdentifier';
export { waitlistUnitIdentifierSchema } from './schemas/WaitlistUnitIdentifier';
export { waitlistSchema } from './schemas/Waitlist';
export { vivawalletGatewaySchema } from './schemas/VivawalletGateway';
export { userSchema } from './schemas/User';
export { updateOrderRequest_idSchema } from './schemas/UpdateOrderRequest_id';
export { updateOrderPricingBodySchema } from './schemas/UpdateOrderPricingBody';
export { updateOrderBodySchema } from './schemas/UpdateOrderBody';
export { updateMappingsRequestSchema } from './schemas/UpdateMappingsRequest';
export { unitTypeSchema } from './schemas/UnitType';
export { unitRestrictionsSchema } from './schemas/UnitRestrictions';
export { unitQuestionsSchema } from './schemas/UnitQuestions';
export { unitPricingSchema } from './schemas/UnitPricing';
export { unitMembershipsSchema } from './schemas/UnitMemberships';
export { unitItemRedemptionSchema } from './schemas/UnitItemRedemption';
export { unitItemQuestionsSchema } from './schemas/UnitItemQuestions';
export { unitItemPricingSchema } from './schemas/UnitItemPricing';
export { unitItemIdentifierSchema } from './schemas/UnitItemIdentifier';
export { unitItemExtrasSchema } from './schemas/UnitItemExtras';
export { unitItemSchema } from './schemas/UnitItem';
export { unitExtrasSchema } from './schemas/UnitExtras';
export { unitContentSchema } from './schemas/UnitContent';
export { unitSchema } from './schemas/Unit';
export { uUIDSchema } from './schemas/UUID';
export { tourGroupSchema } from './schemas/TourGroup';
export { ticketSchema } from './schemas/Ticket';
export { taxSchema } from './schemas/Tax';
export { supplierContentSchema } from './schemas/SupplierContent';
export { supplierContactSchema } from './schemas/SupplierContact';
export { supplierSchema } from './schemas/Supplier';
export { stripeGatewaySchema } from './schemas/StripeGateway';
export { spreedlyGatewaySchema } from './schemas/SpreedlyGateway';
export { settlementMethodSchema } from './schemas/SettlementMethod';
export { sellerSchema } from './schemas/Seller';
export { selectOptionSchema } from './schemas/SelectOption';
export { seatSchema } from './schemas/Seat';
export { scanSchema } from './schemas/Scan';
export { responseHeadersSchema } from './schemas/ResponseHeaders';
export { resourceGroupSchema } from './schemas/ResourceGroup';
export { resourceAllocationSchema } from './schemas/ResourceAllocation';
export { resourceSchema } from './schemas/Resource';
export { resellerStatusSchema } from './schemas/ResellerStatus';
export { resellerSchema } from './schemas/Reseller';
export { requestHeadersSchema } from './schemas/RequestHeaders';
export { rentalDurationSchema } from './schemas/RentalDuration';
export { refundSchema } from './schemas/Refund';
export { redemptionMethodSchema } from './schemas/RedemptionMethod';
export { realaxGatewaySchema } from './schemas/RealaxGateway';
export { questionInputTypeSchema } from './schemas/QuestionInputType';
export { questionAnswerSchema } from './schemas/QuestionAnswer';
export { questionSchema } from './schemas/Question';
export { productRentalsSchema } from './schemas/ProductRentals';
export { productPricingSchema } from './schemas/ProductPricing';
export { productPackagesSchema } from './schemas/ProductPackages';
export { productMembershipsSchema } from './schemas/ProductMemberships';
export { productGoogleSchema } from './schemas/ProductGoogle';
export { productContentSchema } from './schemas/ProductContent';
export { pricingUnitExtrasSchema } from './schemas/PricingUnitExtras';
export { pricingUnitSchema } from './schemas/PricingUnit';
export { pricingPerSchema } from './schemas/PricingPer';
export { pricingOffersSchema } from './schemas/PricingOffers';
export { pricingExtrasSchema } from './schemas/PricingExtras';
export { pricingSchema } from './schemas/Pricing';
export { pointGroupSchema } from './schemas/PointGroup';
export { pointSchema } from './schemas/Point';
export { pickupPointSchema } from './schemas/PickupPoint';
export { peachGatewaySchema } from './schemas/PeachGateway';
export { paytrGatewaySchema } from './schemas/PaytrGateway';
export { paypalGatewaySchema } from './schemas/PaypalGateway';
export { partnersListConnectionsRequestHeaders_ventrataPartnerKeySchema } from './schemas/PartnersListConnectionsRequestHeaders_ventrataPartnerKey';
export { partnersListConnectionsRequestHeaders_octoCapabilitiesSchema } from './schemas/PartnersListConnectionsRequestHeaders_octoCapabilities';
export { partnersListConnectionsRequestHeadersSchema } from './schemas/PartnersListConnectionsRequestHeaders';
export { partnersListConnectionsRequestSchema } from './schemas/PartnersListConnectionsRequest';
export { partnersListConnectionSchema } from './schemas/PartnersListConnection';
export { partnersConnectionSchema } from './schemas/PartnersConnection';
export { partnerEnumSchema } from './schemas/PartnerEnum';
export { partnerSchema } from './schemas/Partner';
export { packageIncludeSchema } from './schemas/PackageInclude';
export { orderQuestionsSchema } from './schemas/OrderQuestions';
export { orderPricingSchema } from './schemas/OrderPricing';
export { orderPathParamsSchema } from './schemas/OrderPathParams';
export { orderOffersSchema } from './schemas/OrderOffers';
export { orderMembershipsSchema } from './schemas/OrderMemberships';
export { orderIdentitiesSchema } from './schemas/OrderIdentities';
export { orderGiftsSchema } from './schemas/OrderGifts';
export { orderContentSchema } from './schemas/OrderContent';
export { orderCheckinSchema } from './schemas/OrderCheckin';
export { orderCardPaymentsSchema } from './schemas/OrderCardPayments';
export { orderSchema } from './schemas/Order';
export { optionRestrictionsSchema } from './schemas/OptionRestrictions';
export { optionRentalsSchema } from './schemas/OptionRentals';
export { optionQuestionsSchema } from './schemas/OptionQuestions';
export { optionPricingSchema } from './schemas/OptionPricing';
export { optionPickupsSchema } from './schemas/OptionPickups';
export { optionPackagesSchema } from './schemas/OptionPackages';
export { optionExtrasSchema } from './schemas/OptionExtras';
export { optionContentSchema } from './schemas/OptionContent';
export { openingHoursContentSchema } from './schemas/OpeningHoursContent';
export { openingHoursSchema } from './schemas/OpeningHours';
export { offerTaxSchema } from './schemas/OfferTax';
export { offerRestrictionsSchema } from './schemas/OfferRestrictions';
export { offerMembershipsSchema } from './schemas/OfferMemberships';
export { offerDiscountSchema } from './schemas/OfferDiscount';
export { offerComparisonSchema } from './schemas/OfferComparison';
export { offerCombinationSchema } from './schemas/OfferCombination';
export { offerSchema } from './schemas/Offer';
export { octo_TaxSchema } from './schemas/Octo_Tax';
export { octo_ResponseHeadersSchema } from './schemas/Octo_ResponseHeaders';
export { octo_RequestHeaders_octoCapabilitiesSchema } from './schemas/Octo_RequestHeaders_octoCapabilities';
export { octo_RequestHeadersContentSchema } from './schemas/Octo_RequestHeadersContent';
export { octo_RequestHeadersSchema } from './schemas/Octo_RequestHeaders';
export { octo_PricingUnitSchema } from './schemas/Octo_PricingUnit';
export { octo_PricingSchema } from './schemas/Octo_Pricing';
export { octo_OpeningHoursSchema } from './schemas/Octo_OpeningHours';
export { octo_MediaSchema } from './schemas/Octo_Media';
export { octo_GetSupplierRequestSchema } from './schemas/Octo_GetSupplierRequest';
export { octo_GetProductsRequestSchema } from './schemas/Octo_GetProductsRequest';
export { octo_GetProductRequest_idSchema } from './schemas/Octo_GetProductRequest_id';
export { octo_GetProductRequestSchema } from './schemas/Octo_GetProductRequest';
export { octo_GetBookingsRequest_supplierReferenceSchema } from './schemas/Octo_GetBookingsRequest_supplierReference';
export { octo_GetBookingsRequest_resellerReferenceSchema } from './schemas/Octo_GetBookingsRequest_resellerReference';
export { octo_GetBookingsRequest_productIdSchema } from './schemas/Octo_GetBookingsRequest_productId';
export { octo_GetBookingsRequest_optionIdSchema } from './schemas/Octo_GetBookingsRequest_optionId';
export { octo_GetBookingsRequest_localDateStartSchema } from './schemas/Octo_GetBookingsRequest_localDateStart';
export { octo_GetBookingsRequest_localDateEndSchema } from './schemas/Octo_GetBookingsRequest_localDateEnd';
export { octo_GetBookingsRequest_localDateSchema } from './schemas/Octo_GetBookingsRequest_localDate';
export { octo_GetBookingsRequestSchema } from './schemas/Octo_GetBookingsRequest';
export { octo_GetBookingRequest_uuidSchema } from './schemas/Octo_GetBookingRequest_uuid';
export { octo_GetBookingRequestSchema } from './schemas/Octo_GetBookingRequest';
export { octo_ExtendReservationRequest_uuidSchema } from './schemas/Octo_ExtendReservationRequest_uuid';
export { octo_ExtendReservationRequestSchema } from './schemas/Octo_ExtendReservationRequest';
export { octo_ExtendReservationErrorResponseSchema } from './schemas/Octo_ExtendReservationErrorResponse';
export { octo_ExtendReservationBodySchema } from './schemas/Octo_ExtendReservationBody';
export { octo_ErrorUnprocessableEntitySchema } from './schemas/Octo_ErrorUnprocessableEntity';
export { octo_ErrorUnauthorizedSchema } from './schemas/Octo_ErrorUnauthorized';
export { octo_ErrorInvalidUnitIDSchema } from './schemas/Octo_ErrorInvalidUnitID';
export { octo_ErrorInvalidProductIDSchema } from './schemas/Octo_ErrorInvalidProductID';
export { octo_ErrorInvalidOptionIDSchema } from './schemas/Octo_ErrorInvalidOptionID';
export { octo_ErrorInvalidBookingUUIDSchema } from './schemas/Octo_ErrorInvalidBookingUUID';
export { octo_ErrorInvalidAvailabilityIDSchema } from './schemas/Octo_ErrorInvalidAvailabilityID';
export { octo_ErrorInternalServerErrorSchema } from './schemas/Octo_ErrorInternalServerError';
export { octo_ErrorForbiddenSchema } from './schemas/Octo_ErrorForbidden';
export { octo_ErrorBadRequestSchema } from './schemas/Octo_ErrorBadRequest';
export { octo_DeliveryFormatSchema } from './schemas/Octo_DeliveryFormat';
export { octo_CapabilityIdSchema } from './schemas/Octo_CapabilityId';
export { octo_CapabilitySchema } from './schemas/Octo_Capability';
export { octo_BookingUnitItemSchema } from './schemas/Octo_BookingUnitItem';
export { octo_BookingReservationRequestSchema } from './schemas/Octo_BookingReservationRequest';
export { octo_BookingReservationErrorResponseSchema } from './schemas/Octo_BookingReservationErrorResponse';
export { octo_BookingReservationBodySchema } from './schemas/Octo_BookingReservationBody';
export { octo_BookingContactSchema } from './schemas/Octo_BookingContact';
export { octo_BookingConfirmationRequest_uuidSchema } from './schemas/Octo_BookingConfirmationRequest_uuid';
export { octo_BookingConfirmationRequestSchema } from './schemas/Octo_BookingConfirmationRequest';
export { octo_BookingConfirmationErrorResponseSchema } from './schemas/Octo_BookingConfirmationErrorResponse';
export { octo_BookingConfirmationBodySchema } from './schemas/Octo_BookingConfirmationBody';
export { octo_BookingCancellationRequest_uuidSchema } from './schemas/Octo_BookingCancellationRequest_uuid';
export { octo_BookingCancellationRequestSchema } from './schemas/Octo_BookingCancellationRequest';
export { octo_BookingCancellationErrorResponseSchema } from './schemas/Octo_BookingCancellationErrorResponse';
export { octo_BookingCancellationBodySchema } from './schemas/Octo_BookingCancellationBody';
export { octo_BaseErrorSchema } from './schemas/Octo_BaseError';
export { octo_AvailabilityUnitSchema } from './schemas/Octo_AvailabilityUnit';
export { octo_AvailabilityCheckRequestSchema } from './schemas/Octo_AvailabilityCheckRequest';
export { octo_AvailabilityCheckErrorResponseSchema } from './schemas/Octo_AvailabilityCheckErrorResponse';
export { octo_AvailabilityCheckBodySchema } from './schemas/Octo_AvailabilityCheckBody';
export { octo_AvailabilityCalendarRequestSchema } from './schemas/Octo_AvailabilityCalendarRequest';
export { octo_AvailabilityCalendarErrorResponseSchema } from './schemas/Octo_AvailabilityCalendarErrorResponse';
export { octo_AvailabilityCalendarBodySchema } from './schemas/Octo_AvailabilityCalendarBody';
export { octo_AvailabilityCalendarSchema } from './schemas/Octo_AvailabilityCalendar';
export { noticeSchema } from './schemas/Notice';
export { netDiscountSchema } from './schemas/NetDiscount';
export { membershipBenefitSchema } from './schemas/MembershipBenefit';
export { membershipSchema } from './schemas/Membership';
export { mediaTypeSchema } from './schemas/MediaType';
export { mediaRelSchema } from './schemas/MediaRel';
export { mappingToUpdateSchema } from './schemas/MappingToUpdate';
export { mappingSchema } from './schemas/Mapping';
export { listWebhooksRequestHeaders_octoCapabilitiesSchema } from './schemas/ListWebhooksRequestHeaders_octoCapabilities';
export { listWebhooksRequestSchema } from './schemas/ListWebhooksRequest';
export { listOrdersRequestSchema } from './schemas/ListOrdersRequest';
export { listCapabilitiesRequestHeadersSchema } from './schemas/ListCapabilitiesRequestHeaders';
export { listCapabilitiesRequestSchema } from './schemas/ListCapabilitiesRequest';
export { labelSchema } from './schemas/Label';
export { itineraryItemTypeSchema } from './schemas/ItineraryItemType';
export { itineraryItemSchema } from './schemas/ItineraryItem';
export { includeSchema } from './schemas/Include';
export { imageSchema } from './schemas/Image';
export { identitySchema } from './schemas/Identity';
export { googleUrlSchema } from './schemas/GoogleUrl';
export { googleRelatedLocationSchema } from './schemas/GoogleRelatedLocation';
export { googleRatingSchema } from './schemas/GoogleRating';
export { googleOptionsSchema } from './schemas/GoogleOptions';
export { googleOptionCategorySchema } from './schemas/GoogleOptionCategory';
export { googleOperatorSchema } from './schemas/GoogleOperator';
export { googleLocationSchema } from './schemas/GoogleLocation';
export { googleLocalizedTextSchema } from './schemas/GoogleLocalizedText';
export { giftPaymentSchema } from './schemas/GiftPayment';
export { giftIdentitiesSchema } from './schemas/GiftIdentities';
export { giftCardPaymentsSchema } from './schemas/GiftCardPayments';
export { giftSchema } from './schemas/Gift';
export { getYourGuideConnectionSchema } from './schemas/GetYourGuideConnection';
export { getYourGuideActivateRequestHeaders_octoCapabilitiesSchema } from './schemas/GetYourGuideActivateRequestHeaders_octoCapabilities';
export { getYourGuideActivateRequestHeadersSchema } from './schemas/GetYourGuideActivateRequestHeaders';
export { getYourGuideActivateRequestSchema } from './schemas/GetYourGuideActivateRequest';
export { getYourGuideActivateBodySchema } from './schemas/GetYourGuideActivateBody';
export { getSupplierRequestSchema } from './schemas/GetSupplierRequest';
export { getProductsRequestSchema } from './schemas/GetProductsRequest';
export { getProductRequestSchema } from './schemas/GetProductRequest';
export { getOrderRequest_idSchema } from './schemas/GetOrderRequest_id';
export { getMappingsRequestSchema } from './schemas/GetMappingsRequest';
export { getMappingsQueryParams_resellerStatusSchema } from './schemas/GetMappingsQueryParams_resellerStatus';
export { getMappingsQueryParams_resellerReferenceSchema } from './schemas/GetMappingsQueryParams_resellerReference';
export { getMappingsQueryParams_productIdSchema } from './schemas/GetMappingsQueryParams_productId';
export { getMappingsQueryParams_optionIdSchema } from './schemas/GetMappingsQueryParams_optionId';
export { getBookingsRequestSchema } from './schemas/GetBookingsRequest';
export { getBookingRequestSchema } from './schemas/GetBookingRequest';
export { fontSchema } from './schemas/Font';
export { fAQSchema } from './schemas/FAQ';
export { extraRestrictionsSchema } from './schemas/ExtraRestrictions';
export { extraPricingSchema } from './schemas/ExtraPricing';
export { extraItemSchema } from './schemas/ExtraItem';
export { extraSchema } from './schemas/Extra';
export { externalGatewaySchema } from './schemas/ExternalGateway';
export { extendReservationRequest_uuidSchema } from './schemas/ExtendReservationRequest_uuid';
export { extendReservationRequestSchema } from './schemas/ExtendReservationRequest';
export { extendReservationPathParamsSchema } from './schemas/ExtendReservationPathParams';
export { extendReservationErrorResponseSchema } from './schemas/ExtendReservationErrorResponse';
export { extendReservationBodySchema } from './schemas/ExtendReservationBody';
export { extendOrderRequest_idSchema } from './schemas/ExtendOrderRequest_id';
export { extendOrderBodySchema } from './schemas/ExtendOrderBody';
export { durationUnitSchema } from './schemas/DurationUnit';
export { diffSchema } from './schemas/Diff';
export { destinationPricingSchema } from './schemas/DestinationPricing';
export { destinationContactSchema } from './schemas/DestinationContact';
export { destinationSchema } from './schemas/Destination';
export { deliveryOptionSchema } from './schemas/DeliveryOption';
export { deliveryMethodSchema } from './schemas/DeliveryMethod';
export { deliveryFormatSchema } from './schemas/DeliveryFormat';
export { deleteWebhookRequest_idSchema } from './schemas/DeleteWebhookRequest_id';
export { deleteWebhookRequestHeaders_octoCapabilitiesSchema } from './schemas/DeleteWebhookRequestHeaders_octoCapabilities';
export { deleteWebhookPathParamsSchema } from './schemas/DeleteWebhookPathParams';
export { defaultableIDSchema } from './schemas/DefaultableID';
export { customerContactSchema } from './schemas/CustomerContact';
export { createWebhookRequestHeaders_octoCapabilitiesSchema } from './schemas/CreateWebhookRequestHeaders_octoCapabilities';
export { createWebhookRequestSchema } from './schemas/CreateWebhookRequest';
export { createWebhookBodySchema } from './schemas/CreateWebhookBody';
export { createWaitlistRequestSchema } from './schemas/CreateWaitlistRequest';
export { createOrderRequest_idSchema } from './schemas/CreateOrderRequest_id';
export { createOrderPricingBodySchema } from './schemas/CreateOrderPricingBody';
export { createOrderBodySchema } from './schemas/CreateOrderBody';
export { contactFieldSchema } from './schemas/ContactField';
export { confirmOrderRequest_idSchema } from './schemas/ConfirmOrderRequest_id';
export { confirmOrderPricingBodySchema } from './schemas/ConfirmOrderPricingBody';
export { confirmOrderBodySchema } from './schemas/ConfirmOrderBody';
export { categorySchema } from './schemas/Category';
export { cardPaymentSchema } from './schemas/CardPayment';
export { cardSchema } from './schemas/Card';
export { capabilityIdSchema } from './schemas/CapabilityId';
export { capabilitySchema } from './schemas/Capability';
export { cancelOrderRequest_idSchema } from './schemas/CancelOrderRequest_id';
export { cancelOrderBodySchema } from './schemas/CancelOrderBody';
export { bridgepayGatewaySchema } from './schemas/BridgepayGateway';
export { brandContactSchema } from './schemas/BrandContact';
export { brandSchema } from './schemas/Brand';
export { bookingUpdateRequest_uuidSchema } from './schemas/BookingUpdateRequest_uuid';
export { bookingUpdateRequestSchema } from './schemas/BookingUpdateRequest';
export { bookingUpdatePathParamsSchema } from './schemas/BookingUpdatePathParams';
export { bookingUpdateBodySchema } from './schemas/BookingUpdateBody';
export { bookingUpdateSchema } from './schemas/BookingUpdate';
export { bookingStatusSchema } from './schemas/BookingStatus';
export { bookingResourcesSchema } from './schemas/BookingResources';
export { bookingReservationRequestSchema } from './schemas/BookingReservationRequest';
export { bookingReservationErrorResponseSchema } from './schemas/BookingReservationErrorResponse';
export { bookingReservationBodySchema } from './schemas/BookingReservationBody';
export { bookingRentalsSchema } from './schemas/BookingRentals';
export { bookingRejectionSchema } from './schemas/BookingRejection';
export { bookingQuestionsSchema } from './schemas/BookingQuestions';
export { bookingPricingSchema } from './schemas/BookingPricing';
export { bookingPickupsSchema } from './schemas/BookingPickups';
export { bookingPickupBodySchema } from './schemas/BookingPickupBody';
export { bookingPackagesSchema } from './schemas/BookingPackages';
export { bookingOffersSchema } from './schemas/BookingOffers';
export { bookingMembershipsSchema } from './schemas/BookingMemberships';
export { bookingIdentitiesSchema } from './schemas/BookingIdentities';
export { bookingGiftsSchema } from './schemas/BookingGifts';
export { bookingExtrasSchema } from './schemas/BookingExtras';
export { bookingContentSchema } from './schemas/BookingContent';
export { bookingContactSchema } from './schemas/BookingContact';
export { bookingConfirmationRequest_uuidSchema } from './schemas/BookingConfirmationRequest_uuid';
export { bookingConfirmationRequestSchema } from './schemas/BookingConfirmationRequest';
export { bookingConfirmationPathParamsSchema } from './schemas/BookingConfirmationPathParams';
export { bookingConfirmationErrorResponseSchema } from './schemas/BookingConfirmationErrorResponse';
export { bookingConfirmationBodySchema } from './schemas/BookingConfirmationBody';
export { bookingCheckinSchema } from './schemas/BookingCheckin';
export { bookingCartSchema } from './schemas/BookingCart';
export { bookingCardPaymentsSchema } from './schemas/BookingCardPayments';
export { bookingCancellationRequest_uuidSchema } from './schemas/BookingCancellationRequest_uuid';
export { bookingCancellationRequestSchema } from './schemas/BookingCancellationRequest';
export { bookingCancellationPathParamsSchema } from './schemas/BookingCancellationPathParams';
export { bookingCancellationErrorResponseSchema } from './schemas/BookingCancellationErrorResponse';
export { bookingCancellationBodySchema } from './schemas/BookingCancellationBody';
export { bookingCancellationSchema } from './schemas/BookingCancellation';
export { bookingAdjustmentsSchema } from './schemas/BookingAdjustments';
export { bookingAdjustmentSchema } from './schemas/BookingAdjustment';
export { availabilityUpdateSchema } from './schemas/AvailabilityUpdate';
export { availabilityUnitSchema } from './schemas/AvailabilityUnit';
export { availabilityTypeSchema } from './schemas/AvailabilityType';
export { availabilityStatusSchema } from './schemas/AvailabilityStatus';
export { availabilityResourcesSchema } from './schemas/AvailabilityResources';
export { availabilityPricingSchema } from './schemas/AvailabilityPricing';
export { availabilityPickupsSchema } from './schemas/AvailabilityPickups';
export { availabilityOffersSchema } from './schemas/AvailabilityOffers';
export { availabilityExtrasSchema } from './schemas/AvailabilityExtras';
export { availabilityContentSchema } from './schemas/AvailabilityContent';
export { availabilityCheckRequestSchema } from './schemas/AvailabilityCheckRequest';
export { availabilityCheckErrorResponseSchema } from './schemas/AvailabilityCheckErrorResponse';
export { availabilityCheckBodySchema } from './schemas/AvailabilityCheckBody';
export { availabilityCalendarRequestSchema } from './schemas/AvailabilityCalendarRequest';
export { availabilityCalendarPricingSchema } from './schemas/AvailabilityCalendarPricing';
export { availabilityCalendarOffersSchema } from './schemas/AvailabilityCalendarOffers';
export { availabilityCalendarExtrasSchema } from './schemas/AvailabilityCalendarExtras';
export { availabilityCalendarErrorResponseSchema } from './schemas/AvailabilityCalendarErrorResponse';
export { availabilityCalendarBodySchema } from './schemas/AvailabilityCalendarBody';
export { availabilityCalendarSchema } from './schemas/AvailabilityCalendar';
export { availabilitySchema } from './schemas/Availability';
export { agentSchema } from './schemas/Agent';
export { adyenPaymentMethodsConfigurationPayPaySchema } from './schemas/AdyenPaymentMethodsConfigurationPayPay';
export { adyenPaymentMethodsConfigurationGooglePaySchema } from './schemas/AdyenPaymentMethodsConfigurationGooglePay';
export { adyenPaymentMethodsConfigurationGooglePayBillingAddressParametersSchema } from './schemas/AdyenPaymentMethodsConfigurationGooglePay';
export { adyenPaymentMethodsConfigurationCardSchema } from './schemas/AdyenPaymentMethodsConfigurationCard';
export { adyenPaymentMethodsConfigurationCardBillingAddressModeSchema } from './schemas/AdyenPaymentMethodsConfigurationCard';
export { adyenPaymentMethodsConfigurationApplePaySchema } from './schemas/AdyenPaymentMethodsConfigurationApplePay';
export { adyenPaymentMethodsConfigurationSchema } from './schemas/AdyenPaymentMethodsConfiguration';
export { adyenGatewaySessionSchema } from './schemas/AdyenGatewaySession';
export { adyenGatewaySchema } from './schemas/AdyenGateway';
export { adjustmentPerSchema } from './schemas/AdjustmentPer';
export { adjustmentDiscountSchema } from './schemas/AdjustmentDiscount';
