/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

export { AdjustmentDiscount } from './models/AdjustmentDiscount';
export { AdjustmentPer } from './models/AdjustmentPer';
export type { AdyenGateway } from './models/AdyenGateway';
export type { AdyenGatewaySession } from './models/AdyenGatewaySession';
export type { AdyenPaymentMethodsConfiguration } from './models/AdyenPaymentMethodsConfiguration';
export type { AdyenPaymentMethodsConfigurationApplePay } from './models/AdyenPaymentMethodsConfigurationApplePay';
export type { AdyenPaymentMethodsConfigurationCard } from './models/AdyenPaymentMethodsConfigurationCard';
export { AdyenPaymentMethodsConfigurationCardBillingAddressMode } from './models/AdyenPaymentMethodsConfigurationCardBillingAddressMode';
export type { AdyenPaymentMethodsConfigurationGooglePay } from './models/AdyenPaymentMethodsConfigurationGooglePay';
export { AdyenPaymentMethodsConfigurationGooglePayBillingAddressParameters } from './models/AdyenPaymentMethodsConfigurationGooglePayBillingAddressParameters';
export type { AdyenPaymentMethodsConfigurationPayPay } from './models/AdyenPaymentMethodsConfigurationPayPay';
export type { Agent } from './models/Agent';
export type { Article } from './models/Article';
export type { Availability } from './models/Availability';
export type { AvailabilityCalendar } from './models/AvailabilityCalendar';
export type { AvailabilityCalendarBatchBody } from './models/AvailabilityCalendarBatchBody';
export type { AvailabilityCalendarBatchErrorResponse } from './models/AvailabilityCalendarBatchErrorResponse';
export type { AvailabilityCalendarBody } from './models/AvailabilityCalendarBody';
export type { AvailabilityCalendarErrorResponse } from './models/AvailabilityCalendarErrorResponse';
export type { AvailabilityCalendarExtras } from './models/AvailabilityCalendarExtras';
export type { AvailabilityCalendarOffers } from './models/AvailabilityCalendarOffers';
export type { AvailabilityCalendarPricing } from './models/AvailabilityCalendarPricing';
export type { AvailabilityCheckBody } from './models/AvailabilityCheckBody';
export type { AvailabilityCheckErrorResponse } from './models/AvailabilityCheckErrorResponse';
export type { AvailabilityCheckQueryParams } from './models/AvailabilityCheckQueryParams';
export type { AvailabilityContent } from './models/AvailabilityContent';
export type { AvailabilityExtras } from './models/AvailabilityExtras';
export type { AvailabilityMappings } from './models/AvailabilityMappings';
export type { AvailabilityOffers } from './models/AvailabilityOffers';
export type { AvailabilityPackages } from './models/AvailabilityPackages';
export type { AvailabilityPickups } from './models/AvailabilityPickups';
export type { AvailabilityPricing } from './models/AvailabilityPricing';
export type { AvailabilityResource } from './models/AvailabilityResource';
export type { AvailabilityResourceGroup } from './models/AvailabilityResourceGroup';
export type { AvailabilityResources } from './models/AvailabilityResources';
export type { AvailabilityResourcesQuery_availabilityId } from './models/AvailabilityResourcesQuery_availabilityId';
export type { AvailabilityResourcesQuery_optionId } from './models/AvailabilityResourcesQuery_optionId';
export type { AvailabilityResourcesQuery_productId } from './models/AvailabilityResourcesQuery_productId';
export type { AvailabilityResourcesQueryParams } from './models/AvailabilityResourcesQueryParams';
export type { AvailabilityResourcesRequest } from './models/AvailabilityResourcesRequest';
export { AvailabilityStatus } from './models/AvailabilityStatus';
export { AvailabilityType } from './models/AvailabilityType';
export type { AvailabilityUnit } from './models/AvailabilityUnit';
export type { AvailabilityUpdate } from './models/AvailabilityUpdate';
export type { AvailableLanguages } from './models/AvailableLanguages';
export type { AvailableLanguagesItem } from './models/AvailableLanguagesItem';
export type { Booking } from './models/Booking';
export type { BookingAdjustment } from './models/BookingAdjustment';
export type { BookingAdjustments } from './models/BookingAdjustments';
export type { BookingCancellationBody } from './models/BookingCancellationBody';
export type { BookingCancellationErrorResponse } from './models/BookingCancellationErrorResponse';
export type { BookingCancellationPathParams } from './models/BookingCancellationPathParams';
export type { BookingCardPayments } from './models/BookingCardPayments';
export type { BookingCart } from './models/BookingCart';
export type { BookingCheckin } from './models/BookingCheckin';
export type { BookingConfirmationBody } from './models/BookingConfirmationBody';
export type { BookingConfirmationErrorResponse } from './models/BookingConfirmationErrorResponse';
export type { BookingConfirmationPathParams } from './models/BookingConfirmationPathParams';
export type { BookingContact } from './models/BookingContact';
export type { BookingContent } from './models/BookingContent';
export type { BookingContentBody } from './models/BookingContentBody';
export type { BookingExtras } from './models/BookingExtras';
export type { BookingGifts } from './models/BookingGifts';
export type { BookingIdenititesBody } from './models/BookingIdenititesBody';
export type { BookingIdentities } from './models/BookingIdentities';
export type { BookingMappings } from './models/BookingMappings';
export type { BookingMemberships } from './models/BookingMemberships';
export type { BookingOffers } from './models/BookingOffers';
export type { BookingOffersBody } from './models/BookingOffersBody';
export type { BookingPackages } from './models/BookingPackages';
export type { BookingPickupBody } from './models/BookingPickupBody';
export type { BookingPickups } from './models/BookingPickups';
export type { BookingPricing } from './models/BookingPricing';
export type { BookingQuestions } from './models/BookingQuestions';
export type { BookingRejection } from './models/BookingRejection';
export type { BookingRentals } from './models/BookingRentals';
export type { BookingReservationBody } from './models/BookingReservationBody';
export type { BookingReservationErrorResponse } from './models/BookingReservationErrorResponse';
export type { BookingResources } from './models/BookingResources';
export type { BookingResourcesBody } from './models/BookingResourcesBody';
export { BookingStatus } from './models/BookingStatus';
export type { BookingUpdate } from './models/BookingUpdate';
export type { BookingUpdateBody } from './models/BookingUpdateBody';
export type { BookingUpdatePathParams } from './models/BookingUpdatePathParams';
export type { Brand } from './models/Brand';
export type { BrandContact } from './models/BrandContact';
export type { BrandVentrataCheckoutContent } from './models/BrandVentrataCheckoutContent';
export type { BridgepayGateway } from './models/BridgepayGateway';
export type { CancelGiftBody } from './models/CancelGiftBody';
export type { CancelGiftPathParams } from './models/CancelGiftPathParams';
export type { Cancellation } from './models/Cancellation';
export type { CancelOrderBody } from './models/CancelOrderBody';
export type { Capability } from './models/Capability';
export { CapabilityId } from './models/CapabilityId';
export type { Card } from './models/Card';
export type { CardPayment } from './models/CardPayment';
export type { CardPaymentGateway } from './models/CardPaymentGateway';
export type { Category } from './models/Category';
export type { CategoryVentrataCheckoutContent } from './models/CategoryVentrataCheckoutContent';
export type { CheckinLookup } from './models/CheckinLookup';
export type { CheckinLookupBody } from './models/CheckinLookupBody';
export type { Checkout } from './models/Checkout';
export type { CheckoutConfig } from './models/CheckoutConfig';
export type { CheckoutConfigContent } from './models/CheckoutConfigContent';
export { CheckoutConfigPricingDisplay } from './models/CheckoutConfigPricingDisplay';
export type { CheckoutDomain } from './models/CheckoutDomain';
export type { CheckoutSitemapEntry } from './models/CheckoutSitemapEntry';
export { CheckoutSitemapEntryRel } from './models/CheckoutSitemapEntryRel';
export type { Claim } from './models/Claim';
export type { ConfirmOrderBody } from './models/ConfirmOrderBody';
export type { ConfirmOrderPricingBody } from './models/ConfirmOrderPricingBody';
export type { Connection } from './models/Connection';
export { ContactField } from './models/ContactField';
export type { CreateGiftBody } from './models/CreateGiftBody';
export type { CreateIdentityBody } from './models/CreateIdentityBody';
export type { CreateOrderBody } from './models/CreateOrderBody';
export type { CreateOrderCardPaymentsBody } from './models/CreateOrderCardPaymentsBody';
export type { CreateOrderGiftsBody } from './models/CreateOrderGiftsBody';
export type { CreateOrderIdentitiesBody } from './models/CreateOrderIdentitiesBody';
export type { CreateOrderPricingBody } from './models/CreateOrderPricingBody';
export type { CreateWaitlistRequest } from './models/CreateWaitlistRequest';
export type { CreateWebhookBody } from './models/CreateWebhookBody';
export type { CreateWebhookRequestHeaders_octoCapabilities } from './models/CreateWebhookRequestHeaders_octoCapabilities';
export type { CustomerContact } from './models/CustomerContact';
export type { CustomRetailOption } from './models/CustomRetailOption';
export type { DefaultableID } from './models/DefaultableID';
export type { DeleteIdentityPathParams } from './models/DeleteIdentityPathParams';
export type { DeleteIdentityRequest_id } from './models/DeleteIdentityRequest_id';
export type { DeleteWebhookPathParams } from './models/DeleteWebhookPathParams';
export type { DeleteWebhookRequest_id } from './models/DeleteWebhookRequest_id';
export type { DeleteWebhookRequestHeaders_octoCapabilities } from './models/DeleteWebhookRequestHeaders_octoCapabilities';
export { DeliveryFormat } from './models/DeliveryFormat';
export { DeliveryMethod } from './models/DeliveryMethod';
export type { DeliveryOption } from './models/DeliveryOption';
export type { DependentAnswer } from './models/DependentAnswer';
export type { Destination } from './models/Destination';
export type { DestinationContact } from './models/DestinationContact';
export type { DestinationPricing } from './models/DestinationPricing';
export type { DestinationVentrataCheckoutContent } from './models/DestinationVentrataCheckoutContent';
export type { Diff } from './models/Diff';
export type { DiscountTax } from './models/DiscountTax';
export type { DropoffPoint } from './models/DropoffPoint';
export { DurationUnit } from './models/DurationUnit';
export { Env } from './models/Env';
export type { ExtendOrderBody } from './models/ExtendOrderBody';
export type { ExtendReservationBody } from './models/ExtendReservationBody';
export type { ExtendReservationErrorResponse } from './models/ExtendReservationErrorResponse';
export type { ExtendReservationPathParams } from './models/ExtendReservationPathParams';
export type { ExternalGateway } from './models/ExternalGateway';
export type { ExternalGatewayRequest } from './models/ExternalGatewayRequest';
export type { Extra } from './models/Extra';
export type { ExtraContent } from './models/ExtraContent';
export type { ExtraItem } from './models/ExtraItem';
export type { ExtraPricing } from './models/ExtraPricing';
export type { ExtraRestrictions } from './models/ExtraRestrictions';
export type { FAQ } from './models/FAQ';
export type { Fare } from './models/Fare';
export type { FareGroup } from './models/FareGroup';
export type { Font } from './models/Font';
export type { GetBookingRequest } from './models/GetBookingRequest';
export type { GetBookingsQuery_localDate } from './models/GetBookingsQuery_localDate';
export type { GetBookingsQuery_localDateEnd } from './models/GetBookingsQuery_localDateEnd';
export type { GetBookingsQuery_localDateStart } from './models/GetBookingsQuery_localDateStart';
export type { GetBookingsQuery_optionId } from './models/GetBookingsQuery_optionId';
export type { GetBookingsQuery_productId } from './models/GetBookingsQuery_productId';
export type { GetBookingsQuery_resellerReference } from './models/GetBookingsQuery_resellerReference';
export type { GetBookingsQuery_supplierReference } from './models/GetBookingsQuery_supplierReference';
export type { GetBookingsQueryParams } from './models/GetBookingsQueryParams';
export type { GetBookingsRequest } from './models/GetBookingsRequest';
export type { GetMappingsQuery_optionId } from './models/GetMappingsQuery_optionId';
export type { GetMappingsQuery_productId } from './models/GetMappingsQuery_productId';
export type { GetMappingsQuery_resellerReference } from './models/GetMappingsQuery_resellerReference';
export type { GetMappingsQuery_resellerStatus } from './models/GetMappingsQuery_resellerStatus';
export type { GetMappingsQueryParams } from './models/GetMappingsQueryParams';
export type { GetMappingsRequest } from './models/GetMappingsRequest';
export type { GetOrderRequest_id } from './models/GetOrderRequest_id';
export type { GetProductRequest } from './models/GetProductRequest';
export type { GetProductsQuery_categoryId } from './models/GetProductsQuery_categoryId';
export type { GetProductsQuery_destinationId } from './models/GetProductsQuery_destinationId';
export type { GetProductsQuery_featured } from './models/GetProductsQuery_featured';
export type { GetProductsQuery_productIds } from './models/GetProductsQuery_productIds';
export type { GetProductsRequest } from './models/GetProductsRequest';
export type { GetSupplierRequest } from './models/GetSupplierRequest';
export type { GetYourGuideActivateBody } from './models/GetYourGuideActivateBody';
export type { GetYourGuideActivateRequestHeaders_octoCapabilities } from './models/GetYourGuideActivateRequestHeaders_octoCapabilities';
export type { GetYourGuideConnection } from './models/GetYourGuideConnection';
export type { Gift } from './models/Gift';
export type { GiftCardPayments } from './models/GiftCardPayments';
export type { GiftCart } from './models/GiftCart';
export { GiftExpiryUnit } from './models/GiftExpiryUnit';
export type { GiftIdentities } from './models/GiftIdentities';
export type { GiftOffers } from './models/GiftOffers';
export type { GiftPayment } from './models/GiftPayment';
export type { GiftsRestrictionItem } from './models/GiftsRestrictionItem';
export type { GiftsRestrictions } from './models/GiftsRestrictions';
export type { GiftVoucher } from './models/GiftVoucher';
export type { GoogleLocalizedName } from './models/GoogleLocalizedName';
export type { GoogleLocalizedText } from './models/GoogleLocalizedText';
export type { GoogleLocation } from './models/GoogleLocation';
export type { GoogleNullableLocalizedName } from './models/GoogleNullableLocalizedName';
export type { GoogleNullableLocalizedText } from './models/GoogleNullableLocalizedText';
export type { GoogleOperator } from './models/GoogleOperator';
export type { GoogleOptionCategory } from './models/GoogleOptionCategory';
export type { GoogleOptions } from './models/GoogleOptions';
export type { GoogleRating } from './models/GoogleRating';
export type { GoogleRelatedLocation } from './models/GoogleRelatedLocation';
export type { GoogleUrl } from './models/GoogleUrl';
export type { Identity } from './models/Identity';
export type { Image } from './models/Image';
export type { Include } from './models/Include';
export type { ItineraryItem } from './models/ItineraryItem';
export { ItineraryItemType } from './models/ItineraryItemType';
export type { Label } from './models/Label';
export type { Link } from './models/Link';
export type { ListCapabilitiesRequest } from './models/ListCapabilitiesRequest';
export type { ListCapabilitiesRequestHeaders } from './models/ListCapabilitiesRequestHeaders';
export type { ListGiftsQueryParams } from './models/ListGiftsQueryParams';
export type { ListOrdersQueryParams } from './models/ListOrdersQueryParams';
export type { ListWebhooksRequest } from './models/ListWebhooksRequest';
export type { ListWebhooksRequestHeaders_octoCapabilities } from './models/ListWebhooksRequestHeaders_octoCapabilities';
export type { Mapping } from './models/Mapping';
export type { MappingToUpdate } from './models/MappingToUpdate';
export type { Membership } from './models/Membership';
export type { MembershipBenefit } from './models/MembershipBenefit';
export type { MembershipLookup } from './models/MembershipLookup';
export type { MembershipLookupBody } from './models/MembershipLookupBody';
export type { Nav } from './models/Nav';
export { NetDiscount } from './models/NetDiscount';
export type { Notice } from './models/Notice';
export type { Octo_AvailabilityCalendarErrorResponse } from './models/Octo_AvailabilityCalendarErrorResponse';
export type { Octo_AvailabilityCheckErrorResponse } from './models/Octo_AvailabilityCheckErrorResponse';
export type { Octo_BaseError } from './models/Octo_BaseError';
export type { Octo_BookingCancellationErrorResponse } from './models/Octo_BookingCancellationErrorResponse';
export type { Octo_BookingConfirmationErrorResponse } from './models/Octo_BookingConfirmationErrorResponse';
export type { Octo_BookingReservationErrorResponse } from './models/Octo_BookingReservationErrorResponse';
export { Octo_CapabilityId } from './models/Octo_CapabilityId';
export type { Octo_ErrorBadRequest } from './models/Octo_ErrorBadRequest';
export type { Octo_ErrorForbidden } from './models/Octo_ErrorForbidden';
export type { Octo_ErrorInternalServerError } from './models/Octo_ErrorInternalServerError';
export type { Octo_ErrorInvalidAvailabilityID } from './models/Octo_ErrorInvalidAvailabilityID';
export type { Octo_ErrorInvalidBookingUUID } from './models/Octo_ErrorInvalidBookingUUID';
export type { Octo_ErrorInvalidOptionID } from './models/Octo_ErrorInvalidOptionID';
export type { Octo_ErrorInvalidProductID } from './models/Octo_ErrorInvalidProductID';
export type { Octo_ErrorInvalidUnitID } from './models/Octo_ErrorInvalidUnitID';
export type { Octo_ErrorUnauthorized } from './models/Octo_ErrorUnauthorized';
export type { Octo_ErrorUnprocessableEntity } from './models/Octo_ErrorUnprocessableEntity';
export type { Octo_ExtendReservationBody } from './models/Octo_ExtendReservationBody';
export type { Octo_ExtendReservationErrorResponse } from './models/Octo_ExtendReservationErrorResponse';
export type { Octo_GetBookingRequest } from './models/Octo_GetBookingRequest';
export type { Octo_GetBookingRequest_uuid } from './models/Octo_GetBookingRequest_uuid';
export type { Octo_GetProductRequest } from './models/Octo_GetProductRequest';
export type { Octo_GetProductRequest_id } from './models/Octo_GetProductRequest_id';
export type { Octo_GetProductsRequest } from './models/Octo_GetProductsRequest';
export type { Octo_GetSupplierRequest } from './models/Octo_GetSupplierRequest';
export type { Octo_RequestHeaders } from './models/Octo_RequestHeaders';
export type { Octo_RequestHeaders_octoCapabilities } from './models/Octo_RequestHeaders_octoCapabilities';
export type { Octo_RequestHeadersContent } from './models/Octo_RequestHeadersContent';
export type { Octo_ResponseHeaders } from './models/Octo_ResponseHeaders';
export type { Offer } from './models/Offer';
export type { OfferCombination } from './models/OfferCombination';
export type { OfferComparison } from './models/OfferComparison';
export type { OfferDiscount } from './models/OfferDiscount';
export type { OfferMemberships } from './models/OfferMemberships';
export type { OfferRestrictions } from './models/OfferRestrictions';
export type { OpeningHours } from './models/OpeningHours';
export type { OpeningHoursContent } from './models/OpeningHoursContent';
export type { Operator } from './models/Operator';
export type { Option } from './models/Option';
export type { OptionContent } from './models/OptionContent';
export type { OptionExtras } from './models/OptionExtras';
export type { OptionPackages } from './models/OptionPackages';
export type { OptionPickups } from './models/OptionPickups';
export type { OptionPricing } from './models/OptionPricing';
export type { OptionQuestions } from './models/OptionQuestions';
export type { OptionRentals } from './models/OptionRentals';
export type { OptionRestrictions } from './models/OptionRestrictions';
export type { Order } from './models/Order';
export type { OrderCardPayments } from './models/OrderCardPayments';
export type { OrderCheckin } from './models/OrderCheckin';
export type { OrderContent } from './models/OrderContent';
export type { OrderGifts } from './models/OrderGifts';
export type { OrderIdentities } from './models/OrderIdentities';
export type { OrderMemberships } from './models/OrderMemberships';
export type { OrderOffers } from './models/OrderOffers';
export type { OrderPathParams } from './models/OrderPathParams';
export type { OrderPricing } from './models/OrderPricing';
export type { OrderQuestions } from './models/OrderQuestions';
export type { OrderVentrataCheckout } from './models/OrderVentrataCheckout';
export type { PackageAvailability } from './models/PackageAvailability';
export type { PackageInclude } from './models/PackageInclude';
export type { Page } from './models/Page';
export type { Partner } from './models/Partner';
export { PartnerEnum } from './models/PartnerEnum';
export type { PartnersConnection } from './models/PartnersConnection';
export type { PartnersListConnection } from './models/PartnersListConnection';
export type { PartnersListConnectionsRequest } from './models/PartnersListConnectionsRequest';
export type { PartnersListConnectionsRequestHeaders } from './models/PartnersListConnectionsRequestHeaders';
export type { PartnersListConnectionsRequestHeaders_octoCapabilities } from './models/PartnersListConnectionsRequestHeaders_octoCapabilities';
export type { PartnersListConnectionsRequestHeaders_ventrataPartnerKey } from './models/PartnersListConnectionsRequestHeaders_ventrataPartnerKey';
export type { PaypalGateway } from './models/PaypalGateway';
export type { PaypalGatewayRequest } from './models/PaypalGatewayRequest';
export type { PaytrGateway } from './models/PaytrGateway';
export type { PeachGateway } from './models/PeachGateway';
export type { PickupPoint } from './models/PickupPoint';
export type { Point } from './models/Point';
export type { PointGroup } from './models/PointGroup';
export type { Pricing } from './models/Pricing';
export type { PricingExtras } from './models/PricingExtras';
export type { PricingOffers } from './models/PricingOffers';
export { PricingPer } from './models/PricingPer';
export type { PricingUnit } from './models/PricingUnit';
export type { PricingUnitExtras } from './models/PricingUnitExtras';
export type { Product } from './models/Product';
export type { ProductContent } from './models/ProductContent';
export type { ProductGoogle } from './models/ProductGoogle';
export type { ProductMemberships } from './models/ProductMemberships';
export type { ProductPackages } from './models/ProductPackages';
export type { ProductPricing } from './models/ProductPricing';
export type { ProductRentals } from './models/ProductRentals';
export type { ProductVentrataCheckout } from './models/ProductVentrataCheckout';
export type { ProductVentrataCheckoutContent } from './models/ProductVentrataCheckoutContent';
export type { Question } from './models/Question';
export type { QuestionAnswer } from './models/QuestionAnswer';
export { QuestionInputType } from './models/QuestionInputType';
export type { RealaxGateway } from './models/RealaxGateway';
export type { RedemptionLookup } from './models/RedemptionLookup';
export type { RedemptionLookupQuery } from './models/RedemptionLookupQuery';
export type { RedemptionLookupQueryParams } from './models/RedemptionLookupQueryParams';
export type { RedemptionLookupRequest } from './models/RedemptionLookupRequest';
export { RedemptionMethod } from './models/RedemptionMethod';
export { Refund } from './models/Refund';
export type { RentalDuration } from './models/RentalDuration';
export type { RequestHeaders } from './models/RequestHeaders';
export type { Reseller } from './models/Reseller';
export { ResellerStatus } from './models/ResellerStatus';
export type { Resource } from './models/Resource';
export type { ResourceAllocation } from './models/ResourceAllocation';
export type { ResourceAllocationRequest } from './models/ResourceAllocationRequest';
export type { ResourceGroup } from './models/ResourceGroup';
export type { ResponseHeaders } from './models/ResponseHeaders';
export type { Scan } from './models/Scan';
export type { Seat } from './models/Seat';
export type { SelectOption } from './models/SelectOption';
export type { Seller } from './models/Seller';
export { SettlementMethod } from './models/SettlementMethod';
export type { SpreedlyGateway } from './models/SpreedlyGateway';
export type { StripeGateway } from './models/StripeGateway';
export type { Supplier } from './models/Supplier';
export type { SupplierContact } from './models/SupplierContact';
export type { SupplierContent } from './models/SupplierContent';
export type { Tax } from './models/Tax';
export type { Terminal } from './models/Terminal';
export type { Ticket } from './models/Ticket';
export type { TourGroup } from './models/TourGroup';
export type { Unit } from './models/Unit';
export type { UnitContent } from './models/UnitContent';
export type { UnitExtras } from './models/UnitExtras';
export type { UnitItem } from './models/UnitItem';
export type { UnitItemExtras } from './models/UnitItemExtras';
export type { UnitItemIdentifier } from './models/UnitItemIdentifier';
export type { UnitItemPricing } from './models/UnitItemPricing';
export type { UnitItemQuestions } from './models/UnitItemQuestions';
export type { UnitItemRedemption } from './models/UnitItemRedemption';
export type { UnitMemberships } from './models/UnitMemberships';
export type { UnitPricing } from './models/UnitPricing';
export type { UnitQuestions } from './models/UnitQuestions';
export type { UnitRedemption } from './models/UnitRedemption';
export type { UnitRestrictions } from './models/UnitRestrictions';
export { UnitType } from './models/UnitType';
export type { UpdateGiftBody } from './models/UpdateGiftBody';
export type { UpdateGiftPathParams } from './models/UpdateGiftPathParams';
export type { UpdateIdentityBody } from './models/UpdateIdentityBody';
export type { UpdateIdentityPathParams } from './models/UpdateIdentityPathParams';
export type { UpdateOrderBody } from './models/UpdateOrderBody';
export type { UpdateOrderPricingBody } from './models/UpdateOrderPricingBody';
export type { User } from './models/User';
export type { UUID, uuid } from './models/UUID';
export type { VivawalletGateway } from './models/VivawalletGateway';
export type { Waitlist } from './models/Waitlist';
export type { WaitlistUnitIdentifier } from './models/WaitlistUnitIdentifier';
export type { WaitlistUnitItemIdentifier } from './models/WaitlistUnitItemIdentifier';
export type { Webhook } from './models/Webhook';
export { WebhookEvent } from './models/WebhookEvent';
export type { WhoAmI } from './models/WhoAmI';
export type { WhoAmIRequest } from './models/WhoAmIRequest';

// Zod Schemas
export { adjustmentDiscountSchema } from './schemas/AdjustmentDiscount';
export { adjustmentPerSchema } from './schemas/AdjustmentPer';
export { adyenGatewaySchema } from './schemas/AdyenGateway';
export { adyenGatewaySessionSchema } from './schemas/AdyenGatewaySession';
export { adyenPaymentMethodsConfigurationSchema } from './schemas/AdyenPaymentMethodsConfiguration';
export { adyenPaymentMethodsConfigurationApplePaySchema } from './schemas/AdyenPaymentMethodsConfigurationApplePay';
export { adyenPaymentMethodsConfigurationCardSchema } from './schemas/AdyenPaymentMethodsConfigurationCard';
export { adyenPaymentMethodsConfigurationCardBillingAddressModeSchema } from './schemas/AdyenPaymentMethodsConfigurationCardBillingAddressMode';
export { adyenPaymentMethodsConfigurationGooglePaySchema } from './schemas/AdyenPaymentMethodsConfigurationGooglePay';
export { adyenPaymentMethodsConfigurationGooglePayBillingAddressParametersSchema } from './schemas/AdyenPaymentMethodsConfigurationGooglePayBillingAddressParameters';
export { adyenPaymentMethodsConfigurationPayPaySchema } from './schemas/AdyenPaymentMethodsConfigurationPayPay';
export { agentSchema } from './schemas/Agent';
export { articleSchema } from './schemas/Article';
export { availabilitySchema } from './schemas/Availability';
export { availabilityCalendarSchema } from './schemas/AvailabilityCalendar';
export { availabilityCalendarBatchBodySchema } from './schemas/AvailabilityCalendarBatchBody';
export { availabilityCalendarBatchErrorResponseSchema } from './schemas/AvailabilityCalendarBatchErrorResponse';
export { availabilityCalendarBodySchema } from './schemas/AvailabilityCalendarBody';
export { availabilityCalendarErrorResponseSchema } from './schemas/AvailabilityCalendarErrorResponse';
export { availabilityCalendarExtrasSchema } from './schemas/AvailabilityCalendarExtras';
export { availabilityCalendarOffersSchema } from './schemas/AvailabilityCalendarOffers';
export { availabilityCalendarPricingSchema } from './schemas/AvailabilityCalendarPricing';
export { availabilityCheckBodySchema } from './schemas/AvailabilityCheckBody';
export { availabilityCheckErrorResponseSchema } from './schemas/AvailabilityCheckErrorResponse';
export { availabilityCheckQueryParamsSchema } from './schemas/AvailabilityCheckQueryParams';
export { availabilityContentSchema } from './schemas/AvailabilityContent';
export { availabilityExtrasSchema } from './schemas/AvailabilityExtras';
export { availabilityMappingsSchema } from './schemas/AvailabilityMappings';
export { availabilityOffersSchema } from './schemas/AvailabilityOffers';
export { availabilityPackagesSchema } from './schemas/AvailabilityPackages';
export { availabilityPickupsSchema } from './schemas/AvailabilityPickups';
export { availabilityPricingSchema } from './schemas/AvailabilityPricing';
export { availabilityResourceSchema } from './schemas/AvailabilityResource';
export { availabilityResourceGroupSchema } from './schemas/AvailabilityResourceGroup';
export { availabilityResourcesSchema } from './schemas/AvailabilityResources';
export { availabilityResourcesQueryParamsSchema } from './schemas/AvailabilityResourcesQueryParams';
export { availabilityResourcesQuery_availabilityIdSchema } from './schemas/AvailabilityResourcesQuery_availabilityId';
export { availabilityResourcesQuery_optionIdSchema } from './schemas/AvailabilityResourcesQuery_optionId';
export { availabilityResourcesQuery_productIdSchema } from './schemas/AvailabilityResourcesQuery_productId';
export { availabilityResourcesRequestSchema } from './schemas/AvailabilityResourcesRequest';
export { availabilityStatusSchema } from './schemas/AvailabilityStatus';
export { availabilityTypeSchema } from './schemas/AvailabilityType';
export { availabilityUnitSchema } from './schemas/AvailabilityUnit';
export { availabilityUpdateSchema } from './schemas/AvailabilityUpdate';
export { availableLanguagesSchema } from './schemas/AvailableLanguages';
export { availableLanguagesItemSchema } from './schemas/AvailableLanguagesItem';
export { bookingSchema } from './schemas/Booking';
export { bookingAdjustmentSchema } from './schemas/BookingAdjustment';
export { bookingAdjustmentsSchema } from './schemas/BookingAdjustments';
export { bookingCancellationBodySchema } from './schemas/BookingCancellationBody';
export { bookingCancellationErrorResponseSchema } from './schemas/BookingCancellationErrorResponse';
export { bookingCancellationPathParamsSchema } from './schemas/BookingCancellationPathParams';
export { bookingCardPaymentsSchema } from './schemas/BookingCardPayments';
export { bookingCartSchema } from './schemas/BookingCart';
export { bookingCheckinSchema } from './schemas/BookingCheckin';
export { bookingConfirmationBodySchema } from './schemas/BookingConfirmationBody';
export { bookingConfirmationErrorResponseSchema } from './schemas/BookingConfirmationErrorResponse';
export { bookingConfirmationPathParamsSchema } from './schemas/BookingConfirmationPathParams';
export { bookingContactSchema } from './schemas/BookingContact';
export { bookingContentSchema } from './schemas/BookingContent';
export { bookingContentBodySchema } from './schemas/BookingContentBody';
export { bookingExtrasSchema } from './schemas/BookingExtras';
export { bookingGiftsSchema } from './schemas/BookingGifts';
export { bookingIdenititesBodySchema } from './schemas/BookingIdenititesBody';
export { bookingIdentitiesSchema } from './schemas/BookingIdentities';
export { bookingMappingsSchema } from './schemas/BookingMappings';
export { bookingMembershipsSchema } from './schemas/BookingMemberships';
export { bookingOffersSchema } from './schemas/BookingOffers';
export { bookingOffersBodySchema } from './schemas/BookingOffersBody';
export { bookingPackagesSchema } from './schemas/BookingPackages';
export { bookingPickupBodySchema } from './schemas/BookingPickupBody';
export { bookingPickupsSchema } from './schemas/BookingPickups';
export { bookingPricingSchema } from './schemas/BookingPricing';
export { bookingQuestionsSchema } from './schemas/BookingQuestions';
export { bookingRejectionSchema } from './schemas/BookingRejection';
export { bookingRentalsSchema } from './schemas/BookingRentals';
export { bookingReservationBodySchema } from './schemas/BookingReservationBody';
export { bookingReservationErrorResponseSchema } from './schemas/BookingReservationErrorResponse';
export { bookingResourcesSchema } from './schemas/BookingResources';
export { bookingResourcesBodySchema } from './schemas/BookingResourcesBody';
export { bookingStatusSchema } from './schemas/BookingStatus';
export { bookingUpdateSchema } from './schemas/BookingUpdate';
export { bookingUpdateBodySchema } from './schemas/BookingUpdateBody';
export { bookingUpdatePathParamsSchema } from './schemas/BookingUpdatePathParams';
export { brandSchema } from './schemas/Brand';
export { brandContactSchema } from './schemas/BrandContact';
export { brandVentrataCheckoutContentSchema } from './schemas/BrandVentrataCheckoutContent';
export { bridgepayGatewaySchema } from './schemas/BridgepayGateway';
export { cancelGiftBodySchema } from './schemas/CancelGiftBody';
export { cancelGiftPathParamsSchema } from './schemas/CancelGiftPathParams';
export { cancelOrderBodySchema } from './schemas/CancelOrderBody';
export { cancellationSchema } from './schemas/Cancellation';
export { capabilitySchema } from './schemas/Capability';
export { capabilityIdSchema } from './schemas/CapabilityId';
export { cardSchema } from './schemas/Card';
export { cardPaymentSchema } from './schemas/CardPayment';
export { cardPaymentGatewaySchema } from './schemas/CardPaymentGateway';
export { categorySchema } from './schemas/Category';
export { categoryVentrataCheckoutContentSchema } from './schemas/CategoryVentrataCheckoutContent';
export { checkinLookupSchema } from './schemas/CheckinLookup';
export { checkinLookupBodySchema } from './schemas/CheckinLookupBody';
export { checkoutSchema } from './schemas/Checkout';
export { checkoutConfigSchema } from './schemas/CheckoutConfig';
export { checkoutConfigContentSchema } from './schemas/CheckoutConfigContent';
export { checkoutConfigPricingDisplaySchema } from './schemas/CheckoutConfigPricingDisplay';
export { checkoutDomainSchema } from './schemas/CheckoutDomain';
export { checkoutSitemapEntrySchema } from './schemas/CheckoutSitemapEntry';
export { checkoutSitemapEntryRelSchema } from './schemas/CheckoutSitemapEntryRel';
export { claimSchema } from './schemas/Claim';
export { confirmOrderBodySchema } from './schemas/ConfirmOrderBody';
export { confirmOrderPricingBodySchema } from './schemas/ConfirmOrderPricingBody';
export { connectionSchema } from './schemas/Connection';
export { contactFieldSchema } from './schemas/ContactField';
export { createGiftBodySchema } from './schemas/CreateGiftBody';
export { createIdentityBodySchema } from './schemas/CreateIdentityBody';
export { createOrderBodySchema } from './schemas/CreateOrderBody';
export { createOrderCardPaymentsBodySchema } from './schemas/CreateOrderCardPaymentsBody';
export { createOrderGiftsBodySchema } from './schemas/CreateOrderGiftsBody';
export { createOrderIdentitiesBodySchema } from './schemas/CreateOrderIdentitiesBody';
export { createOrderPricingBodySchema } from './schemas/CreateOrderPricingBody';
export { createWaitlistRequestSchema } from './schemas/CreateWaitlistRequest';
export { createWebhookBodySchema } from './schemas/CreateWebhookBody';
export { createWebhookRequestHeaders_octoCapabilitiesSchema } from './schemas/CreateWebhookRequestHeaders_octoCapabilities';
export { customRetailOptionSchema } from './schemas/CustomRetailOption';
export { customerContactSchema } from './schemas/CustomerContact';
export { defaultableIDSchema } from './schemas/DefaultableID';
export { deleteIdentityPathParamsSchema } from './schemas/DeleteIdentityPathParams';
export { deleteIdentityRequest_idSchema } from './schemas/DeleteIdentityRequest_id';
export { deleteWebhookPathParamsSchema } from './schemas/DeleteWebhookPathParams';
export { deleteWebhookRequestHeaders_octoCapabilitiesSchema } from './schemas/DeleteWebhookRequestHeaders_octoCapabilities';
export { deleteWebhookRequest_idSchema } from './schemas/DeleteWebhookRequest_id';
export { deliveryFormatSchema } from './schemas/DeliveryFormat';
export { deliveryMethodSchema } from './schemas/DeliveryMethod';
export { deliveryOptionSchema } from './schemas/DeliveryOption';
export { dependentAnswerSchema } from './schemas/DependentAnswer';
export { destinationSchema } from './schemas/Destination';
export { destinationContactSchema } from './schemas/DestinationContact';
export { destinationPricingSchema } from './schemas/DestinationPricing';
export { destinationVentrataCheckoutContentSchema } from './schemas/DestinationVentrataCheckoutContent';
export { diffSchema } from './schemas/Diff';
export { discountTaxSchema } from './schemas/DiscountTax';
export { dropoffPointSchema } from './schemas/DropoffPoint';
export { durationUnitSchema } from './schemas/DurationUnit';
export { envSchema } from './schemas/Env';
export { extendOrderBodySchema } from './schemas/ExtendOrderBody';
export { extendReservationBodySchema } from './schemas/ExtendReservationBody';
export { extendReservationErrorResponseSchema } from './schemas/ExtendReservationErrorResponse';
export { extendReservationPathParamsSchema } from './schemas/ExtendReservationPathParams';
export { externalGatewaySchema } from './schemas/ExternalGateway';
export { externalGatewayRequestSchema } from './schemas/ExternalGatewayRequest';
export { extraSchema } from './schemas/Extra';
export { extraContentSchema } from './schemas/ExtraContent';
export { extraItemSchema } from './schemas/ExtraItem';
export { extraPricingSchema } from './schemas/ExtraPricing';
export { extraRestrictionsSchema } from './schemas/ExtraRestrictions';
export { fAQSchema } from './schemas/FAQ';
export { fareSchema } from './schemas/Fare';
export { fareGroupSchema } from './schemas/FareGroup';
export { fontSchema } from './schemas/Font';
export { getBookingRequestSchema } from './schemas/GetBookingRequest';
export { getBookingsQueryParamsSchema } from './schemas/GetBookingsQueryParams';
export { getBookingsQuery_localDateSchema } from './schemas/GetBookingsQuery_localDate';
export { getBookingsQuery_localDateEndSchema } from './schemas/GetBookingsQuery_localDateEnd';
export { getBookingsQuery_localDateStartSchema } from './schemas/GetBookingsQuery_localDateStart';
export { getBookingsQuery_optionIdSchema } from './schemas/GetBookingsQuery_optionId';
export { getBookingsQuery_productIdSchema } from './schemas/GetBookingsQuery_productId';
export { getBookingsQuery_resellerReferenceSchema } from './schemas/GetBookingsQuery_resellerReference';
export { getBookingsQuery_supplierReferenceSchema } from './schemas/GetBookingsQuery_supplierReference';
export { getBookingsRequestSchema } from './schemas/GetBookingsRequest';
export { getMappingsQueryParamsSchema } from './schemas/GetMappingsQueryParams';
export { getMappingsQuery_optionIdSchema } from './schemas/GetMappingsQuery_optionId';
export { getMappingsQuery_productIdSchema } from './schemas/GetMappingsQuery_productId';
export { getMappingsQuery_resellerReferenceSchema } from './schemas/GetMappingsQuery_resellerReference';
export { getMappingsQuery_resellerStatusSchema } from './schemas/GetMappingsQuery_resellerStatus';
export { getMappingsRequestSchema } from './schemas/GetMappingsRequest';
export { getOrderRequest_idSchema } from './schemas/GetOrderRequest_id';
export { getProductRequestSchema } from './schemas/GetProductRequest';
export { getProductsQuery_categoryIdSchema } from './schemas/GetProductsQuery_categoryId';
export { getProductsQuery_destinationIdSchema } from './schemas/GetProductsQuery_destinationId';
export { getProductsQuery_featuredSchema } from './schemas/GetProductsQuery_featured';
export { getProductsQuery_productIdsSchema } from './schemas/GetProductsQuery_productIds';
export { getProductsRequestSchema } from './schemas/GetProductsRequest';
export { getSupplierRequestSchema } from './schemas/GetSupplierRequest';
export { getYourGuideActivateBodySchema } from './schemas/GetYourGuideActivateBody';
export { getYourGuideActivateRequestHeaders_octoCapabilitiesSchema } from './schemas/GetYourGuideActivateRequestHeaders_octoCapabilities';
export { getYourGuideConnectionSchema } from './schemas/GetYourGuideConnection';
export { giftSchema } from './schemas/Gift';
export { giftCardPaymentsSchema } from './schemas/GiftCardPayments';
export { giftCartSchema } from './schemas/GiftCart';
export { giftExpiryUnitSchema } from './schemas/GiftExpiryUnit';
export { giftIdentitiesSchema } from './schemas/GiftIdentities';
export { giftOffersSchema } from './schemas/GiftOffers';
export { giftPaymentSchema } from './schemas/GiftPayment';
export { giftVoucherSchema } from './schemas/GiftVoucher';
export { giftsRestrictionItemSchema } from './schemas/GiftsRestrictionItem';
export { giftsRestrictionsSchema } from './schemas/GiftsRestrictions';
export { googleLocalizedNameSchema } from './schemas/GoogleLocalizedName';
export { googleLocalizedTextSchema } from './schemas/GoogleLocalizedText';
export { googleLocationSchema } from './schemas/GoogleLocation';
export { googleNullableLocalizedNameSchema } from './schemas/GoogleNullableLocalizedName';
export { googleNullableLocalizedTextSchema } from './schemas/GoogleNullableLocalizedText';
export { googleOperatorSchema } from './schemas/GoogleOperator';
export { googleOptionCategorySchema } from './schemas/GoogleOptionCategory';
export { googleOptionsSchema } from './schemas/GoogleOptions';
export { googleRatingSchema } from './schemas/GoogleRating';
export { googleRelatedLocationSchema } from './schemas/GoogleRelatedLocation';
export { googleUrlSchema } from './schemas/GoogleUrl';
export { identitySchema } from './schemas/Identity';
export { imageSchema } from './schemas/Image';
export { includeSchema } from './schemas/Include';
export { itineraryItemSchema } from './schemas/ItineraryItem';
export { itineraryItemTypeSchema } from './schemas/ItineraryItemType';
export { labelSchema } from './schemas/Label';
export { linkSchema } from './schemas/Link';
export { listCapabilitiesRequestSchema } from './schemas/ListCapabilitiesRequest';
export { listCapabilitiesRequestHeadersSchema } from './schemas/ListCapabilitiesRequestHeaders';
export { listGiftsQueryParamsSchema } from './schemas/ListGiftsQueryParams';
export { listOrdersQueryParamsSchema } from './schemas/ListOrdersQueryParams';
export { listWebhooksRequestSchema } from './schemas/ListWebhooksRequest';
export { listWebhooksRequestHeaders_octoCapabilitiesSchema } from './schemas/ListWebhooksRequestHeaders_octoCapabilities';
export { mappingSchema } from './schemas/Mapping';
export { mappingToUpdateSchema } from './schemas/MappingToUpdate';
export { membershipSchema } from './schemas/Membership';
export { membershipBenefitSchema } from './schemas/MembershipBenefit';
export { membershipLookupSchema } from './schemas/MembershipLookup';
export { membershipLookupBodySchema } from './schemas/MembershipLookupBody';
export { navSchema } from './schemas/Nav';
export { netDiscountSchema } from './schemas/NetDiscount';
export { noticeSchema } from './schemas/Notice';
export { octo_AvailabilityCalendarErrorResponseSchema } from './schemas/Octo_AvailabilityCalendarErrorResponse';
export { octo_AvailabilityCheckErrorResponseSchema } from './schemas/Octo_AvailabilityCheckErrorResponse';
export { octo_BaseErrorSchema } from './schemas/Octo_BaseError';
export { octo_BookingCancellationErrorResponseSchema } from './schemas/Octo_BookingCancellationErrorResponse';
export { octo_BookingConfirmationErrorResponseSchema } from './schemas/Octo_BookingConfirmationErrorResponse';
export { octo_BookingReservationErrorResponseSchema } from './schemas/Octo_BookingReservationErrorResponse';
export { octo_CapabilityIdSchema } from './schemas/Octo_CapabilityId';
export { octo_ErrorBadRequestSchema } from './schemas/Octo_ErrorBadRequest';
export { octo_ErrorForbiddenSchema } from './schemas/Octo_ErrorForbidden';
export { octo_ErrorInternalServerErrorSchema } from './schemas/Octo_ErrorInternalServerError';
export { octo_ErrorInvalidAvailabilityIDSchema } from './schemas/Octo_ErrorInvalidAvailabilityID';
export { octo_ErrorInvalidBookingUUIDSchema } from './schemas/Octo_ErrorInvalidBookingUUID';
export { octo_ErrorInvalidOptionIDSchema } from './schemas/Octo_ErrorInvalidOptionID';
export { octo_ErrorInvalidProductIDSchema } from './schemas/Octo_ErrorInvalidProductID';
export { octo_ErrorInvalidUnitIDSchema } from './schemas/Octo_ErrorInvalidUnitID';
export { octo_ErrorUnauthorizedSchema } from './schemas/Octo_ErrorUnauthorized';
export { octo_ErrorUnprocessableEntitySchema } from './schemas/Octo_ErrorUnprocessableEntity';
export { octo_ExtendReservationBodySchema } from './schemas/Octo_ExtendReservationBody';
export { octo_ExtendReservationErrorResponseSchema } from './schemas/Octo_ExtendReservationErrorResponse';
export { octo_GetBookingRequestSchema } from './schemas/Octo_GetBookingRequest';
export { octo_GetBookingRequest_uuidSchema } from './schemas/Octo_GetBookingRequest_uuid';
export { octo_GetProductRequestSchema } from './schemas/Octo_GetProductRequest';
export { octo_GetProductRequest_idSchema } from './schemas/Octo_GetProductRequest_id';
export { octo_GetProductsRequestSchema } from './schemas/Octo_GetProductsRequest';
export { octo_GetSupplierRequestSchema } from './schemas/Octo_GetSupplierRequest';
export { octo_RequestHeadersSchema } from './schemas/Octo_RequestHeaders';
export { octo_RequestHeadersContentSchema } from './schemas/Octo_RequestHeadersContent';
export { octo_RequestHeaders_octoCapabilitiesSchema } from './schemas/Octo_RequestHeaders_octoCapabilities';
export { octo_ResponseHeadersSchema } from './schemas/Octo_ResponseHeaders';
export { offerSchema } from './schemas/Offer';
export { offerCombinationSchema } from './schemas/OfferCombination';
export { offerComparisonSchema } from './schemas/OfferComparison';
export { offerDiscountSchema } from './schemas/OfferDiscount';
export { offerMembershipsSchema } from './schemas/OfferMemberships';
export { offerRestrictionsSchema } from './schemas/OfferRestrictions';
export { openingHoursSchema } from './schemas/OpeningHours';
export { openingHoursContentSchema } from './schemas/OpeningHoursContent';
export { operatorSchema } from './schemas/Operator';
export { optionSchema } from './schemas/Option';
export { optionContentSchema } from './schemas/OptionContent';
export { optionExtrasSchema } from './schemas/OptionExtras';
export { optionPackagesSchema } from './schemas/OptionPackages';
export { optionPickupsSchema } from './schemas/OptionPickups';
export { optionPricingSchema } from './schemas/OptionPricing';
export { optionQuestionsSchema } from './schemas/OptionQuestions';
export { optionRentalsSchema } from './schemas/OptionRentals';
export { optionRestrictionsSchema } from './schemas/OptionRestrictions';
export { orderSchema } from './schemas/Order';
export { orderCardPaymentsSchema } from './schemas/OrderCardPayments';
export { orderCheckinSchema } from './schemas/OrderCheckin';
export { orderContentSchema } from './schemas/OrderContent';
export { orderGiftsSchema } from './schemas/OrderGifts';
export { orderIdentitiesSchema } from './schemas/OrderIdentities';
export { orderMembershipsSchema } from './schemas/OrderMemberships';
export { orderOffersSchema } from './schemas/OrderOffers';
export { orderPathParamsSchema } from './schemas/OrderPathParams';
export { orderPricingSchema } from './schemas/OrderPricing';
export { orderQuestionsSchema } from './schemas/OrderQuestions';
export { orderVentrataCheckoutSchema } from './schemas/OrderVentrataCheckout';
export { packageAvailabilitySchema } from './schemas/PackageAvailability';
export { packageIncludeSchema } from './schemas/PackageInclude';
export { pageSchema } from './schemas/Page';
export { partnerSchema } from './schemas/Partner';
export { partnerEnumSchema } from './schemas/PartnerEnum';
export { partnersConnectionSchema } from './schemas/PartnersConnection';
export { partnersListConnectionSchema } from './schemas/PartnersListConnection';
export { partnersListConnectionsRequestSchema } from './schemas/PartnersListConnectionsRequest';
export { partnersListConnectionsRequestHeadersSchema } from './schemas/PartnersListConnectionsRequestHeaders';
export { partnersListConnectionsRequestHeaders_octoCapabilitiesSchema } from './schemas/PartnersListConnectionsRequestHeaders_octoCapabilities';
export { partnersListConnectionsRequestHeaders_ventrataPartnerKeySchema } from './schemas/PartnersListConnectionsRequestHeaders_ventrataPartnerKey';
export { paypalGatewaySchema } from './schemas/PaypalGateway';
export { paypalGatewayRequestSchema } from './schemas/PaypalGatewayRequest';
export { paytrGatewaySchema } from './schemas/PaytrGateway';
export { peachGatewaySchema } from './schemas/PeachGateway';
export { pickupPointSchema } from './schemas/PickupPoint';
export { pointSchema } from './schemas/Point';
export { pointGroupSchema } from './schemas/PointGroup';
export { pricingSchema } from './schemas/Pricing';
export { pricingExtrasSchema } from './schemas/PricingExtras';
export { pricingOffersSchema } from './schemas/PricingOffers';
export { pricingPerSchema } from './schemas/PricingPer';
export { pricingUnitSchema } from './schemas/PricingUnit';
export { pricingUnitExtrasSchema } from './schemas/PricingUnitExtras';
export { productSchema } from './schemas/Product';
export { productContentSchema } from './schemas/ProductContent';
export { productGoogleSchema } from './schemas/ProductGoogle';
export { productMembershipsSchema } from './schemas/ProductMemberships';
export { productPackagesSchema } from './schemas/ProductPackages';
export { productPricingSchema } from './schemas/ProductPricing';
export { productRentalsSchema } from './schemas/ProductRentals';
export { productVentrataCheckoutSchema } from './schemas/ProductVentrataCheckout';
export { productVentrataCheckoutContentSchema } from './schemas/ProductVentrataCheckoutContent';
export { questionSchema } from './schemas/Question';
export { questionAnswerSchema } from './schemas/QuestionAnswer';
export { questionInputTypeSchema } from './schemas/QuestionInputType';
export { realaxGatewaySchema } from './schemas/RealaxGateway';
export { redemptionLookupSchema } from './schemas/RedemptionLookup';
export { redemptionLookupQuerySchema } from './schemas/RedemptionLookupQuery';
export { redemptionLookupQueryParamsSchema } from './schemas/RedemptionLookupQueryParams';
export { redemptionLookupRequestSchema } from './schemas/RedemptionLookupRequest';
export { redemptionMethodSchema } from './schemas/RedemptionMethod';
export { refundSchema } from './schemas/Refund';
export { rentalDurationSchema } from './schemas/RentalDuration';
export { requestHeadersSchema } from './schemas/RequestHeaders';
export { resellerSchema } from './schemas/Reseller';
export { resellerStatusSchema } from './schemas/ResellerStatus';
export { resourceSchema } from './schemas/Resource';
export { resourceAllocationSchema } from './schemas/ResourceAllocation';
export { resourceAllocationRequestSchema } from './schemas/ResourceAllocationRequest';
export { resourceGroupSchema } from './schemas/ResourceGroup';
export { responseHeadersSchema } from './schemas/ResponseHeaders';
export { scanSchema } from './schemas/Scan';
export { seatSchema } from './schemas/Seat';
export { selectOptionSchema } from './schemas/SelectOption';
export { sellerSchema } from './schemas/Seller';
export { settlementMethodSchema } from './schemas/SettlementMethod';
export { spreedlyGatewaySchema } from './schemas/SpreedlyGateway';
export { stripeGatewaySchema } from './schemas/StripeGateway';
export { supplierSchema } from './schemas/Supplier';
export { supplierContactSchema } from './schemas/SupplierContact';
export { supplierContentSchema } from './schemas/SupplierContent';
export { taxSchema } from './schemas/Tax';
export { terminalSchema } from './schemas/Terminal';
export { ticketSchema } from './schemas/Ticket';
export { tourGroupSchema } from './schemas/TourGroup';
export { uuidSchema } from './schemas/UUID';
export { uUIDSchema } from './schemas/UUID';
export { unitSchema } from './schemas/Unit';
export { unitContentSchema } from './schemas/UnitContent';
export { unitExtrasSchema } from './schemas/UnitExtras';
export { unitItemSchema } from './schemas/UnitItem';
export { unitItemExtrasSchema } from './schemas/UnitItemExtras';
export { unitItemIdentifierSchema } from './schemas/UnitItemIdentifier';
export { unitItemPricingSchema } from './schemas/UnitItemPricing';
export { unitItemQuestionsSchema } from './schemas/UnitItemQuestions';
export { unitItemRedemptionSchema } from './schemas/UnitItemRedemption';
export { unitMembershipsSchema } from './schemas/UnitMemberships';
export { unitPricingSchema } from './schemas/UnitPricing';
export { unitQuestionsSchema } from './schemas/UnitQuestions';
export { unitRedemptionSchema } from './schemas/UnitRedemption';
export { unitRestrictionsSchema } from './schemas/UnitRestrictions';
export { unitTypeSchema } from './schemas/UnitType';
export { updateGiftBodySchema } from './schemas/UpdateGiftBody';
export { updateGiftPathParamsSchema } from './schemas/UpdateGiftPathParams';
export { updateIdentityBodySchema } from './schemas/UpdateIdentityBody';
export { updateIdentityPathParamsSchema } from './schemas/UpdateIdentityPathParams';
export { updateOrderBodySchema } from './schemas/UpdateOrderBody';
export { updateOrderPricingBodySchema } from './schemas/UpdateOrderPricingBody';
export { userSchema } from './schemas/User';
export { vivawalletGatewaySchema } from './schemas/VivawalletGateway';
export { waitlistSchema } from './schemas/Waitlist';
export { waitlistUnitIdentifierSchema } from './schemas/WaitlistUnitIdentifier';
export { waitlistUnitItemIdentifierSchema } from './schemas/WaitlistUnitItemIdentifier';
export { webhookSchema } from './schemas/Webhook';
export { webhookEventSchema } from './schemas/WebhookEvent';
export { whoAmISchema } from './schemas/WhoAmI';
export { whoAmIRequestSchema } from './schemas/WhoAmIRequest';
